### PR TITLE
AC Test Fix - LRAC-14799 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14799

**Problem:**
`CustomEventsAttributeSettings#RenameAttributeDisplayName` modified the Display Name of the `category` attribute and when `CustomEventsSavingAnalysis#UserWithMemberPermissionCanViewAndCreateAnalysisReport` was executed, it did not add the `category` attribute to the filter because the Display Name expected by this test was `category` and the other test had changed it to `category Display Name`

**Solution:**
I modified `CustomEventsAttributeSettings#RenameAttributeDisplayName` to use the `team` attribute to change the Display Name since this attribute is not used in any other test, so it will not impact other cases

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks for adding this change

**Review by nkkwon — APPROVED** [review]
LGTM!

**Review by manuferreira — APPROVED** [review]
Thanks for the investigation. :tada:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
