### PR TITLE
AC Automated Test - LRAC-11502 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11502 (Ticket)
https://issues.liferay.com/browse/LRAC-8103 (Bug 1)
https://issues.liferay.com/browse/LRAC-9457 (Bug 2)
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1920973835&testrayRunId=1921304939)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Well done! LGTM

**Review by calvinctvo — APPROVED** [review]
Amazing work @ViniLopes20 ! LGTM

**Review by christianstokes — APPROVED** [review]
Very nice, thanks @ViniLopes20. Approved!

**Review by manuferreira — APPROVED** [review]
LGTM, thanks a lot :tada:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
