### PR TITLE
AC Automation Improvements - LRAC-13440 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
**Tickets:**
https://liferay.atlassian.net/browse/LRAC-14082 (Story)
https://liferay.atlassian.net/browse/LRAC-13440 (Enable Ticket)

**Testray:**
- [Testray Results with some tests related to the property](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2446759440)
- [Testray Results Acceptance](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2447482285)
- [Testray Results Analytics Cloud Suite](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2447852063) - 60% of the tests passed (a similar number to the CI routine) and I did not observe any regression. I see that `tearDown` is running successfully in tests

**Data Souce:**
We have no planning or story created to enable the deletion of the data source again

**TearDown:**
I moved `tearDownAC` to the end to ensure that the connection will be broken before and after that, so all present properties can be deleted. Only the demo property cannot be deleted, so the `deleteAllProperties` macro will always check the checkbox for all properties and then uncheck the checkbox for the demo property

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hey team, we need to review and forward this [PR](https://github.com/liferay-ac/liferay-portal/pull/771) first to avoid conflicts in this other one when it goes to bchan

**Review by joshitagaki — APPROVED** [review]
Thanks for updating this! LGTM!

**Review by nkkwon — APPROVED** [review]
Thanks for working on this LGTM! :+1:

**Review by manuferreira — APPROVED** [review]
Hey Vini, thanks for taking some time to look into this :muscle: :detective:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
