### PR TITLE
LRAC-14488 Rename | master

### PR DESCRIPTION
**Pull request by lesliewong92**
https://liferay.atlassian.net/browse/LRAC-14488

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:forward

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:stable

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
