### PR TITLE
LRAC-14113 Refactor Loading Component

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issues: https://issues.liferay.com/browse/LRAC-14113, https://issues.liferay.com/browse/LRAC-14118

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hey @interaminense, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Review by fmarcio — APPROVED** [review]
LGTM! thanks a lot @interaminense :rocket:

**Comment by interaminense** [comment]
ci:forward:force

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:test:table

**Comment by interaminense** [comment]
ci:test:stable

**Pull request closed without merging**
