### PR TITLE
LRAC-11981 - [F] Create modal to assign channels and sites to the property

### PR DESCRIPTION
**Pull request by ilzamcmed**

### CODE REVIEW

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @ilzamcmed!!

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:stop

**Comment by ilzamcmed** [comment]
ci:stop

**Comment by ilzamcmed** [comment]
Closing this PR because tests are frozen with issues.

**Comment by ilzamcmed** [comment]
PR moved here: https://github.com/liferay-ac/liferay-portal/pull/130

**Pull request closed without merging**
