### PR TITLE
AC Test fix - LRAC-12809 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-12809
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2172341268&testrayRunId=2172341313)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM @joshitagaki, thanks for working on ti 🎉

**Review by calvinctvo — APPROVED** [review]
Thanks Josh for the fix!

**Review by manuferreira — APPROVED** [review]
Hey Josh, thank you! :tada:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
