### PR TITLE
QA Automation - LRAC-14444, LRAC-14445 and LRAC-14542 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
Hello! These are the automations related to:

- https://liferay.atlassian.net/browse/LRAC-14444
- https://liferay.atlassian.net/browse/LRAC-14445
- https://liferay.atlassian.net/browse/LRAC-14542

Related to these stories:

- https://liferay.atlassian.net/browse/LRAC-14220
- https://liferay.atlassian.net/browse/LRAC-14101

Echo Team Note:
Some tests from the echo team were deleted and others were ignored as they used features that will no longer be present in AB test after the stories of improvements from the AC team. The Echo team will be notified before the PR is forwarded

Removed because we no longer have tabs in the AB test side panel:

- ABTesting#DeleteHistoryTab
- ABTesting#HistoryTabListedDescModifiedDate

Ignored because it is no longer possible to create more than one variant for the same Test:

- ABTesting#CheckContentPersistAfterEditVariant
- ABTesting#CheckVariantDeletedInAC
- ABTesting#EditVariant
- ABTesting#EditVariantSameName
- ABTesting#ReviewAndStartRunCheckInfo
- ABTesting#ReviewAndStartSum100

Since I edited some tests from the echo team and the changes related to the AB test stories will be included in future releases, I think we have to block this PR in the meantime. 🙂

### CODE REVIEW

**Comment by joshitagaki** [comment]
Thanks for working on this! Just a comment about ignoring some of the tests that use multiple variants. 

I think some of these tests still provide value, but will need to be updated to only include one variant. 
- ABTesting#CheckContentPersistAfterEditVariant
- ABTesting#CheckVariantDeletedInAC
- ABTesting#EditVariant
- ABTesting#ReviewAndStartRunCheckInfo
- ABTesting#ReviewAndStartSum100
So instead of ignoring them can we update the test to only use one variant? Or maybe we can update those tests in another ticket? Let me know what you think.

**Comment by ViniLopes20** [comment]
Covered by https://github.com/liferay-ac/liferay-portal/pull/698

**Comment by ViniLopes20** [comment]
> Thanks for working on this! Just a comment about ignoring some of the tests that use multiple variants.
> 
> I think some of these tests still provide value, but will need to be updated to only include one variant.
> 
> * ABTesting#CheckContentPersistAfterEditVariant
> * ABTesting#CheckVariantDeletedInAC
> * ABTesting#EditVariant
> * ABTesting#ReviewAndStartRunCheckInfo
> * ABTesting#ReviewAndStartSum100
> 
> So instead of ignoring them can we update the test to only use one variant? Or maybe we can update those tests in another ticket? Let me know what you think.

Hey Josh, these tests are from the Echo team. I updated some of their tests that I noticed would be necessary because of the story changes. But I set these as ignored so that they can observe and make the necessary updates. I don't think it's necessary to create more than one variant, but as they are not our tests, I think the best thing would be for them to analyze and check whether they are just going to remove the use of the second variant or not. What do you think?

**Comment by joshitagaki** [comment]
> Hey Josh, these tests are from the Echo team. I updated some of their tests that I noticed would be necessary because of the story changes. But I set these as ignored so that they can observe and make the necessary updates. I don't think it's necessary to create more than one variant, but as they are not our tests, I think the best thing would be for them to analyze and check whether they are just going to remove the use of the second variant or not. What do you think?

Ok I agree with this approach. We can inform them about these changes and suggest removing the second variant once we finish the automation.

**Pull request closed without merging**
