### PR TITLE
LPD-16635 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LPD-16635

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
