### PR TITLE
AC Test Fix - LRAC-14555 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14555

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Review by ViniLopes20 — APPROVED** [review]
Very good, Josh. This correction will help me with another ticket that I have. LGTM 🎉

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks, Josh! :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
