### PR TITLE
LRAC-15322 Uncaught ReferenceError: Analytics is not defined when rendering DPT

### PR DESCRIPTION
**Pull request by Mikellorza**
Coming from https://github.com/liferay-ac/liferay-portal/pull/991. I am sending again because of rebase error when brian went to do the rebase, please see: https://github.com/brianchandotcom/liferay-portal/pull/145904#issuecomment-1877485081 

@rachaelkoestartyo @marcellustavares 

Fix two bugs:

1. https://liferay.atlassian.net/browse/LRAC-15322
2. https://liferay.atlassian.net/browse/LRAC-15321

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @Mikellorza, someone broke the AC build locally on `master`. So AC acceptance tests won't work to check if your modifications will cause anything to the AC. We cannot guarantee this

**Comment by marcellustavares** [comment]
@ViniLopes20 stable and relevant are also failing.

**Comment by ViniLopes20** [comment]
**Relevant Failure:**
- [PortalDatabaseValidationUpgrade#CompareUpgradedAndFreshDatabaseSchemas621021](https://testray.liferay.com/home/-/testray/case_results/2482779159?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2482778984%26testrayRunId%3D2482779032%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) - I observe in the history that it doesn't just fail in its PR, so I believe it's not a regression
- [PortalSmoke#Smoke](https://testray.liferay.com/home/-/testray/case_results/2482779123/history?tab=result&hideFilterPin=true) - I observe in the history that it doesn't just fail in its PR, so I believe it's not a regression
- The other test that fails is the AC test which is caused by a problem building the AC, this was caused by someone else and not by this PR

**Stable Failure:**
I'm going to run just `stable` again to be able to isolate the error

cc: @marcellustavares and @Mikellorza

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:forward:force

**Pull request closed without merging**
