### PR TITLE
LPS-198681 - Apply --control-menu-container-height css variable to analytics-reports-web.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPS-198681

This PR is consistently applying the use of the --control-menu-container-height css variable to handle the offset for elements that have a fixed position.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @ethib137, the failure of `acceptance` is related to this [bug](https://liferay.atlassian.net/browse/LRAC-13481). The PR looks good to be forwarded. Thanks!

**Comment by ethib137** [comment]
ci:forward

**Pull request closed without merging**
