### PR TITLE
LPD-35878 | Test Fix | Poshi >>> Playwright

### PR DESCRIPTION
**Pull request by rafaellajordao**
### Motivation:
Test failing due to Poshi limitations.

### Proposed Solution:
Transcribe test to playwright in order to facilitate maintenance.

**More details:** [LPD-35878](https://liferay.atlassian.net/browse/LPD-35878)

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:analytics-cloud

**Review by interaminense — APPROVED** [review]
LGTM, thanks @rafaellajordao!

**Comment by rafaellajordao** [comment]
ci:foward

**Comment by rafaellajordao** [comment]
ci:forward

**Pull request closed without merging**
