### PR TITLE
AC Test Fix - LRAC-14842 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14842
https://liferay.atlassian.net/browse/LRAC-14017

**Problem:**
Currently, the test tries to check if the number of unique victors has changed in the Sites area. These metrics depend on the session, so it takes time to appear on the dashboard.

**Solution:**
The test must verify if the total number of individuals who interacted with the AC has changed.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! I think this change is fine for this test. LGTM

**Review by nkkwon — APPROVED** [review]
LGTM! :+1: Thank you for working on this!

**Review by manuferreira — APPROVED** [review]
Thanks for the adaptations Vini :slightly_smiling_face:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
