### PR TITLE
LRAC-15243 | master

### PR DESCRIPTION
**Pull request by lesliewong92**
https://liferay.atlassian.net/browse/LRAC-15243

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:upgrade

**Comment by lesliewong92** [comment]
ci:test:startup

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:test:analytics-cloud-acceptance

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
