### PR TITLE
LRAC-14747 | master

### PR DESCRIPTION
**Pull request by lesliewong92**
https://liferay.atlassian.net/browse/LRAC-14747

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
