### PR TITLE
AC Remove from quarantine - LRAC-11263 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11263
Passing consistently
[Testray](https://testray.liferay.com/home/-/testray/case_results/2154122430/history?tab=result&hideFilterPin=true)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good, thanks for looking at this case, Josh 🎉

**Review by manuferreira — APPROVED** [review]
Thank you, Josh! :muscle:

**Review by calvinctvo — APPROVED** [review]
Thanks for enable this test again Josh

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
