### PR TITLE
[F] LRAC 13328 - Upgrade Clay Modal component to latest version

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://issues.liferay.com/browse/LRAC-13328

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by interaminense** [comment]
Hey @fmarcio, could you remove this commit from your PR? https://github.com/liferay-ac/liferay-portal/pull/403/commits/cf05154ee972ef4aa9176ae21925e2804333def6 unit tests will be disabled for while on master branch

**Comment by fmarcio** [comment]
Closing this PR because it will sendo to another repo

**Comment by fmarcio** [comment]
resent to @interaminense liferay-portal repo. https://github.com/interaminense/liferay-portal/pull/354

**Pull request closed without merging**
