### PR TITLE
Disable AC Automation - LRAC-14775 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14775

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM

**Review by nkkwon — APPROVED** [review]
Thank you LGTM!

**Review by manuferreira — APPROVED** [review]
I believe we can cover at least one of those tests using personas, right? They will come just from one channel but I believe it's a start. Thank you! :detective:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
