### PR TITLE
AC Automated Test - LRAC-12144 and LRAC-12147 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
- https://issues.liferay.com/browse/LRAC-12147 (Test Automation Ticket)
[Test Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2049434123)

- https://issues.liferay.com/browse/LRAC-12144 (Test Automation Ticket)
[Test Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2055714961)

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Nice! Thanks @calvinctvo. LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you, it's really good :clap: :tada:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
