### PR TITLE
LPD-26598

### PR DESCRIPTION
**Pull request by ivicac**

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:analytics-cloud

**Comment by ViniLopes20** [comment]
Hey @ivicac, thanks for fixing this and running the tests. I analyzed the result here and basically, most of the failures are related to [LPD-26134](https://liferay.atlassian.net/browse/LPD-26134) and other failures are related to other bug tickets. So your modification is working and tests are running after successfully creating the faro image locally. Thanks

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
