### PR TITLE
LRAC-13685 remove AC calls for every anonymous user

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
relevant failures don't seem relevant 🤔

**Pull request closed without merging**
