### PR TITLE
AC Delete Automation Test - LRAC-14716 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14714 (Bug)
https://liferay.atlassian.net/browse/LRAC-14716

**Context:**
We had two test cases that were validating the functionality with incorrect behavior that was not expected by the product team. Basically, if we have a custom event blocked, it should still appear in the Event analysis or segment list, but no new interactions generated for that event will be processed.

If the custom event is hidden, then it will not appear in the event analysis and segment list.

The two test cases that were wrong were deleted from the test map and this is the automation we had created to cover these cases: `CustomEventsUnblockEvents#ViewEventIsVisibleOrNotInEventAnalysisWhenBlockedOrUnblocked`

**Test Case:**
- Blocked event is hidden in the Event Analysis events lists
- Unblocked event is visible in the Event Analysis events lists

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by nkkwon — APPROVED** [review]
LGTM! :+1:

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you! :detective:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
