### PR TITLE
LPD-35689 | Quarantining tests that need to be reviewed

### PR DESCRIPTION
**Pull request by rafaellajordao**
### Motivation:
Tests failing Due to a Poshi limitation, virtual instance properties are not compatible with CA tests. See comments: [LRCI-3822](https://liferay.atlassian.net/browse/LRCI-3822)

### Proposed Solution:
Quarantine tests, review and check what can be migrated to playwright.

More details: [LPD-35689](https://liferay.atlassian.net/browse/LPD-35689)

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:analytics-cloud

**Review by marcosapmf — APPROVED** [review]

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:analytics-cloud

**Comment by rafaellajordao** [comment]
ci:forward

**Pull request closed without merging**
