### PR TITLE
AC Test fix - LRAC-11132 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11132

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks Vini.

**Review by calvinctvo — APPROVED** [review]
LGTM, thanks Vini for the fix

**Review by joshitagaki — APPROVED** [review]
LGTM. Thanks for fixing this!

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
