### PR TITLE
AC Test Fix - LRAC-11941 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11941
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2012157665)
Hey guys looking more into the test, I noticed that it still runs past the add user step and fails when trying to go to admin page. Did not find a reason why the step fails when creating a user and it looks like the test passes with these changes.

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
It makes sense to open AC url before accessing AC Admin to avoid skipping over accessing admin. LGTM!

**Review by ViniLopes20 — APPROVED** [review]
Thanks for it, Josh. LGTM 🎉 .

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks Josh :tada:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
