### PR TITLE
LPD-6540 | Master

### PR DESCRIPTION
**Pull request by interaminense**
Jira issue: https://issues.liferay.com/browse/LPD-6540

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
I made some changes to the client SDK so that Analytics API can receive a `cookieManager`. This way, 3rd party cookies can manage cookies.

**CookieManager API**

```
{
   actions: {
      getItem: () => {},
      setItem: () => {},
      removeItem: () => {},
      getItemFromLocalStorage: () => {},
      onConsentChange: () => {
      },
      enabled: boolean, // Enable / Disable cookie manager
      checkConsent: boolean // Check the user consent
   }
}
```

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
