### PR TITLE
LPS-199328 Follow up

### PR DESCRIPTION
**Pull request by JLucasM**
LPS-199328: [Jira Issue](https://liferay.atlassian.net/browse/LPS-199328)

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
Hey @JLucasM, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
