### PR TITLE
LRAC-12695 fix account groups search

### PR DESCRIPTION
**Pull request by thiago-buarqque**

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
LGTM

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
