### PR TITLE
LRAC-11500 Migrate FARO to Portal Master

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://issues.liferay.com/browse/LRAC-11500

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Review by matthewkong — APPROVED** [review]

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:acceptance-release

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by susanchen3** [comment]
ci:test:bundle

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:stop

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @interaminense,

No regression was found in the analysis of the [acceptance](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2248789686) and [relevant](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2248150614) suites. `ant all` is also working and no regressions were found in exploratory tests. So the PR is approved to go to Brian through the QA team ✅ 

Thanks 😄

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
