### PR TITLE
LRAC-14397 Apply timezone for custom ranges

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://liferay.atlassian.net/browse/LRAC-14397

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
resent https://github.com/liferay-ac/liferay-portal/pull/933

**Pull request closed without merging**
