### PR TITLE
LRAC-12602 addapt comparator to XML fields with locale

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Follow up related to [LRAC-12602](https://issues.liferay.com/browse/LRAC-12602)

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:sf

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
Test passing locally, running relevant again

**Review by riccardo-ferrari — APPROVED** [review]

**Comment by riccardo-ferrari** [comment]
ci:forward

**Pull request closed without merging**
