### PR TITLE
LRAC-12959 UI inconsistency when ordering the orders attributes by data type

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://issues.liferay.com/browse/LRAC-12959

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Review by ilzamcmed — APPROVED** [review]
LGTM! :rocket:

**Review by interaminense — CHANGES_REQUESTED** [review]
Hi @fmarcio, increase column width instead, please. Thanks!

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
> Hi @fmarcio, increase column width instead, please. Thanks!

@interaminense done! :-)

**Review by JLucasM — APPROVED** [review]
LGTM!

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @fmarcio!

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
