### PR TITLE
LPD-32795 | master

### PR DESCRIPTION
**Pull request by fmarcio**
Jira ticket https://liferay.atlassian.net/browse/LPD-32795

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
