### PR TITLE
AC Test fix - LRAC-11566 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11566

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Hey @joshitagaki ! Thanks for working on this, LGTM

**Review by manuferreira — APPROVED** [review]
Hey @joshitagaki nice fix. I guess we don't have any tests to delete a specific breakdown? Since the update you did in the macro will delete all breakdowns, right?

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks for it Josh 🎉

**Comment by joshitagaki** [comment]
@manuferreira Yea there are no instances where we were to delete a specific breakdown. All instances are being used as cleanup which should be in the teardown. If we do create a test to delete a specific cleanup we would need to create a new macro

**Comment by manuferreira** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
