### PR TITLE
AC Test fix - LRAC-11371 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11371
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1893396674&testrayRunId=1893422449)

The test that failed in Testray was expected because it needs the user and upstream all users are anonymous. I ran this test to check in the log if the `closeAllSessions` macro would work and it is working. The problem was because we restarted the `osbasahredis` container and that made the macro not work, I talked to Marcos and he suggested that we clean the `osbasahredis` container so that the problem does not occur.

I updated two tests that were doing more things than needed.

https-testray-liferay-com-reports-production-logs-2022-06-test-1-25-test-portal-acceptance-pullrequest-master-3428-functional-tomcat90-mysql57-jdk8-0-0-jenkins-console-txt-gz-authuser-0

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by manuferreira** [comment]
Hey @ViniLopes20 I remember some time ago that we added something similar (?) to solve the problem with the individuals taking some time to show up. Is this something related to it?

**Comment by ViniLopes20** [comment]
> Hey @ViniLopes20 I remember some time ago that we added something similar (?) to solve the problem with the individuals taking some time to show up. Is this something related to it?

Hey @manuferreira, I think what you're talking about is putting the page with a blog or some other assets. I think this might still help, but I think it wasn't helping as much because this macro wasn't working. I hope it works again and helps us again.

**Comment by manuferreira** [comment]
> > Hey @ViniLopes20 I remember some time ago that we added something similar (?) to solve the problem with the individuals taking some time to show up. Is this something related to it?
> 
> Hey @manuferreira, I think what you're talking about is putting the page with a blog or some other assets. I think this might still help, but I think it wasn't helping as much because this macro wasn't working. I hope it works again and helps us again.

Actually I was talking about that change Leo made when he "restarted" the container (or something like that) related to individuals. Do you remember this?

**Comment by ViniLopes20** [comment]
> 

Ohhh ok. That was the problem. We are down the redis container and up it again, but Poshi was executing the closing of the sessions before the container was up again. So we're not going to take down the container anymore, we're just going to clear the cache and data from the container. The behavior and the benefit will be the same for us, at least I hope it is hahaha.

**Comment by ViniLopes20** [comment]
> > > Hey @ViniLopes20 I remember some time ago that we added something similar (?) to solve the problem with the individuals taking some time to show up. Is this something related to it?
> > 
> > 
> > Hey @manuferreira, I think what you're talking about is putting the page with a blog or some other assets. I think this might still help, but I think it wasn't helping as much because this macro wasn't working. I hope it works again and helps us again.
> 
> Actually I was talking about that change Leo made when he "restarted" the container (or something like that) related to individuals. Do you remember this?

Ohhh ok. That was the problem. We are down the redis container and up it again, but Poshi was executing the closing of the sessions before the container was up again. So we're not going to take down the container anymore, we're just going to clear the cache and data from the container. The behavior and the benefit will be the same for us, at least I hope it is hahaha.

**Comment by joshitagaki** [comment]
> > > > Hey @ViniLopes20 I remember some time ago that we added something similar (?) to solve the problem with the individuals taking some time to show up. Is this something related to it?
> > > 
> > > 
> > > Hey @manuferreira, I think what you're talking about is putting the page with a blog or some other assets. I think this might still help, but I think it wasn't helping as much because this macro wasn't working. I hope it works again and helps us again.
> > 
> > 
> > Actually I was talking about that change Leo made when he "restarted" the container (or something like that) related to individuals. Do you remember this?
> 
> Ohhh ok. That was the problem. We are down the redis container and up it again, but Poshi was executing the closing of the sessions before the container was up again. So we're not going to take down the container anymore, we're just going to clear the cache and data from the container. The behavior and the benefit will be the same for us, at least I hope it is hahaha.

So from what I understand in the conversation was that Poshi did not fully close the sessions before bringing back up the container so we're seeing some issues. To resolve that we are not tearing it down but clearing the cache and data. Doing that we should hopefully see some improvements with our data processing. Is that correct?

**Comment by ViniLopes20** [comment]
> > > > > Hey @ViniLopes20 I remember some time ago that we added something similar (?) to solve the problem with the individuals taking some time to show up. Is this something related to it?
> > > > 
> > > > 
> > > > Hey @manuferreira, I think what you're talking about is putting the page with a blog or some other assets. I think this might still help, but I think it wasn't helping as much because this macro wasn't working. I hope it works again and helps us again.
> > > 
> > > 
> > > Actually I was talking about that change Leo made when he "restarted" the container (or something like that) related to individuals. Do you remember this?
> > 
> > 
> > Ohhh ok. That was the problem. We are down the redis container and up it again, but Poshi was executing the closing of the sessions before the container was up again. So we're not going to take down the container anymore, we're just going to clear the cache and data from the container. The behavior and the benefit will be the same for us, at least I hope it is hahaha.
> 
> So from what I understand in the conversation was that Poshi did not fully close the sessions before bringing back up the container so we're seeing some issues. To resolve that we are not tearing it down but clearing the cache and data. Doing that we should hopefully see some improvements with our data processing. Is that correct?

Exactly @joshitagaki, I think that with the session closing macro working again and clearing the redis cache, I hope the processing will be faster. I remember when Leo and I made the macro to clear the cache we had a lot of tests passing, but then the close macro started to fail and the tests also started to fail a lot.

**Review by joshitagaki — APPROVED** [review]
Nice job finding the solution for the sessions! Hopefully we'll see better results because of it. Also nice catch in the tests. LGTM!

**Review by calvinctvo — APPROVED** [review]
Thank you @ViniLopes20 , hopefully these changes will process data faster. Really nice work 🎉

**Comment by ViniLopes20** [comment]
ci:stop

**Comment by ViniLopes20** [comment]
resend https://github.com/liferay-ac/liferay-portal/pull/46

**Pull request closed without merging**
