### PR TITLE
LRAC-14492 Add new columns to render count of Sites and Channels

### PR DESCRIPTION
**Pull request by JLucasM**
LRAC-14492: [Jira Issue](https://liferay.atlassian.net/browse/LRAC-14492#)

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
@JLucasM why this PR is on hold? Thanks

**Comment by fmarcio** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM!

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
