### PR TITLE
AC Test Fix - LRAC-11962 | master

### PR DESCRIPTION
**Pull request by manuferreira**
[Jira ticket](https://issues.liferay.com/browse/LRAC-11962)
[Testray execution](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2008317734&testrayRunId=2008317804)

- Hey guys, I don't think it's necessary to create a new XPath or macro, since we are able to use the original generic text xpath to validate the texts.
- The reason I'm doing this: `textValueList = "Email Reports: ,Disabled"` it's because in the email report we have a line break, so it's only possible to validate these cases by passing a list to the macro and giving some space between the elements.

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks for fixing this

**Review by calvinctvo — APPROVED** [review]
Thank you for this fix @manuferreira ! LGTM

**Review by ViniLopes20 — APPROVED** [review]
Very good solution, Manu. Thank you for that! LGTM 🎉

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
