### PR TITLE
AC Automation Improvements - LRAC-14011 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14011

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good analysis, Josh. Individuals appear faster is something that will help a lot in most of our tests. Thank you for that. LGTM

**Review by nkkwon — APPROVED** [review]
LGTM! Thank you for working on this Josh!

**Review by manuferreira — APPROVED** [review]
Hey Josh, thanks for this! LGTM. :muscle: :detective:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
