### PR TITLE
LPD-24267 | master

### PR DESCRIPTION
**Pull request by riccardo-ferrari**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:forward

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
