### PR TITLE
AC Test Fix - LRAC-12693 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-12693

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Good catch, Josh. LGTM! 🎉

**Review by manuferreira — APPROVED** [review]
Thank you, Josh! :muscle:

**Review by calvinctvo — APPROVED** [review]
Nice catch @joshitagaki ! Thanks for the fix

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
