### PR TITLE
AC Test Fix - LPD-28680 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LPD-28680

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
acceptance failure should be fixed by https://github.com/liferay-ac/liferay-portal/pull/1637

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/1643

**Pull request closed without merging**
