### PR TITLE
LRAC-11979 - [F] Make request to get properties from backend

### PR DESCRIPTION
**Pull request by ilzamcmed**

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by interaminense** [comment]
Resent https://github.com/liferay-ac/liferay-portal/pull/123

**Pull request closed without merging**
