### PR TITLE
LPD-40587 | Refactor Playwright Test

### PR DESCRIPTION
**Pull request by rafaellajordao**
### :information_source: Motivation:

Refactor tests to improve the way it sends events to the AC.

### :heavy_check_mark: Proposed Solution:

Send custom events through the HTML fragment and not through the page's javascript.

more details: [LPD-40587](https://liferay.atlassian.net/browse/LPD-40587)

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:analytics-cloud

**Comment by rafaellajordao** [comment]
ci:test:analytics-cloud

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
