### PR TITLE
LPD-39719 LPD-39720 LPD-39723 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
resent https://github.com/liferay-ac/liferay-portal/pull/1976

**Pull request closed without merging**
