### PR TITLE
LPD-1181 | master

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:forward:force

**Comment by marcosapmf** [comment]
@sillascavalcanti can you please fix the sf issue?
Thanks

**Comment by marcosapmf** [comment]
ci:stop

**Comment by marcosapmf** [comment]
ci:test:stop

**Comment by sillascavalcanti** [comment]
ci:close

**Comment by sillascavalcanti** [comment]
Resend to https://github.com/liferay-ac/liferay-portal/pull/1484

**Pull request closed without merging**
