### PR TITLE
AC Test Fix LRAC-14264 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14264

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good, Josh. Thank you for updating these paginations. LGTM 🎉

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for working on this! :muscle:

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
