### PR TITLE
LPD-24181 - Dividing the title with splitTextToSize and adapting the size of the containers

### PR DESCRIPTION
**Pull request by sillascavalcanti**
[Issue](https://liferay.atlassian.net/browse/LPD-24181)

### CODE REVIEW

**Comment by sillascavalcanti** [comment]
ci:test:sf

**Comment by sillascavalcanti** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Review by interaminense — CHANGES_REQUESTED** [review]
It needs to fix the heading height. I talked to @sillascavalcanti personally about it

**Comment by sillascavalcanti** [comment]
ci:test:sf

**Comment by sillascavalcanti** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
Resent https://github.com/liferay-ac/liferay-portal/pull/1524

**Pull request closed without merging**
