### PR TITLE
AC Test Fix - LRAC-11938 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11938 (Automation ticket)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks Vini :tada:

**Comment by joshitagaki** [comment]
Hey Vini! Looking at the test it seems like this issue is pretty flaky. The demo data source are sometimes deleted before running this test causing this issue. Other times the demo data will be available and the test will pass. I suggest changing it so the test runs on its own so it won't be as flaky. 
`property test.name.skip.portal.instance = "AnalyticsCloudConnectionTest#CancelCreatingDxpDataSource";`

**Review by calvinctvo — APPROVED** [review]
Hey @ViniLopes20 ! Thanks for fixing the issue. LGTM! Regarding what Josh stated. I think it'd would make sense to batch the connection tests together to efficiently use CI resource. I'm not sure running the test on its own batch would be efficient use of CI resources. What do you think?

**Comment by ViniLopes20** [comment]
Hey @joshitagaki and @calvinctvo, thanks for that, I was thinking the same thing. I think isolating the test may not be the final solution because there will be data source from the demo created, so I think the best solution would be to create a new workspace for the test to use a new workspace that has no data source created

**Comment by ViniLopes20** [comment]
Hey guys, I made the changes. I think now the test will no longer be flaky. What do you think?

cc: @joshitagaki @calvinctvo

**Review by joshitagaki — APPROVED** [review]
Great job! LGTM, Thanks Vini!

**Comment by joshitagaki** [comment]
@calvinctvo We should take a look again at the tests we currently have that are running as it's own batch and see if we can remove it. I think this test in particular would need to run on it's own batch due to it depending on if it is the first test to run or not. I'll start a conversation on our qa channel to get everyone's opinion.

**Review by calvinctvo — APPROVED** [review]
Thanks for the great solution @ViniLopes20 ! LGTM!

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
