### PR TITLE
LRAC-14015 - The Contact Sales button is secondary

### PR DESCRIPTION
**Pull request by ilzamcmed**
Jira issue: https://issues.liferay.com/browse/LRAC-14015

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @ilzamcmed

**Comment by interaminense** [comment]
ci:forward

**Comment by ilzamcmed** [comment]
ci:forward

**Comment by ilzamcmed** [comment]
ci:stop

**Pull request closed without merging**
