### PR TITLE
AC Test Fix/Enable Test - LRAC-11490 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11490

⚠️ **Affected tests:**

**CustomEventsFilterBreakdown#AddMaxOf3AttributesToEvent** (Disabled)
**CustomEventsFilterBreakdown#AssertDataChangeWhenRearrangeBreakdownAndReturnOriginalState** (Disabled)
**CustomEventsFilterBreakdown#SortTheResultsAnalysisAfterRearrangingBreakdowns** (Disabled)

**CustomEventsSavingAnalysis#CanChangeAttributeTypeInUseWithoutAffectingExistingAnalysisReports** (The test has been adapted to use only one breakdown, but it is good to revert to using more than one breakdown)
**CustomEventsSavingAnalysis#CanEditAnalysisReport** (The test has been adapted to use only one breakdown, but it is good to revert to using more than one breakdown)

**CustomEventsFilterBreakdown#AssertAttributeBreakdownsSortedByHighestEventCount** (I think this test doesn't need to add more than one breakdown to work)
**CustomEventsFilterBreakdown#AssertTheAnalysisResultIsSorted** (I think this test doesn't need to add more than one breakdown to work)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by christianstokes — APPROVED** [review]
LGTM thanks for fixing and enabling this again Vini

**Review by calvinctvo — APPROVED** [review]
Thanks @ViniLopes20 for enable these tests! LGTM

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks @ViniLopes20

**Review by manuferreira — APPROVED** [review]
LGTM, thanks Vini :clap:

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
