### PR TITLE
[F] LRAC-15402 remove URL from popover

### PR DESCRIPTION
**Pull request by fmarcio**
https://liferay.atlassian.net/browse/LRAC-15402

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:stable

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by fmarcio** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by fmarcio** [comment]
ci:test:stable

**Comment by fmarcio** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by fmarcio** [comment]
ci:stop

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
