### PR TITLE
AC Test Improvement - LRAC-14075 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14075

Description:
Explanation of the PR in the ticket description

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks my friend :muscle:

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by nkkwon — APPROVED** [review]
LGTM! :+1:

**Pull request closed without merging**
