### PR TITLE
AC Automated Test - LRAC-11433 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11433 (Automation Ticket)
https://issues.liferay.com/browse/LRAC-11366 (Bug)
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1903988089&testrayRunId=1903988151)

I noticed some tests that were disabled because of changing empty state stories. The story is already finished, so I'm activating these tests again.

### CODE REVIEW

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks @ViniLopes20

**Review by calvinctvo — APPROVED** [review]
Hey @ViniLopes20 Thanks for activating these tests again! LGTM

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
