### PR TITLE
AC Automated Test - LRAC-12352 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
Automation ticket - https://issues.liferay.com/browse/LRAC-12352
[Test Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2087229642)

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good, Calvin. Thank you for that. LGTM 🎉

**Review by manuferreira — APPROVED** [review]
Hey Calvin, thanks for the automation and the update on the macro :muscle:

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks Calvin!

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
