### PR TITLE
AC Test Fix - LRAC-13679 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-13679
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2306722738&testrayRunId=2306722996)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Good catch, Josh. LGTM 🎉

**Review by manuferreira — APPROVED** [review]
Thanks for the investigation. LGTM! :male_detective:

**Review by nkkwon — APPROVED** [review]
LGTM! Thank you! :+1:

**Pull request closed without merging**
