### PR TITLE
AC Test Improvement - LRAC-12840 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-12840

ℹ️
A new branch is created in Asah (3.6.x), so we need to create a rule for the CI to know which matching pair to use to build the AC to run the tests on PRs that are going to that branch

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks Vini

**Review by calvinctvo — APPROVED** [review]
Hey Vini! Thanks for modifying the test property!

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you Vini :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
