### PR TITLE
LRAC-13773 Adjust Faro Admin table

### PR DESCRIPTION
**Pull request by JLucasM**
LRAC-13773: [Jira Issue](https://issues.liferay.com/browse/LRAC-13773)

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by JLucasM** [comment]
ci:test:sf

**Review by interaminense — APPROVED** [review]
LGTM, thanks!

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
