### PR TITLE
LPD-20905 | master

### PR DESCRIPTION
**Pull request by ivicac**

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by marcosapmf — APPROVED** [review]

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ivicac** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ivicac** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
