### PR TITLE
LRAC-12505 - [BUG] When syncing accounts and contacts through the toggle the number of accounts/users/organizations is reset to zero

### PR DESCRIPTION
**Pull request by ilzamcmed**
https://issues.liferay.com/browse/LRAC-12505

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Review by JLucasM — APPROVED** [review]
LGTM!

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:foward

**Comment by ilzamcmed** [comment]
ci:forward

**Pull request closed without merging**
