### PR TITLE
AC Disable Test - LRAC-15304 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-15304 (Bug)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
