### PR TITLE
LRAC-14082 [F] Enable Property Deletion from AC

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issues:

https://liferay.atlassian.net/browse/LRAC-14493
https://liferay.atlassian.net/browse/LRAC-14494
https://liferay.atlassian.net/browse/LRAC-14495

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @interaminense, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
Hey @interaminense, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by interaminense** [comment]
Hi @ViniLopes20 it is still failing SF here

**Pull request closed without merging**
