### PR TITLE
LPD-20478 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
forwarded to https://github.com/brianchandotcom/liferay-portal/pull/148277

**Pull request closed without merging**
