### PR TITLE
AC Test Improvement - LRAC-13080 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-13080

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you! :tada: :muscle:

**Review by calvinctvo — APPROVED** [review]
Thanks @ViniLopes20 for the fix! LGTM

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
