### PR TITLE
LPD-33857 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-33857

Backport to 4.9.x in https://github.com/liferay-ac/liferay-portal/pull/1766

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Review by marcellustavares — APPROVED** [review]

**Pull request closed without merging**
