### PR TITLE
LRAC-14746 | master

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:forward

**Comment by marcellustavares** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by marcellustavares** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/753

**Pull request closed without merging**
