### PR TITLE
LRAC-15253/LRAC-15254/LRAC-15255 | master

### PR DESCRIPTION
**Pull request by lesliewong92**
https://liferay.atlassian.net/browse/LRAC-15253
https://liferay.atlassian.net/browse/LRAC-15254
https://liferay.atlassian.net/browse/LRAC-15255

### CODE REVIEW

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:test:startup

**Comment by lesliewong92** [comment]
ci:test:upgrade

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
@lesliewong92 do we hope to get all the test suites green before forwarding the pull?

**Comment by lesliewong92** [comment]
@marcellustavares I don't think we would be able to get test suites all green before fowarding. Still going through all the errors from the different suites. But for now, seems like at least some are errors that are unrelated to the current changes.

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:stable

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:test:startup

**Comment by lesliewong92** [comment]
ci:test:upgrade

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
