### PR TITLE
LRAC-14481 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-14481

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @marcosapmf

**Comment by interaminense** [comment]
ci:forward:force

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
