### PR TITLE
LPD-25239

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LPD-25239

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:analytics-cloud

**Comment by fmarcio** [comment]
ci:test:analytics-cloud

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:forward

**Review by ViniLopes20 — APPROVED** [review]
LGTM @fmarcio. Please, send me a pix

**Pull request closed without merging**
