### PR TITLE
LRAC-12394 Commerce Connections Stuff

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issues: [LRAC-12394](https://issues.liferay.com/browse/LRAC-12394), [LRAC-12386](https://issues.liferay.com/browse/LRAC-12386)

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
