### PR TITLE
LRAC-13923 Fixes

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issues: https://issues.liferay.com/browse/LRAC-13923, https://issues.liferay.com/browse/LRAC-13925, https://issues.liferay.com/browse/LRAC-13948, https://issues.liferay.com/browse/LRAC-13957, https://issues.liferay.com/browse/LRAC-13958

### CODE REVIEW

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ilzamcmed** [comment]
ci:forward:force

**Pull request closed without merging**
