### PR TITLE
LRAC-14551 Unable to create property name using symbol '%'

### PR DESCRIPTION
**Pull request by JLucasM**
LRAC-14551: [Jira Issue](https://liferay.atlassian.net/browse/LRAC-14551)

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by joshitagaki** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
Hey @JLucasM, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
