### PR TITLE
AC Test Fix - LRAC-13156 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-13156

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Thanks Josh for the fix! LGTM

**Review by ViniLopes20 — APPROVED** [review]
Good catch, thanks for fixing it. LGTM 🎉

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for working on it! :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
