### PR TITLE
AC Test fix LRAC-13100 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-13100
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2224041660)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Thank you Josh for the fix. LGTM

**Review by manuferreira — APPROVED** [review]
LGTM! Thank you. :tada:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
