### PR TITLE
AC Test Fix - LRAC-11758 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11758

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Thank you very much for this fix, Josh. LGTM 🎉

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks Josh :tada:

**Review by calvinctvo — APPROVED** [review]
Thanks for the fix @joshitagaki ! LGTM

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
