### PR TITLE
AC Test Fix - LRAC-13043 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-13043
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2216242019&testrayRunId=2216242022)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good fix, Josh. LGTM and thanks for working on it 🎉

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you! :tada:

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
