### PR TITLE
LRAC-14117 The icon representing the static and dynamic segments are dark in the Associated Segments card in the details of a known individual

### PR DESCRIPTION
**Pull request by JLucasM**
LRAC- 14117: [Jira Issue](https://liferay.atlassian.net/jira/software/c/projects/LRAC/boards/595?modal=detail&selectedIssue=LRAC-14117)

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @JLucasM

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by ViniLopes20** [comment]
Hey @JLucasM, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by fmarcio** [comment]
ci:forward:force

**Comment by ViniLopes20** [comment]
ci:forward:force

**Pull request closed without merging**
