### PR TITLE
AC Automated Test - LRAC-11507 | master

### PR DESCRIPTION
**Pull request by manuferreira**
https://issues.liferay.com/browse/LRAC-11507 (automation ticket)
https://issues.liferay.com/browse/LRAC-11450 (bug ticket)

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Hey @manuferreira ! Great test! LGTM

**Review by ViniLopes20 — APPROVED** [review]
Very good test, LGTM Manu. Thanks! 🎉

**Review by joshitagaki — APPROVED** [review]
Nice! LGTM!

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
