### PR TITLE
LRAC-11900 [F] Implement Empty State display message

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://issues.liferay.com/browse/LRAC-11900

### CODE REVIEW

**Comment by interaminense** [comment]
ci:stop

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:sf

**Pull request closed without merging**
