### PR TITLE
AC Test fix - LRAC-11277 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11277 (Ticket)
[Testray](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1865384107)

Solutions:
The change was made to place an empty state message on the graph in case it has no data ([LRAC-11016](https://issues.liferay.com/browse/LRAC-11016)). We should stop validating the tooltip and validating only the message on the chart in case we don't have data in the workspace.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks Vini

**Review by calvinctvo — APPROVED** [review]
Thanks @ViniLopes20 for working on this, the code LGTM

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
