### PR TITLE
LRAC-14612 Publish an experiment as complete when status is winner or no winner

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue https://issues.liferay.com/browse/LRAC-14612

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
Hey @interaminense, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded after the `stable` is passing. Thanks!

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:test:stable

**Comment by riccardo-ferrari** [comment]
Forwarding as per commend https://github.com/liferay-ac/liferay-portal/pull/719#issuecomment-1730270848

**Comment by riccardo-ferrari** [comment]
ci:forward:force

**Pull request closed without merging**
