### PR TITLE
AC Test Fix - LRAC-11448 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRAC-11448 (Test fix ticket)
Since this test checks for 1 banner after time zone change, I want to try keeping the same time zone (China), but using a different region (XinJiang), note that this will also changing the information banner since XinJiang timezone is different than Shanghai timezone. I've run this test on CI and it seems to stable the test.
[Testray Result 1](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1905872321)
[Testray Result 2](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1906045460)
[Testray Result 3](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1906736990)

### CODE REVIEW

**Review by joshitagaki — APPROVED** [review]
Hmm yea this is a weird one. Not sure why it passes after slightly changing the timezone. Hopefully it continues to pass now though lol. LGTM!

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by manuferreira — CHANGES_REQUESTED** [review]

**Review by ViniLopes20 — APPROVED** [review]
LGTM, Calvin. I hope the test keeps passing the CI hahahahaha. Thanks for this man. 🙏🏽

**Review by manuferreira — APPROVED** [review]
LGTM, thank you for working on this Calvin and nice fix :tada: I hope this time we can get rid of this one :rofl: :rofl:

**Review by christianstokes — APPROVED** [review]
Approved

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
