### PR TITLE
LRAC-13946 - The icon representing the static and dynamic segment is dark where it should be white

### PR DESCRIPTION
**Pull request by ilzamcmed**
Jira ticket: https://issues.liferay.com/browse/LRAC-13946

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM!

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by ilzamcmed** [comment]
ci:forward:force

**Comment by ilzamcmed** [comment]
ci:forward:force

**Pull request closed without merging**
