### PR TITLE
AC Automation Improvements - LRAC-13083 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-13083

Fixes issue: `com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//*[not(self::div)][contains(@class,'btn')][normalize-space()='Assign'][not(contains(@class,'navbar'))]"`

We classified this as a bug: https://liferay.atlassian.net/browse/LRAC-13481. There is no timeline on when this will get picked up to fix so creating a workaround in the meantime.

[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2421301017)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by nkkwon — APPROVED** [review]
LGTM! 👍 Thanks for the improvement for the macro

**Review by ViniLopes20 — COMMENTED** [review]
Hey @joshitagaki, I think this modification makes sense and would avoid the problem. But I don't know if it would be the right approach we should take (We may only be covering this bug for an indefinite period of time). I think that as the bug is also affecting MySQL now and causing problems for our tests, and tests from another team and could even occur in the environment of a client that uses MySQL.

So I think the right thing to do would be for us to mention Riccardo again in the ticket and in the thread that you opened in June so that he can correct this problem, as it is affecting us.

I think you could put a message to Riccardo and Marcellus on the ticket and on the [thread](https://liferay.slack.com/archives/GP37V21A6/p1686934414990319) to find out if the bug will be fixed or not and the effort to fix it. What do you think?

**Comment by joshitagaki** [comment]
> Hey @joshitagaki, I think this modification makes sense and would avoid the problem. But I don't know if it would be the right approach we should take (We may only be covering this bug for an indefinite period of time). I think that as the bug is also affecting MySQL now and causing problems for our tests, and tests from another team and could even occur in the environment of a client that uses MySQL.

So I think the right thing to do would be for us to mention Riccardo again in the ticket and in the thread that you opened in June so that he can correct this problem, as it is affecting us.

I think you could put a message to Riccardo and Marcellus on the ticket and on the [thread](https://liferay.slack.com/archives/GP37V21A6/p1686934414990319) to find out if the bug will be fixed or not and the effort to fix it. What do you think?

Good idea. I think it would be better to have this fixed, but probably won't get prioritized unless a customer has found this issue as well.

**Review by ViniLopes20 — APPROVED** [review]
Thanks for that Josh. We will continue with this alternative until the bug is fixed 👏🏽

**Review by nkkwon — APPROVED** [review]

**Review by manuferreira — APPROVED** [review]
Hey Josh. Thanks for that, let's hope the bug will be fixed soon :slightly_smiling_face:

**Comment by manuferreira** [comment]
ci:forward

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
