### PR TITLE
AC New Automated Test - LRAC-12199 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
[Automation ticket](https://issues.liferay.com/browse/LRAC-12199) 
[Bug Ticket](https://issues.liferay.com/browse/LRAC-12040) 
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2046501780&testrayRunId=2046548007)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Hey @joshitagaki ! Thanks for working on this! LGTM!

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you, Josh. :tada: :clap:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
