### PR TITLE
AC Test Fix - LRAC-14500 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14500#

### CODE REVIEW

**Review by ViniLopes20 — APPROVED** [review]
Thanks Josh, LGTM 🎉

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you!

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
