### PR TITLE
AC Automated Test - LRAC-11890 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11890 (Automation ticket)
https://issues.liferay.com/browse/LRAC-11665 (Story)
[Test Plan](https://docs.google.com/document/d/1lsYx9TBAgRxzkn4HZwe-NS6mtAvvY8WpXKmtqEDwUyo/edit#)
I didn't run it on CI because of the problems

**Note:**

- I isolated the test so that we don't need to implement a teardown to undo the change in server administration. If these steps were placed in the teardown we would have all the tests in the file performed unnecessary steps in the teardown.

- As we use the API to send the email report, so it is not necessary to enable the email report in the property, the email report is sent anyway by the API and will be received in the Mock Mock

- I will make documentation on confluence explaining how to run Mock Mock locally so we can all get this information and help with new similar tests or fixes

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by christianstokes — APPROVED** [review]
Looks awesome, thanks @ViniLopes20!

Approved

**Review by manuferreira — APPROVED** [review]
Thanks Vini, nice macro and test :tada: :male_detective:

**Comment by christianstokes** [comment]
Let's go for it!

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
