### PR TITLE
AC New Automation - LRAC-14648 and LRAC-14649 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14648
https://liferay.atlassian.net/browse/LRAC-14649

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
Hey, thanks for working on it! :muscle:

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
