### PR TITLE
LPD-33305 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-33305

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud

**Review by ViniLopes20 — APPROVED** [review]
LGTM @marcosapmf 🎉

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
