### PR TITLE
LRAC-13968 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-13968

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/144670

**Pull request closed without merging**
