### PR TITLE
AC Test Fix - LRAC-14788 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14788

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you! :detective:

**Review by nkkwon — APPROVED** [review]
LGTM!

**Review by joshitagaki — APPROVED** [review]
Thanks for updating this! LGTM

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
