### PR TITLE
[F] Create unit tests for Wizard Group Pages

### PR DESCRIPTION
**Pull request by JLucasM**
https://issues.liferay.com/browse/LRAC-12673

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by fmarcio — CHANGES_REQUESTED** [review]
Hey @JLucasM do you really need my commits on your PR? There are some tests on my commits that needs changes and I'm still working on it. So when we forward this PR we're going to have conflicts. If you don't need them, please rebase it with master and update it. Thanks!

**Review by interaminense — CHANGES_REQUESTED** [review]
Hey @JLucasM, it's missing the JIRA ID in your commits

**Comment by JLucasM** [comment]
Resent to: https://github.com/liferay-ac/liferay-portal/pull/239

**Pull request closed without merging**
