### PR TITLE
LPD-20478 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://liferay.atlassian.net/browse/LPD-20478

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
Will conflict with https://github.com/liferay-ac/liferay-portal/pull/1250. updating to merge the 2 PRs

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:forward:force

**Comment by marcosapmf** [comment]
merged in https://github.com/liferay-ac/liferay-portal/pull/1269

**Pull request closed without merging**
