### PR TITLE
LRACs-11906, 12196, 12264 - Property, People and Attributes step

### PR DESCRIPTION
**Pull request by fmarcio**

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:sf

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:stable

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:stop

**Comment by interaminense** [comment]
Resent https://github.com/liferay-ac/liferay-portal/pull/164

**Pull request closed without merging**
