### PR TITLE
AC Test Improvement - LRAC-13739 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-13739

**What will change with these modifications?**

- PRs that are pushed to Asah's 4.0.x branch will now run acceptance tests correctly with the most current tag of Faro

- The Testray release routine will run the tests using the most current version of Asah and Faro equal to UAT (Change made in Jenkins settings as well)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
Thanks for making these changes! Shouldn't we also change the other instances as well?
https://github.com/liferay-ac/liferay-portal/blob/7494aebff917f7ba8a5fbc5c076654062a844077/test.properties#L1221
https://github.com/liferay-ac/liferay-portal/blob/7494aebff917f7ba8a5fbc5c076654062a844077/test.properties#L3210-L3211
https://github.com/liferay-ac/liferay-portal/blob/7494aebff917f7ba8a5fbc5c076654062a844077/test.properties#L3231-L3232
https://github.com/liferay-ac/liferay-portal/blob/7494aebff917f7ba8a5fbc5c076654062a844077/test.properties#L4307-L4308

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks a lot! :muscle: :male_detective:

**Comment by ViniLopes20** [comment]
https://github.com/liferay-ac/liferay-portal/blob/7494aebff917f7ba8a5fbc5c076654062a844077/test.properties#L1221

Answer: I think this one we can remove this one as we won't have more PRs being submitted for 3.1.x since it's an old branch. thanks for observing this

https://github.com/liferay-ac/liferay-portal/blob/7494aebff917f7ba8a5fbc5c076654062a844077/test.properties#L3210-L3211

and 

https://github.com/liferay-ac/liferay-portal/blob/7494aebff917f7ba8a5fbc5c076654062a844077/test.properties#L3231-L3232

and

https://github.com/liferay-ac/liferay-portal/blob/7494aebff917f7ba8a5fbc5c076654062a844077/test.properties#L4307-L4308

Answer: I don't think we should change these rules now as these changes could affect the DXP teams if they run the acceptance suite or the full AC suite or directly affect the Echo team. We know that the 4.0.x branch is something that is stable for our release, but I think we should only update this to other teams after everything is working properly in production (This does not affect our upstream routine or release routine on the Testray that follows Jenkis settings)

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks!

**Review by nkkwon — APPROVED** [review]
LGMT! :+1: Thank you for working on it!

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward:force

**Pull request closed without merging**
