### PR TITLE
LRAC-12268 - [F] Add Compose Table and sync api calls

### PR DESCRIPTION
**Pull request by ilzamcmed**
https://issues.liferay.com/browse/LRAC-12268

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @ilzamcmed

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
