### PR TITLE
LRAC-13375 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**
Jira Issue: https://issues.liferay.com/browse/LRAC-13375

### CODE REVIEW

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:sf

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
