### PR TITLE
LRAC-15392 | Master

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issues: https://liferay.atlassian.net/browse/LRAC-14664

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @interaminense, I noticed in the test results that the problem was that the time filter was not changed. The tests try to change to the Last 24 hours to check the data, but I see in the screenshot that the Last 30 days time filter is still being used. Could you check if the time filter is being changed normally?

**Cases:**
- Try changing to a time filter different than the default and check if it is possible
- Try changing a time filter different than the default and then reload the page and check if the time filter option is maintained

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
