### PR TITLE
LPD-40264 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Review by marcosapmf — APPROVED** [review]

**Comment by marcellustavares** [comment]
ci:forward

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by marcellustavares** [comment]
@rachaelkoestartyo, it looks like there are failures unique to this pull. Please check https://github.com/brianchandotcom/liferay-portal/pull/155694

**Pull request closed without merging**
