### PR TITLE
[HOLD] LRAC-13772 Adjust "Free Trial" button

### PR DESCRIPTION
**Pull request by JLucasM**
LRAC-13772: [Jira Issue](https://issues.liferay.com/browse/LRAC-13772)

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by ilzamcmed — APPROVED** [review]
LGTM! :rocket:

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
