### PR TITLE
AC Automated Tests - LRAC-12811 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-12694 (Bug)
https://issues.liferay.com/browse/LRAC-12811 (Test Fix)
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2234190991&testrayRunId=2234191035)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Thanks Vini for the test! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks my friend :man_dancing:

**Comment by manuferreira** [comment]
ci:forward

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
