### PR TITLE
AC New Automated Test - LRAC-11634 | master

### PR DESCRIPTION
**Pull request by manuferreira**
https://issues.liferay.com/browse/LRAC-11634 (automation ticket)
https://issues.liferay.com/browse/LRAC-11460 (bug ticket)
[Testray run](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1981078911&testrayRunId=1981089412)

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks for this job, manu 🎉

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks @manuferreira

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
