### PR TITLE
AC Test Fix LRAC-13091 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-13091

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Good catch, Josh. LGTM 🎉

**Review by calvinctvo — APPROVED** [review]
Thanks for the fix @joshitagaki ! LGTM

**Review by manuferreira — APPROVED** [review]
Thanks Josh, congratulations on seeing this detail! :tada:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
