### PR TITLE
AC Test fix - LRAC-12423 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-12423
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2071566102&testrayRunId=2071624715)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Thanks @joshitagaki for the fix! LGTM

**Review by ViniLopes20 — APPROVED** [review]
Good catch, Josh. Thanks for fixing this. LGTM! 🎉

**Review by ViniLopes20 — APPROVED** [review]
Good catch, Josh. Thanks for fixing this. LGTM! 🎉

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
