### PR TITLE
AC Test Fix - LRAC-14824 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14824

**Problem:**
After the Clay migration, the segment criteria customization buttons are no longer `Select` elements and are now `Button` elements. So we need to modify all the buttons so they don't use the `Select` function.

**Solution:**
To correct this, you need to click on the button and then click on the option that appears in the dropdown.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks for working on this! LGTM!

**Review by nkkwon — APPROVED** [review]
LGTM! :+1:

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for the update :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
