### PR TITLE
LPD-19856 | master

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LPD-19856

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by fmarcio** [comment]
@interaminense I talked to @rachaelkoestartyo yesterday and she will include my commits on her PR

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
merged into https://github.com/liferay-ac/liferay-portal/pull/1351

**Pull request closed without merging**
