### PR TITLE
AC Test fix - LRAC-14038 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-14038

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks for working on it :muscle: :detective:

**Review by ViniLopes20 — APPROVED** [review]
Good catch, Josh. Thanks for it 🎉 🕵🏽‍♂️

**Review by nkkwon — APPROVED** [review]
LGTM 👍

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
