### PR TITLE
[F] LRAC-14257 create unit tests

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LRAC-14257

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by manuferreira** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:test:relevant

**Pull request closed without merging**
