### PR TITLE
LPD-25384 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:forward

**Comment by lesliewong92** [comment]
Backport for 4.7.x https://github.com/liferay-ac/liferay-portal/pull/1527

**Pull request closed without merging**
