### PR TITLE
AC Test Fix - LRAC-11898 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11898
normalize-space is unable to find text for certain xpaths that have multiple separate texts within the same node `(e.g. <div class="no-results-description">Create a segment to get started.<a class="d-block" href="https://learn.liferay.com/analytics-cloud/latest/en/people/segments/segments.html" target="_blank">Access our documentation to learn more.</a></div>)`

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
Hey, @joshitagaki nice solution :tada: :male_detective: . But I'm just curious, what's the difference when you add `text()` inside the normalize-space?

**Comment by joshitagaki** [comment]
> Hey, @joshitagaki nice solution tada male_detective . But I'm just curious, what's the difference when you add `text()` inside the normalize-space?

So from what I've been reading it's that normalize-space by itself will read all of a nodes text within it. While using text within normalize-space will only read the specific text node. `<div class="no-results-description">Create a segment to get started.<a class="d-block" href="https://learn.liferay.com/analytics-cloud/latest/en/people/segments/segments.html" target="_blank">Access our documentation to learn more.</a></div>` From the example when using `normalize-space()='Create a segment to get started.' `the test would fail since you need to also add the following text with it `normalize-space()='Create a segment to get started.Access our documentation to learn more.`

**Review by christianstokes — APPROVED** [review]
Looks great, thank you!

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
