### PR TITLE
AC Test fix - LRAC-11759 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11759
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1952198041)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Thanks for fixing this @joshitagaki ! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks, Josh :tada:

**Review by ViniLopes20 — APPROVED** [review]
LGTM. Thanks, Josh 🎉

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
