### PR TITLE
LPD-34046 | Test Fix

### PR DESCRIPTION
**Pull request by rafaellajordao**
**Jira Ticket:** [LPD-34046](https://liferay.atlassian.net/browse/LPD-34046)

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM @rafaellajordao

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:forward

**Pull request closed without merging**
