### PR TITLE
LRAC-14593 Reactivate unit tests and add new ones

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue https://issues.liferay.com/browse/LRAC-14593

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:test:stable

**Comment by riccardo-ferrari** [comment]
hey @interaminense,

Please verify https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356793/testReport/.opt.dev.projects.github.liferay-portal.modules.dxp.apps.segments.segments-experiment-web.test.js/components/

Thanks

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward:force

**Comment by interaminense** [comment]
ci:forward:force

**Comment by riccardo-ferrari** [comment]
ci:forward

**Pull request closed without merging**
