### PR TITLE
LPD-34185 Allow individual activities count to be nullable | master

### PR DESCRIPTION
**Pull request by lesliewong92**
https://liferay.atlassian.net/browse/LPD-34185

### CODE REVIEW

**Comment by lesliewong92** [comment]
Backports:
4.8.x - https://github.com/liferay-ac/liferay-portal/pull/1767
4.9.x - https://github.com/liferay-ac/liferay-portal/pull/1769

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward

**Pull request closed without merging**
