### PR TITLE
Disable test from upstream and release routine - LRAC-11408 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRAC-11408 (Ticket)
Note: Disabling this test since Segments does not show any custom events, hence this test is irrelevant and can be disregard.

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
> Hey @calvinctvo thanks for looking into this. If the test is irreverent, do you think we can just delete the test instead? Is there ever a scenario where we need it?

Hey @christianstokes , I don't see any scenario that need this test so I think we can delete this test.

**Comment by ViniLopes20** [comment]
Hey @calvinctvo, this test check a functionality that doesn't yet exist in AC. We have a story to be developed that will allow the user to use the custom event as a criterion for the segment. So I think we could disable the test like you thought we do and we'll have this automation ready when the new functionality works. What do you think?

cc: @christianstokes

**Comment by christianstokes** [comment]
Ok that sounds good to me @ViniLopes20 and @calvinctvo

**Review by ViniLopes20 — APPROVED** [review]
LGTM,  thanks Calvin

**Review by manuferreira — APPROVED** [review]
LGTM, Thanks Calvin :)

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
