### PR TITLE
LRAC-15173 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:stable

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
Hey @rachaelkoestartyo, the failure of `acceptance` is related to this [bug](https://liferay.atlassian.net/browse/LRAC-15298). The PR looks good to be forwarded after the stable is passing. Thanks!

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by rachaelkoestartyo** [comment]
hi @interaminense  can you review https://github.com/liferay-ac/liferay-portal/pull/953/commits/8592d40258d9f47a766b49491af3e71a0c24c092 ? Thanks!

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
