### PR TITLE
LPD-6540 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LPD-6540

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
I made some changes on it.

**Comment by interaminense** [comment]
Resend https://github.com/liferay-ac/liferay-portal/pull/1276

**Pull request closed without merging**
