### PR TITLE
AC Test Fix LRAC-14266 and LRAC-14267 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14266
https://liferay.atlassian.net/browse/LRAC-14267

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
Thanks for looking into that! LGTM. :tada:

**Review by nkkwon — APPROVED** [review]
LGTM! :+1: Thanks for working on this!

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
