### PR TITLE
LPD-19862 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LPD-19862

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ivicac** [comment]
Resent https://github.com/liferay-ac/liferay-portal/pull/1379

**Pull request closed without merging**
