### PR TITLE
LPS-199883 Remove metal storage

### PR DESCRIPTION
**Pull request by p2kmgcl**
This PR removes metal-storage from `osb-faro-web`. The API is almost the same than using `localStorage` directly.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @p2kmgcl, the failure of `acceptance` is not related to your modifications. The PR looks good to be forwarded after the `stable` and `relevant` are passing. Thanks!

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @p2kmgcl

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
