### PR TITLE
LPD-35281 | master

### PR DESCRIPTION
**Pull request by fmarcio**
https://liferay.atlassian.net/browse/LPD-35281

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:test:analytics-cloud-acceptance

**Comment by rafaellajordao** [comment]
> ### ✔️ ci:test:stable - 27 out of 27 jobs passed
> ### ❌ ci:test:relevant - 32 out of 34 jobs passed in 1 hour 36 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [0f91bd03c7ba1d4051fe03816c48f009924370cc](https://github.com/liferay/liferay-portal/commit/0f91bd03c7ba1d4051fe03816c48f009924370cc)
> 
> #### Upstream Comparison:
> Branch GIT ID: [5cd9d2157f6cb3cd262bde03e8f17395bcf943b9](https://github.com/liferay/liferay-portal/commit/5cd9d2157f6cb3cd262bde03e8f17395bcf943b9)Jenkins Build URL: [EE Development Acceptance (master) - 793 - 2024-09-01[16:37:47]](https://testray.liferay.com/#/project/34754/routines/174485/build/77630452)
> 
> **ci:test:stable - 27 out of 27 jobs PASSED**
> **ci:test:relevant - 32 out of 34 jobs PASSED**
> ##### For more details click [here](https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4879/jenkins-report.html).
> #### Failures unique to this pull:
> 1. [playwright-js-tomcat90-mysql57-jdk8/1/0](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1079209//consoleText) - [Playwright Report](https://testray.liferay.com/reports/production/logs/2024-09/test-1-32/test-portal-acceptance-pullrequest(master)/4879/playwright-js-tomcat90-mysql57-jdk8/1/0/playwright-report/index.html)1. [osb-faro-web/segment.spec.ts](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1079209/testReport/osb-faro-web_segment.spec/ts)1. [Add segment using an individual property "user group"](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1079209//testReport/osb-faro-web_segment.spec/ts/Add_segment_using_an_individual_property__user_group_)2. [Add segment using an organization property "organization"](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1079209//testReport/osb-faro-web_segment.spec/ts/Add_segment_using_an_organization_property__organization_)
> 
> #### For upstream results, click [here](https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)).

Hi @fmarcio ,
After analyzing the faults in the relevant suite of this pr and realizing that the faults have no relation to your changes! :tada:

**Comment by fmarcio** [comment]
ci:forward:force

**Pull request closed without merging**
