### PR TITLE
LRAC-15299 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-15299

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @marcosapmf, the failure of `acceptance` is related to this [bug](https://liferay.atlassian.net/browse/LRAC-15298). The PR looks good to be forwarded. Thanks!

**Comment by ViniLopes20** [comment]
ci:forward:force

**Pull request closed without merging**
