### PR TITLE
[ON HOLD] LPD-22318 | Master

### PR DESCRIPTION
**Pull request by interaminense**
https://issues.liferay.com/browse/LPD-22318

[ON HOLD] To do:

- [x] Remove cookie manage on top_head.jsp to be adapted to the AC SDK 1.1.9 version
- [x] Delete code about "remove cache on Server Administration"
- [x] Fix playwright tests after that

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
[ON HOLD] To do:
1. Remove cookie manage on top_head.jsp to be adapted to the AC SDK 1.1.9 version
2. Delete code about "remove cache on Server Administration"
3. Fix playwright tests after that

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
