### PR TITLE
LRAC-14056 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-14056

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @marcosapmf, one test is failing your `relevant` but checking the history and they always fail for other PRs too. It should not be related to your modifications. I would say you could follow the PR

Test:

- [PortalLogAssertorTest-functional-smoke-tomcat90-oracle193-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2354651326/history?tab=result&hideFilterPin=true)

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
