### PR TITLE
LRAC-14058

### PR DESCRIPTION
**Pull request by riccardo-ferrari**

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Review by marcosapmf — APPROVED** [review]

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @riccardo-ferrari, two tests are failing your `relevant` but checking the history of both and they always fail for other PRs too. It should not be related to your modifications. I would say you could follow the PR

Test:

- [PortalLogAssertorTest-functional-smoke-wildfly180-mariadb104-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2354414578/history?tab=result&hideFilterPin=true)
- [PortalLogAssertorTest-modules-integration-mysql57-jdk8/0/1](https://testray.liferay.com/home/-/testray/case_results/2354414723/history?tab=result&hideFilterPin=true)

**Comment by marcosapmf** [comment]
ci:forward:force

**Comment by marcosapmf** [comment]
Hey @riccardo-ferrari can you please check the issue with the SF?

**Comment by ViniLopes20** [comment]
SF issue: https://liferay.slack.com/archives/C1SJ64S9X/p1687184246725049

**Comment by riccardo-ferrari** [comment]
Thank you guys, i guess nothing to do on my end.

**Comment by riccardo-ferrari** [comment]
ci:forward:force

**Pull request closed without merging**
