### PR TITLE
AC Automated Test - LRAC-12347 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
Automation ticket - https://issues.liferay.com/browse/LRAC-12347
[Test Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2087513086)

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good, Calvin. Thank you for that. LGTM 🎉

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks Calvin!! :tada: :muscle:

**Review by joshitagaki — APPROVED** [review]
Very nice. Thanks Calvin! LGTM

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
