### PR TITLE
LPD-19862 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LPD-19862

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud-acceptance

**Review by marcellustavares — APPROVED** [review]

**Comment by marcellustavares** [comment]
@marcosapmf, I think the semantic version test is a real failure.

**Review by ivicac — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
forwarded to https://github.com/brianchandotcom/liferay-portal/pull/148880

**Pull request closed without merging**
