### PR TITLE
LPD-43809 | Test Fix | Poshi >>> Playwright

### PR DESCRIPTION
**Pull request by rafaellajordao**
### Motivation:
Test failing due to Poshi limitations.

### Proposed Solution:
Transcribe test to playwright in order to facilitate maintenance.

**More details:** [LPD-43809](https://liferay.atlassian.net/browse/LPD-43809)

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @rafaellajordao

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
