### PR TITLE
AC Test fix - LRAC-14277 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14277

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
> LGTM. Thanks for working on this! Hey Josh, quick question: do you why the other way does not work anymore?

I don't think it has worked this way previously. All other instances of running curl has been using this with the url first

**Review by nkkwon — APPROVED** [review]
LGTM! Thanks for fixing this!

**Comment by joshitagaki** [comment]
ci:forward

**Comment by joshitagaki** [comment]
ci:forward

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
