### PR TITLE
LRAC-11874 [F] Implement Workspace connection step / LRAC-11909 - [F] Implement Sidebar after connection is done

### PR DESCRIPTION
**Pull request by interaminense**
https://issues.liferay.com/browse/LRAC-11899

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud:nocompile

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by christianstokes** [comment]
Hey guys, what is this PR for? @interaminense @ViniLopes20

**Comment by ViniLopes20** [comment]
> Hey guys, what is this PR for? @interaminense @ViniLopes20

Hey @christianstokes, this PR is from the commerce connection modal stories. Front-end team needs to send PR to `liferay-portal` and they are sent to our user queue to keep AC PR here.

In the future when Faro is placed inside the `liferay-portal`, so they will start sending the PR to the `liferay-portal` only, should they share this user with us or should they create one just for them? I know that some teams in Brazil divide the user between QA and Dev or do you think each one is better?

**Comment by interaminense** [comment]
ci:reevaluate:1387401_3910

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
