### PR TITLE
LRACs-15084-15086-15087 Dynamic test (multi armed bandit)

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
Resent directly to Brian https://github.com/brianchandotcom/liferay-portal/pull/144998

**Pull request closed without merging**
