### PR TITLE
AC Enable Test - LRAC-11466 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
Bug: https://issues.liferay.com/browse/LRAC-11466

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks @ViniLopes20! LGTM! Was this the only test we need to enable?

**Comment by ViniLopes20** [comment]
> Thanks @ViniLopes20! LGTM! Was this the only test we need to enable?

Yes @joshitagaki, I checked all the tests affected by the bug and only this one was ignored

**Review by calvinctvo — APPROVED** [review]
Thanks @ViniLopes20 ! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks Vini :tada:

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
