### PR TITLE
LPD-28871 | Master

### PR DESCRIPTION
**Pull request by interaminense**
Each Analytics.track event fired after page load must wait for the window.Analytics instance to load to fire the event. So I'm adding a `window.onload` to do that.

### CODE REVIEW

**Comment by interaminense** [comment]
@marcosapmf can you review it?

**Comment by interaminense** [comment]
ci:test:sf

**Review by marcosapmf — APPROVED** [review]

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Pull request closed without merging**
