### PR TITLE
AC Automated Test - LRAC-12357 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-12357 (Automation ticket)
https://issues.liferay.com/browse/LRAC-11636 (Bug)
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2082590499&testrayRunId=2082642019)

**Changes:**

- ACUtils.macro:
This change allows us to create more than one WC for the same page, before we didn't inform the position we wanted to configure the WC, so it always replaced the first one on the page

- ACEventAnalysis.macro:
This macro takes the value that appears for the columns of each breakdown, but you need to pass the position that needs the value to be taken

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM!

**Review by calvinctvo — APPROVED** [review]
Hey @ViniLopes20 ! Nice change for the macro! LGTM!

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for the automation and the macro! :tada: :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
