### PR TITLE
LRAC-15180 | master | follow-up

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @marcellustavares, the failure of `acceptance` is related to this [bug](https://liferay.atlassian.net/browse/LRAC-15298). The PR looks good to be forwarded. Thanks!

**Comment by marcellustavares** [comment]
ci:test:sf

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:forward:force

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
