### PR TITLE
LRAC-14780 | master

### PR DESCRIPTION
**Pull request by marcellustavares**
@riccardo-ferrari, please see my comments at https://github.com/liferay-ac/liferay-portal/pull/770#issuecomment-1783627219

Thanks

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:forward

**Comment by marcellustavares** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
Hey @marcellustavares, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded after the `stable` and `acceptance` are passing. Thanks!

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
rebased and resent to https://github.com/liferay-ac/liferay-portal/pull/779

**Pull request closed without merging**
