### PR TITLE
AC Test Fix LRAC-14318 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14318

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good, Josh. Thank you for updating this xpath. LGTM 🎉

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for this update! :tada:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
