### PR TITLE
AC Test Fix/Disable Test - LRAC-11607 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11607

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by christianstokes — APPROVED** [review]
Goodbye for now Salesforce. We will miss you. Until your return 🖖👋

**Comment by christianstokes** [comment]
@ViniLopes20 I think if you can clean up the commit list, you can go ahead and forward it. Thanks for working on this :)

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
