### PR TITLE
LRAC-15304 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-15304

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:stable

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @marcosapmf

**Comment by interaminense** [comment]
ci:forward:force

**Comment by interaminense** [comment]
ci:reopen

**Pull request closed without merging**
