### PR TITLE
LRAC-12833 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-12833

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:stop

**Comment by ViniLopes20** [comment]
Hey @marcosapmf, could you check this problem?

`* What went wrong:
     [exec] Execution failed for task ':apps:analytics:analytics-settings-web:packageRunTest'.
     [exec] > Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1`

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @marcosapmf, are these problems related to your modifications?

- Issues related to `apps:analytics:analytics-settings-web:packageRunTest`
- Issues related to REST builder:
`Detected build REST changes. See above build REST log for more
     [echo] information. Make sure to commit in all build REST results.
      [get] Getting: \$\{dependencies.url\}/archive/test-1-31/test-portal-acceptance-pullrequest-downstream(master)/403159consoleText`

**Comment by JLucasM** [comment]
Resent to: https://github.com/liferay-ac/liferay-portal/pull/289

**Pull request closed without merging**
