### PR TITLE
AC Test Fix - LRAC-14514 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14514

`ACSegments.selectOperator` macro will work after this [PR](https://github.com/liferay-ac/liferay-portal/pull/703)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Nice! Thanks Vini LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for working on it!! :detective:

**Review by nkkwon — APPROVED** [review]
Thanks for the fix! 👍

**Comment by nkkwon** [comment]
ci:forward

**Pull request closed without merging**
