### PR TITLE
LPD-34127 | master

### PR DESCRIPTION
**Pull request by fmarcio**
Jira ticket https://liferay.atlassian.net/browse/LPD-34127

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:analytics-cloud-acceptance

**Comment by fmarcio** [comment]
ci:test:analytics-cloud-acceptance

**Comment by fmarcio** [comment]
ci:test:analytics-cloud-acceptance

**Review by interaminense — CHANGES_REQUESTED** [review]
Hey @fmarcio, It's weird. As I said, you only must pass `externalLink` to the ClayLink component.

**Comment by fmarcio** [comment]
> Hey @fmarcio, It's weird. As I said, you only must pass `externalLink` to the ClayLink component.

If I pass `externalLink` compiler will throw an type error ocurring in native typescript interface (not in the interface declared by us). This solution is based on ClayUI link documentation (please see `With Context`) topic
https://clayui.com/docs/components/link.html#

**Comment by interaminense** [comment]
> > Hey @fmarcio, It's weird. As I said, you only must pass `externalLink` to the ClayLink component.
> 
> If I pass `externalLink` compiler will throw an type error ocurring in native typescript interface (not in the interface declared by us). This solution is based on ClayUI Link component documentation (please see `With Context`) topic https://clayui.com/docs/components/link.html#

We are already doing that here https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/App.tsx#L140-L165

Please, follow this pattern https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/assets/components/AssetAppearsOnCard.tsx#L252-L260

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by interaminense** [comment]
ci:forward

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
