### PR TITLE
LRAC-12470 [resend] set min length when creating a new property

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://issues.liferay.com/browse/LRAC-12470

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Review by ilzamcmed — APPROVED** [review]
LGTM! :rocket:

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/190

**Pull request closed without merging**
