### PR TITLE
LPD-19855 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://liferay.atlassian.net/browse/LPD-19855

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Review by marcosapmf — APPROVED** [review]

**Comment by rachaelkoestartyo** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
Hey @rachaelkoestartyo, the acceptance routine is not working because of this [bug](https://liferay.atlassian.net/browse/LPD-21738)

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/1356

**Pull request closed without merging**
