### PR TITLE
LRAC-12806 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:reevaluate:1267401_7190

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:reevaluate:1287401_5606

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @rachaelkoestartyo, some tests are always failing for your PR. Could you [run these unit tests locally](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2171816992&testrayRunId=2171817100) to verify it's passing?

**Comment by rachaelkoestartyo** [comment]
@ViniLopes20 it's weird, those failures should be unrelated to my changes. i'm not sure how to run portal tests locally. do you know how or do you have the documentation somewhere?

**Comment by ViniLopes20** [comment]
> @ViniLopes20 it's weird, those failures should be unrelated to my changes. i'm not sure how to run portal tests locally. do you know how or do you have the documentation somewhere?

I don't know, but I believe @marcosapmf knows and can help you with this

**Comment by rachaelkoestartyo** [comment]
ci:reevaluate:1327401_7994

**Comment by joshitagaki** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
was able to run some of the failing tests locally, and they are all passing locally 🤔

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:reevaluate:1377401_8339

**Pull request closed without merging**
