### PR TITLE
LPD-5067 | Update AC-PRD services - fix search LCP.json

### PR DESCRIPTION
**Pull request by wagnersantana**
https://liferay.atlassian.net/browse/LPD-5067

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
@wagnersantana `ci:test:sf` failure

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by wagnersantana** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward

**Pull request closed without merging**
