### PR TITLE
[F] LRAC-13974 The link for active and inactive pages is different compared to UAT/Prod

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://issues.liferay.com/browse/LRAC-13974

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Review by ilzamcmed — APPROVED** [review]
LGTM! Thanks @fmarcio 
:rocket:

**Comment by fmarcio** [comment]
ci:test:stable

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by fmarcio** [comment]
ci:forward

**Pull request closed without merging**
