### PR TITLE
LPD-43512 | master

### PR DESCRIPTION
**Pull request by fmarcio**
Jira ticket https://liferay.atlassian.net/browse/LPD-43512

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward:force

**Comment by interaminense** [comment]
Resent directly to Brian https://github.com/brianchandotcom/liferay-portal/pull/156695

**Pull request closed without merging**
