### PR TITLE
LRAC-14553 osb-faro-docker: update Liferay Docker image version

### PR DESCRIPTION
**Pull request by sillascavalcanti**
### Issue
Error when trying to add a user to a property.The addUserGroup method from GroupdLocalService had its return type [updated](https://github.com/liferay/liferay-portal/commit/f38eec0d4b381bc276cb074d737a9447f8d24d09), giving us the following error `Caused by: java.lang.NoSuchMethodError: 'boolean com.liferay.portal.kernel.service.GroupLocalService.addUserGroup(long, long)'
	at com.liferay.osb.faro.service.impl.FaroChannelLocalServiceImpl.addUsers(FaroChannelLocalServiceImpl.java:107) ~[?:?]`

### Proposed solution
The Liferay Docker image was updated in the [Dockerfile](https://github.com/liferay-ac/liferay-portal/blob/master/modules/dxp/apps/osb/osb-faro/osb-faro-docker/local/Dockerfile) file in osb-faro, the update was from version [u78](https://customer.liferay.com/downloads/-/download/liferay-dxp-7-4-update-78-download) to [u90](https://customer.liferay.com/downloads/-/download/liferay-dxp-7-4-update-90-download) where the addUserGroup method was being found.

### CODE REVIEW

**Comment by sillascavalcanti** [comment]
ci:test:sf

**Comment by sillascavalcanti** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @sillascavalcanti, automated tests are not possible to be executed after this change. I looked at the [Faro container log](https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/8126/functional-tomcat90-mysql57-jdk8/0/0/docker-logs/faro.log) and noticed this error:

`java.lang.RuntimeException: Invalid host name osbfarofrontend
	at com.liferay.portal.servlet.filters.validhostname.ValidHostNameFilter.doFilterTry(ValidHostNameFilter.java:31) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.processDirectCallFilter(InvokerFilterChain.java:185) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:90) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:95) ~[portal-kernel.jar:?]
	at com.liferay.shielded.container.internal.proxy.FilterWrapper.doFilter(FilterWrapper.java:69) ~[com.liferay.shielded.container.impl.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[catalina.jar:9.0.75]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481) ~[catalina.jar:9.0.75]
	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:545) ~[catalina.jar:9.0.75]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130) [catalina.jar:9.0.75]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) [catalina.jar:9.0.75]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [catalina.jar:9.0.75]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.75]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390) [tomcat-coyote.jar:9.0.75]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) [tomcat-coyote.jar:9.0.75]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926) [tomcat-coyote.jar:9.0.75]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791) [tomcat-coyote.jar:9.0.75]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) [tomcat-coyote.jar:9.0.75]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) [tomcat-util.jar:9.0.75]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) [tomcat-util.jar:9.0.75]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.75]
	at java.lang.Thread.run(Thread.java:829) [?:?]`
	
When the tests are run in CI, they access the AC using `osbfarofrontend` in the URL, but for some reason, after your modifications, CI is unable to use `osbfarofrontend` as the host. You need to investigate this with @marcosapmf when he returns from vacation on Monday. If he doesn't know how to resolve this, then we can involve the CI team as well.

**Comment by sillascavalcanti** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @sillascavalcanti, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded after the `stable` is passing. Thanks!

**Comment by marcellustavares** [comment]
Related to https://github.com/liferay-ac/liferay-portal/pull/761/

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
@sillascavalcanti and @ViniLopes20, I'm putting this pr on hold until we finish the regression tests so we can use uat to test these changes there.
Thanks

**Comment by marcosapmf** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/765
Thanks @sillascavalcanti!

**Pull request closed without merging**
