### PR TITLE
LRAC-15379 | master

### PR DESCRIPTION
**Pull request by ivicac**

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @ivicac, I downloaded your PR and built the AC to try to check why the automation wasn't running here. I note that when we log in, the workspace list does not load and keeps refreshing forever. Could you check this?

[screen-capture (2).webm](https://github.com/liferay-ac/liferay-portal/assets/76956227/e002b78d-c0b1-41c8-997d-0dbddff31e3b)

**Comment by ivicac** [comment]
@ViniLopes20 This should be the current behavior on master. @marcosapmf said there is a communication issue between faro and asah.

**Comment by marcosapmf** [comment]
Hey @ivicac,
When you said you were using master, I thought you were using tomcat to start Faro. In this case, there is a communication issue. Using a Docker image should be good.

Sorry the misunderstanding :sweat_smile:

**Comment by ivicac** [comment]
@marcosapmf , actually I am building faro from master and using portal docker image from master(nightly build)

**Comment by ivicac** [comment]
not Docker image using released liferay portal docker image

**Comment by marcosapmf** [comment]
It does not look like to be a asah communication issue. The response is returning `Unauthorized` the logged user seems to be `default@liferay.com` when it should be `test@liferay.com`
image

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @ivicac and @marcosapmf, I don't know why CI didn't execute acceptance here, I'll investigate that. But I downloaded the PR and built the AC locally here and everything is working correctly. I believe we can forward this PR. Thank you

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
@ivicac can you please fix the source format issue?

Thanks :)

**Comment by marcosapmf** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/1101

**Pull request closed without merging**
