### PR TITLE
[F] LRAC-14761 fix pagination issue when there's at least 8 known individuals

### PR DESCRIPTION
**Pull request by fmarcio**
https://liferay.atlassian.net/browse/LRAC-14761

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by interaminense** [comment]
ci:forward

**Comment by fmarcio** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
