### PR TITLE
AC Test Fix - LRAC-11937 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11937

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Hey @joshitagaki ! Thanks for the fix! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you, Josh. :tada:

**Review by ViniLopes20 — APPROVED** [review]
Thanks for the fix, Josh. LGTM 🎉

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
