### PR TITLE
AC Test fix - LRAC-11638 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11638

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — COMMENTED** [review]
Hey @ViniLopes20 not related to your fix but there's a typo in line 304 `task ("Navigate to Individule Segments")` could you fix that too? :grin:

**Review by manuferreira — APPROVED** [review]
LGTM, thanks Vini :police_officer:

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks for fixing this!

**Review by christianstokes — APPROVED** [review]
Approved, thank you Vini!

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
