### PR TITLE
LRAC-14028 | master

### PR DESCRIPTION
**Pull request by marcellustavares**
@fmarcio could you please review this pull? Thanks

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Review by fmarcio — APPROVED** [review]
LGTM! thanks @marcellustavares :rocket:

**Comment by marcellustavares** [comment]
ci:forward

**Comment by marcellustavares** [comment]
looks good @fmarcio, I just ran locally. Thanks

**Comment by marcellustavares** [comment]
@fmarcio please send a follow up for the JS tests.

**Pull request closed without merging**
