### PR TITLE
LRAC-12806 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://liferay.atlassian.net/browse/LRAC-12806

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by rachaelkoestartyo** [comment]
@nkkwon thanks! i'll take a look

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by nkkwon** [comment]
[central-requirements-jdk8/0/0](https://testray.liferay.com/reports/production/logs/2023-08/test-1-37/test-portal-acceptance-pullrequest(master)/13526/central-requirements-jdk8/0/0/jenkins-console.txt.gz?authuser=0) - Looks like another check for `analytics-message-sender-api` module

```   [junit] Testcase: testScanBuildScripts(com.liferay.portal.modules.ModulesStructureTest):	FAILED
    [junit] Missing modules/apps/analytics/analytics-message-sender-api/build.gradle
    [junit] junit.framework.AssertionFailedError: Missing modules/apps/analytics/analytics-message-sender-api/build.gradle
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$2.preVisitDirectory(ModulesStructureTest.java:285)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest$2.preVisitDirectory(ModulesStructureTest.java:159)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2677)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.modules.ModulesStructureTest.testScanBuildScripts(ModulesStructureTest.java:157)
    [junit] 
    [junit] 
    [junit] Test com.liferay.portal.modules.ModulesStructureTest FAILED
```

[modules-compile-jdk8/0/6](https://testray.liferay.com/reports/production/logs/2023-08/test-1-37/test-portal-acceptance-pullrequest(master)/13526/modules-compile-jdk8/0/6/jenkins-console.txt.gz?authuser=0) - Could not resolve files for `osb-faro-provisioning-client`

```    [exec] FAILURE: Build completed with 4 failures.
     [exec] 
     [exec] 1: Task failed with an exception.
     [exec] -----------
     [exec] * What went wrong:
     [exec] Execution failed for task ':dxp:apps:osb:osb-faro:osb-faro-provisioning-client:compileJava'.
     [exec] > Could not resolve all files for configuration ':dxp:apps:osb:osb-faro:osb-faro-provisioning-client:compileClasspath'.
     [exec]    > Could not resolve com.liferay.osb.koroneiki:com.liferay.osb.koroneiki.client:1.0.0.
     [exec]      Required by:
     [exec]          project :dxp:apps:osb:osb-faro:osb-faro-provisioning-client
     [exec]       > Could not resolve com.liferay.osb.koroneiki:com.liferay.osb.koroneiki.client:1.0.0.
     [exec]          > Could not get resource 'https://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/osb/koroneiki/com.liferay.osb.koroneiki.client/1.0.0/com.liferay.osb.koroneiki.client-1.0.0.pom'.
     [exec]             > Could not GET 'https://repository-cdn.liferay.com/nexus/service/local/repo_groups/private/content/com/liferay/osb/koroneiki/com.liferay.osb.koroneiki.client/1.0.0/com.liferay.osb.koroneiki.client-1.0.0.pom'. Received status code 401 from server: Unauthorized
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dxp:apps:osb:osb-faro:osb-faro-provisioning-client:compileJava'.
     [exec] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
     [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)

**Comment by rachaelkoestartyo** [comment]
@nkkwon there's no other references to analytics-message-sender-api.. is it perhaps some test configurations?

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by rachaelkoestartyo** [comment]
ci:reevaluate:1257401_2330

**Comment by rachaelkoestartyo** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
Hey @nkkwon, Could you analyze the `relevant` failures to check whether tests that were already failing before the PR modifications or not?

**Comment by nkkwon** [comment]
I'll take a look!

**Comment by rachaelkoestartyo** [comment]
FYI we are still waiting for load testing (testing with millions of users) to finish before we can merge this. so probably we'll need to rebase and resend this later 😞

**Comment by ViniLopes20** [comment]
Hey @rachaelkoestartyo, we created this [SRE ticket](https://liferay.atlassian.net/browse/SRE-4194?atlOrigin=eyJpIjoiYThjNWRmYjlhOGI5NDc2YjkzN2I0NmIzMGFmM2MxNTIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ) to update our [LXC environment](https://analyticsqa.lxc.liferay.com/) with your branch to validate the sync batch in an LXC environment before approving this PR

**Comment by nkkwon** [comment]
It looks like all the `relevant` failures aren't related to this PR 👍

**Comment by marcellustavares** [comment]
@rachaelkoestartyo , could you please rebase?

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:stable

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/789

**Pull request closed without merging**
