### PR TITLE
LPD-32848 | master

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Review by riccardo-ferrari — APPROVED** [review]
Should we have all our exports in gzip? Including Commerce and Assets related exports?

**Comment by marcellustavares** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by riccardo-ferrari** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by riccardo-ferrari** [comment]
ci:forward

**Pull request closed without merging**
