### PR TITLE
LRAC-14112 Some AC buttons are not with the link style

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LRAC-14112

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @fmarcio

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
