### PR TITLE
AC Test Fix - LRAC-12433 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-12433
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2087229571&testrayRunId=2087286676)

Let me know what you think of this solution. It's reading the identity event twice for some reason so using partial assert should fix the issue.

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Thanks Josh, LGTM 🎉

**Review by manuferreira — APPROVED** [review]
Thanks, Josh. Nice fix! :tada:

**Review by calvinctvo — APPROVED** [review]
Thanks @joshitagaki ! LGTM

**Comment by calvinctvo** [comment]
Thanks guys for reviewing, I'm forwarding the PR

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
