### PR TITLE
AC New Automation Test - LRAC-12141 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
[Automation ticket](https://issues.liferay.com/browse/LRAC-12141)
[Story](https://issues.liferay.com/browse/LRAC-12058)
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2007085613)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
Testing expected value on CI: https://github.com/joshitagaki/liferay-portal/pull/90

**Review by manuferreira — APPROVED** [review]
LGTM. You did an amazing job creating these macros Josh, thank you :clap:

**Review by calvinctvo — APPROVED** [review]
hey @joshitagaki ! Thanks for explaining this to me yesterday. LGTM

**Comment by calvinctvo** [comment]
thanks for reviewing guy! I'm forwarding this PR

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
