### PR TITLE
LRAC-12601 Fix commerce channels total when toggle commerce sync

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://issues.liferay.com/browse/LRAC-12601

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Review by ilzamcmed — APPROVED** [review]
LGTM! :rocket:

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by ilzamcmed** [comment]
ci:forward

**Pull request closed without merging**
