### PR TITLE
AC Test Fix - LRAC-11761 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11761

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM. Thanks, Josh 🎉

**Review by christianstokes — APPROVED** [review]
Nice easy fix, approved!

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
