### PR TITLE
LRAC-13887 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-13887
Jira ticket: https://issues.liferay.com/browse/LRAC-13900

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/456

**Pull request closed without merging**
