### PR TITLE
LPD-15977 Download report cards not using the same date range

### PR DESCRIPTION
**Pull request by sillascavalcanti**
[Issue](https://liferay.atlassian.net/browse/LPD-15977)

### CODE REVIEW

**Comment by sillascavalcanti** [comment]
ci:test:sf

**Comment by sillascavalcanti** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @sillascavalcanti

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
