### PR TITLE
LPD-39329

### PR DESCRIPTION
**Pull request by ivicac**
https://liferay.atlassian.net/browse/LPD-39329

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by ivicac** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ivicac** [comment]
ci:test:stable

**Comment by ivicac** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
ci:forward

**Pull request closed without merging**
