### PR TITLE
LRAC-14322 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-14322

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:forward

**Comment by fmarcio** [comment]
SF is failing due to https://liferay.slack.com/archives/C1SJ64S9X/p1690492148909619

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/640

**Pull request closed without merging**
