### PR TITLE
AC Test fix - LRAC-12434 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-12434
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2086947146&testrayRunId=2086995494)

Another failure found for the groupid searchapi. https://issues.liferay.com/browse/LRAC-12454

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Thanks Josh, LGTM 🎉

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you, Josh. Nice finding :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
