### PR TITLE
LPD-20598 | master

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LPD-20598

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @fmarcio

**Comment by interaminense** [comment]
ci:test:stable

**Comment by fmarcio** [comment]
ci:stop

**Comment by interaminense** [comment]
ci:stop

**Comment by fmarcio** [comment]
ci:stop

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
