### PR TITLE
AC Remove tests from Quarantine - LRAC-12526 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRAC-12526
Removing these tests from quarantine as Total Individuals Card is enabled on UAT

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Thanks a lot for enabling these automations, Calvin. LGTM 🎉

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks, Calvin :tada: :muscle:

**Review by joshitagaki — APPROVED** [review]
Thanks for re-enabling these tests! LGTM

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
