### PR TITLE
LRAC-12602 | fix sorting on sites and channels tab

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Related to [LRAC-12602](https://issues.liferay.com/browse/LRAC-12602)

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:stop

**Comment by thiago-buarqque** [comment]
ci:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:reevaluate:1377401_7136

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Review by riccardo-ferrari — APPROVED** [review]
LGTM

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:stop

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
