### PR TITLE
[F] LRAC-15330 Set only authorized users to download all requests from the request log

### PR DESCRIPTION
**Pull request by fmarcio**
https://liferay.atlassian.net/browse/LRAC-15330

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by interaminense** [comment]
LGTM! Thanks @fmarcio

**Comment by interaminense** [comment]
ci:forward

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:forward

**Comment by fmarcio** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
Hey @fmarcio, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by ViniLopes20** [comment]
ci:forward:force

**Pull request closed without merging**
