### PR TITLE
AC Test Fix - LRAC-14550 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14550

### CODE REVIEW

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for working on it! :muscle:

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks Josh 🎉

**Review by nkkwon — APPROVED** [review]
LGTM! 👍 Thanks for the change

**Comment by nkkwon** [comment]
ci:forward

**Pull request closed without merging**
