### PR TITLE
LRAC-14630 - Add “Origin-” to X-Forwarded header names to avoid API gateway overriding them

### PR DESCRIPTION
**Pull request by ivicac**

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by ViniLopes20** [comment]
Hey @marcellustavares and @ivicac, I ran the acceptance tests twice here and I'm observing strange behavior after the modifications in this PR. After logging in, the AC page is loading for a long time to access the workspace list and is causing the tests to fail. Is this related to these modifications?

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
