### PR TITLE
AC Test Fix - LRAC-14549 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14549

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for taking some time to update this! :detective:

**Review by ViniLopes20 — APPROVED** [review]
Very good, Josh. Very boring correction to make. LGTM 🎉

**Review by nkkwon — APPROVED** [review]
Thank you for the fix!

**Comment by nkkwon** [comment]
ci:forward

**Pull request closed without merging**
