### PR TITLE
LRAC-13995 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**
Jira ticket: https://issues.liferay.com/browse/LRAC-13995

### CODE REVIEW

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/505

**Pull request closed without merging**
