### PR TITLE
LPD-41139 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-41139

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
@marcellustavares can you please double check if I didn't miss any module?
Thanks

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Review by marcellustavares — APPROVED** [review]

**Comment by marcellustavares** [comment]
ci:forward

**Pull request closed without merging**
