### PR TITLE
AC Automated Test/Quarantine - LRAC-12005 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-12005 (Automation ticket)
https://issues.liferay.com/browse/LRAC-11848 (Bug)

**PS:** Hey team, I decided to quarantine this test since custom field values take a long time in automation to appear in AC. So the test is not passing every time. I hope that after the migration of segments, maybe this part will be a little faster and we will be able to remove it from quarantine

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you! Good macros and paths :tada: :muscle:

**Review by calvinctvo — APPROVED** [review]
Thanks @ViniLopes20 for the new test and macro! LGTM

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks Vini

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
