### PR TITLE
AC Test Fix - LRAC-12301 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-12301
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2155928038&testrayRunId=2155929153)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, Josh. Thanks for working on it 🎉

**Review by ViniLopes20 — APPROVED** [review]
LGTM, Josh. Thanks for working on it 🎉

**Review by calvinctvo — APPROVED** [review]
Thanks for updating this test Josh! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks Josh :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
