### PR TITLE
AC Test fix - LRAC-13947 | master

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/LRAC-13947

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks for fixing this! LGTM!

**Review by ViniLopes20 — APPROVED** [review]
Very good, Nick. Thank you for working on it. LGTM 🎉

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks Nick!

**Comment by manuferreira** [comment]
ci:forward

**Comment by joshitagaki** [comment]
ci:forward

**Comment by joshitagaki** [comment]
ci:forward

**Comment by joshitagaki** [comment]
ci:forward

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
