### PR TITLE
AC Test Fix - LRAC-14521 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14521

### CODE REVIEW

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Review by ViniLopes20 — APPROVED** [review]
Thanks Josh, LGTM 🎉

**Review by manuferreira — APPROVED** [review]
Thank you, Josh! :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
