### PR TITLE
AC Remove from upstream run - LRAC-11282 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11282

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
thanks @joshitagaki , the code LGTM

**Review by manuferreira — APPROVED** [review]
LGTM, thanks Josh :tada:

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
