### PR TITLE
LRAC 13887

### PR DESCRIPTION
**Pull request by ivicac**
- LRAC-13887 use StringUtil.merge generates a different token than just concating the strings
- LRAC-13900 update Faro modules OSGI dependencies
- LRAC-13780 - Fix oauth token generation

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by manuferreira** [comment]
ci:stop

**Comment by marcosapmf** [comment]
ci:stop

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
