### PR TITLE
LRAC-14037 Help Center and Report an Issue is redirecting to the wrong page

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://issues.liferay.com/browse/LRAC-14037

### CODE REVIEW

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by ilzamcmed** [comment]
Hey @JLucasM and @interaminense 
When testing in the UI, I noticed that the link is only clickable on the text. On UAT, we can click the whole area.
Can one of you guys fix that?
Thanks!

**Comment by fmarcio** [comment]
> Hey @JLucasM and @interaminense When testing in the UI, I noticed that the link is only clickable on the text. On UAT, we can click the whole area. Can one of you guys fix that? Thanks!

Thx for the observation, @ilzamcmed! Maybe the fix for this is passing these classes `className='button-root btn btn-block btn-unstyled`. You guys can use this commit as an example: https://github.com/liferay-ac/liferay-portal/pull/527/commits/508af90130ae37bac586b2acb9169fdd2e6744ea

**Comment by ilzamcmed** [comment]
I tested on the previuos PR and this one has already fix the issue. :tada:

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by JLucasM — APPROVED** [review]
LGTM!

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
