### PR TITLE
LPD-39610 | Unit tests for LPD-37898

### PR DESCRIPTION
**Pull request by rafaellajordao**
This task consists of creating unit tests to cover the bug scenarios.

more details: [LPD-39610](https://liferay.atlassian.net/browse/LPD-39610)

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @rafaellajordao

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
