### PR TITLE
LRAC-13843 Fix unit tests on master

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://issues.liferay.com/browse/LRAC-13843

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Review by ilzamcmed — APPROVED** [review]
LGTM! :rocket:

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
