### PR TITLE
LRAC-13919 The fix pack download button in the connection modal is redirecting to the wrong page

### PR DESCRIPTION
**Pull request by interaminense**
Jira issue https://issues.liferay.com/browse/LRAC-13919

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
