### PR TITLE
LRAC-12647 - [F] Remove Channels and Sites tabs texts

### PR DESCRIPTION
**Pull request by ilzamcmed**
https://issues.liferay.com/browse/LRAC-12647

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:sf

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by ilzamcmed** [comment]
ci:forward

**Comment by ilzamcmed** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/127998

**Pull request closed without merging**
