### PR TITLE
LRAC-12590 - [BUG] When you sync by group/organization/account and then sync by all contacts and/or accounts and then deselect, the accounts/groups/organization that you synced before are not selected

### PR DESCRIPTION
**Pull request by ilzamcmed**
https://issues.liferay.com/browse/LRAC-12590

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM!

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
