### PR TITLE
LRAC-14795 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-14795

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:stable

**Review by marcellustavares — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:forward:force

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
