### PR TITLE
LPD-23023 | master

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LPD-23023

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by fmarcio** [comment]
ci:test:analytics-cloud-acceptance

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
