### PR TITLE
BACKPORT - LRAC-13933 | master

### PR DESCRIPTION
**Pull request by ilzamcmed**
Backport of  https://liferay.atlassian.net/browse/LRAC-13993

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
SF team is working on a fix
https://liferay.slack.com/archives/C1SJ64S9X/p1687151985725329

**Comment by ViniLopes20** [comment]
Hey @ilzamcmed, The `relevant` failing is not related to your modifications. I would say you could follow the PR after the `stable` and `SF` are passing

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
SF depends on https://liferay.slack.com/archives/C1SJ64S9X/p1687184246725049

**Review by fmarcio — APPROVED** [review]
Considering SF issue is not related to us, LGTM :rocket:

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:stable

**Comment by ilzamcmed** [comment]
ci:stop

**Comment by ilzamcmed** [comment]
ci:forward

**Pull request closed without merging**
