### PR TITLE
LRAC-13917 [BUG] The icon for copying the token is wrong in the connection modal and in the API page

### PR DESCRIPTION
**Pull request by JLucasM**
LRAC-13917: [Jira Issue](https://issues.liferay.com/browse/LRAC-13917)

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Review by ilzamcmed — APPROVED** [review]
LGTM!

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by JLucasM** [comment]
Resent to: https://github.com/liferay-ac/liferay-portal/pull/468

**Pull request closed without merging**
