### PR TITLE
LPD-21215 | master

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
si:test:stable

**Comment by marcellustavares** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:test:upgrade

**Comment by marcellustavares** [comment]
si:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Review by rachaelkoestartyo — APPROVED** [review]

**Comment by marcellustavares** [comment]
ci:stable

**Comment by marcellustavares** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/1378

**Pull request closed without merging**
