### PR TITLE
AC Remove Test - LRAC-12150 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-12150 (Automation ticket)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks for removing these tests

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks Vini

**Review by calvinctvo — APPROVED** [review]
Thanks for removing these test @ViniLopes20 ! LGTM

**Comment by calvinctvo** [comment]
Thanks for reviewing guys! I'm forwarding this.

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
