### PR TITLE
LPD-24471 | master

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
si:test:stable

**Comment by marcellustavares** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
@ViniLopes20, is this related to my pull?

**Comment by ViniLopes20** [comment]
Hey @marcellustavares, I don't think so, but as it only failed in this PR, I'll run it one more time just to get a double check

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @marcellustavares, I think it must be related to your PR. Could you try building the AC (creating the image locally and building the backend) to check if you find any errors? I see in the logs that he was waiting for Faro Demo Data to be ready and that is not happening

**Review by rachaelkoestartyo — APPROVED** [review]

**Comment by marcellustavares** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
@ViniLopes20 , where can you see that? I could not find anything meaningful in the logs.

**Comment by ViniLopes20** [comment]
Hey @marcellustavares, I am seeing [here](https://testray.liferay.com/reports/production/logs/2024-04/test-1-28/test-portal-acceptance-pullrequest(master)/9345/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

Search by: `Waiting for Faro demo data to be created.`

**Comment by ViniLopes20** [comment]
I downloaded your PR today and tried to build the AC, I observed that the Demo Property is not created, maybe this is the reason that the `Completed demo data creation` did not appear in the log

**Comment by lesliewong92** [comment]
Looking into demo data creation issue.

**Comment by marcellustavares** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/1478

**Pull request closed without merging**
