### PR TITLE
LPD-15933 Tooltip don't appear in audience card

### PR DESCRIPTION
**Pull request by sillascavalcanti**
[Issue](https://liferay.atlassian.net/browse/LPD-15933)

### CODE REVIEW

**Comment by sillascavalcanti** [comment]
ci:test:sf

**Comment by sillascavalcanti** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @sillascavalcanti, The acceptance failure is related to a problem in [one of the playwright tests](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2571618683&testrayRunId=2571621064). [I fix this today](https://liferay.atlassian.net/browse/LCD-38204), but it is not related with you modifications. Thanks!

**Review by fmarcio — APPROVED** [review]
LGTM! thanks @sillascavalcanti :rocket:

**Comment by interaminense** [comment]
Resent https://github.com/liferay-ac/liferay-portal/pull/1571

**Pull request closed without merging**
