### PR TITLE
AC Test Fix - LRAC-11542 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11542
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1916282280&testrayRunId=1916300525)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks for fixing this

**Review by calvinctvo — APPROVED** [review]
Hey @ViniLopes20 , LGTM!

**Review by christianstokes — APPROVED** [review]
Looks good, approved.

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
