### PR TITLE
AC Test Fix - LRAC-11545 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11545
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1916635345&testrayRunId=1916638808)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Thanks @ViniLopes20 for the fix, LGTM

**Review by christianstokes — APPROVED** [review]
Looks good. Approved.

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
