### PR TITLE
LPD-27167 Check if the segmentsExperienceId belongs to the actual page

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Please review this pull, I think the component is yours.

Previous pull: https://github.com/liferay-echo/liferay-portal/pull/15728

Regards.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
thanks @georgel-pop-lr, LGTM. Did you have a chance to test this with a real environment with AC connected?

If not, I will test it manually tomorrow. Thanks

**Comment by georgel-pop-lr** [comment]
> thanks @georgel-pop-lr, LGTM. Did you have a chance to test this with a real environment with AC connected?
> 
> If not, I will test it manually tomorrow. Thanks

Hi,

I could not test it, I forced the condition.

Regards.

**Review by marcellustavares — APPROVED** [review]

**Comment by marcellustavares** [comment]
ci:forward

**Pull request closed without merging**
