### PR TITLE
AC Test Fix - LRAC-12240 | master

### PR DESCRIPTION
**Pull request by manuferreira**
Hi, this test was in the wrong file.
https://issues.liferay.com/browse/LRAC-12240

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Thanks @manuferreira for the fix! LGTM!

**Review by joshitagaki — APPROVED** [review]
Thanks for moving this test! LGTM!

**Review by ViniLopes20 — APPROVED** [review]
Thanks a lot for it, Manu. LGTM! 🎉

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
