### PR TITLE
AC Test Fix - LRAC-14515 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14515

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! Changing to modifedDate LGTM

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks meu amigo :detective:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
