### PR TITLE
LRAC-13712 Follow up

### PR DESCRIPTION
**Pull request by interaminense**
https://issues.liferay.com/browse/LRAC-13712

### CODE REVIEW

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
Hey @interaminense, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
