### PR TITLE
AC Test fix - LRAC-11314 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRAC-11314 (Test fix ticket)
Note: Sometimes the banner does not show up until clicking on a different setting tabs. By adding another action (clicking on Usage) can help prevent the flakiness of this test.

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by manuferreira** [comment]
hey @calvinctvo, I don't think the banner gets stacked in this test case, even if you change the timezone a couple of times.
Have you tried like `change the timezone to japan > save > refresh the page > see the information banner` 
`change the timezone again > save > see the banner `(I was doing this case manually and apparently the test doesn't need a refresh when changing the timezone a second time). What do you think?

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
Hey @christianstokes , like @manuferreira said, the banner does not stack anymore, and refreshing the page does indeed open the modal, so I deleted both the refresh and close modal command. Here is the [test result ](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1891533133). I think this should stable the test

**Review by christianstokes — APPROVED** [review]
Looks good to me, thanks @calvinctvo!

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
