### PR TITLE
AC Disable Automated Test - LRAC-13984 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-13984

Let me know what you think about disabling this test. So it's currently failing because now the x-axis on the activities chart does not show the ticks when there is no data present. This test checks all time periods to make sure the x-axis marks are showing the correct pattern

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by nkkwon — APPROVED** [review]
LGTM! :+1:

**Comment by manuferreira** [comment]
Hmm so probably this test could be covered by the personas approach? since we are supposed to generate data, we would have data for all the time filters or we could see if the dev team can create a test for this case. But anyway, I think the best solution is to ignore it, thanks Josh.

**Review by manuferreira — APPROVED** [review]

**Review by ViniLopes20 — APPROVED** [review]
Thanks for disabling this test Josh, we need sessions to close faster for this case to work. LGTM 🎉

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
