### PR TITLE
LRAC-12638 - Handle hover effects on disabled table row

### PR DESCRIPTION
**Pull request by ilzamcmed**
https://issues.liferay.com/browse/LRAC-12638

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by interaminense — CHANGES_REQUESTED** [review]
Instead of do that. Could you just remove className `text-muted` from `ClayTable.Row` and add it on `<ClayTable.Cell` at line 120 on Content.tsx component.

**Comment by ilzamcmed** [comment]
> Instead of do that. Could you just remove className `text-muted` from `ClayTable.Row` and add it on `<ClayTable.Cell` at line 120 on Content.tsx component.

Thanks @interaminense, I had not think of that possibility

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by interaminense** [comment]
@ilzamcmed, please send this PR directly to Brian.

**Comment by ilzamcmed** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/127985

**Pull request closed without merging**
