### PR TITLE
LPD-25000 | Master

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @interaminense, this failure is a CI problem that is failing the tests sometimes. I have already talked to them to investigate the problem. Not related to your PR

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
