### PR TITLE
LPS-199884 Remove metal-ajax and metal-structs

### PR DESCRIPTION
**Pull request by p2kmgcl**
Hey there! We are continuing removing metal-* dependencies from portal. Now I have removed metal-ajax, and it looks like it can be easily replaced with the native fetch function.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Review by interaminense — APPROVED** [review]
LGTM, @p2kmgcl!

**Comment by interaminense** [comment]
Thanks a lot for working on it!

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
