### PR TITLE
[F] LRAC-14587 unit tests

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LRAC-14587

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by interaminense** [comment]
Waiting for Brian's sync with master to run ci:test:sf again. cc: @fmarcio

**Comment by fmarcio** [comment]
> Waiting for Brian's sync with master to run ci:test:sf again. cc: @fmarcio

@interaminense sync is done. I'm going to run SF test again

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:forward

**Review by interaminense — COMMENTED** [review]
LGTM!

**Comment by marcellustavares** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:stable:sf

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
Resent https://github.com/brianchandotcom/liferay-portal/pull/141279

**Pull request closed without merging**
