### PR TITLE
LPD-30325 | Master

### PR DESCRIPTION
**Pull request by interaminense**
https://liferay.atlassian.net/browse/LPD-29588

### CODE REVIEW

**Comment by interaminense** [comment]
cc: @ViniLopes20

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @interaminense, you need to run the tests that you tried to fix on the CI. Follow this [documentation](https://liferay.atlassian.net/wiki/spaces/ENGAC/pages/2895183873/How+to+run+the+Playwright+or+and+Poshi+tests+in+the+CI#%3Aci%3A-%3Aposhi%3A-How-to-run-a-specific-Poshi-test-in-the-CI%3F) to learn how to do this

**Comment by interaminense** [comment]
ci:test:analytics-cloud

**Comment by ViniLopes20** [comment]
Resend here: https://github.com/liferay-ac/liferay-portal/pull/1671

**Pull request closed without merging**
