### PR TITLE
Disable AC Automation - LRAC-14553 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14553 (Bug 1 - Fixed)
https://liferay.atlassian.net/browse/LRAC-14468 (Bug 2 - Open)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM! Hopefully we can get those default users back

**Review by nkkwon — APPROVED** [review]
LGTM! :+1:

**Review by manuferreira — APPROVED** [review]
LGTM. Hope we can manage to bring them back! :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
