### PR TITLE
AC Test Fix - LRAC-12179 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-12179 (Bug)
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2010886779&testrayRunId=2010899217)

**Note:**
After fixing this bug, the documentation link for the connection part was changed, so we need to update our automation to be able to navigate to the correct tab that will open and check the new title of the documentation

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
Nice, thank you :tada: :police_officer:

**Review by calvinctvo — APPROVED** [review]
thanks @ViniLopes20 ! LGTM

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
