### PR TITLE
LRAC-14780

### PR DESCRIPTION
**Pull request by riccardo-ferrari**
Hi guys,

This PR bring the 1st of the 2 required recommendation managers. Will be the entry point for the collection providers in order to fetch and display recommended asset entries. Some classes are already split with their base classes to be shared with the 2nd recommendation manager needed by this endeavour.

This structure - in accordance with our conversation with Marco - is a replica of what we did for Commerce some time ago.

Thank you

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
hey @riccardo-ferrari, I removed some abstractions for now so I can slowly digest whats coming in. Sorry about the inconvenience. We can re add the abstractions in the next pulls if needed. Let's do one recommendation at a time please.

Also, I have a couple suggestions, I didn't really changed on my pull but I would like

1. Instead of interface UserContentRecommendation can we just have a class?
2. Can we rename UserContentRecommendation to AssetRecommendation?

See https://github.com/liferay-ac/liferay-portal/pull/776

Thanks

**Comment by riccardo-ferrari** [comment]
> Can we rename UserContentRecommendation to AssetRecommendation?

This was very painful when we did the Commerce recommenders too. we have multiple entities that refer to the same content/asset however use a different process.

This is:
- User -> It is a recommendation for the User
- Content -> what we recommend. This can be Asset
- Recommendation -> it is a recommendation

Next will be something like: MostPopularContentRecommendation ...

On a side note the algorithm used to generate UserContentRecommendations can generate also 
ContentInteractionContentRecommendation:
- ContentInteraction -> It is a rec for a content (similar item). Interaction because is generated by user interaction activity
- Content -> what we recommend
- Recommendation -> ..

Open to change Content to Asset but the naming structure is pretty tested, what do you think?

**Pull request closed without merging**
