### PR TITLE
AC Test fix - LRAC-11157 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11157

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks @joshitagaki 😄

**Review by manuferreira — APPROVED** [review]
LGTM, thanks Josh :grin:

**Review by calvinctvo — APPROVED** [review]
LGTM, thanks @joshitagaki

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
