### PR TITLE
AC Test fix - LRQA-79862 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRQA-79862 (Test Fix)
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2237517947&testrayRunId=2237518007)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks for fixing this Vini! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks :muscle: :tada:

**Review by calvinctvo — APPROVED** [review]
Thank you @ViniLopes20 for the fix! LGTM

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
