### PR TITLE
LPD-16063 | Master

### PR DESCRIPTION
**Pull request by interaminense**
https://liferay.atlassian.net/browse/LPD-16063

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @interaminense, the AC functional tests are not working because of a problem creating the Faro image that was caused by a version change made by a DXP team. Marcos told me that it should work again after this [PR](https://github.com/liferay-ac/liferay-portal/pull/1101) is merged

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:help

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
Backport here https://github.com/liferay-ac/liferay-portal/pull/1117

**Comment by interaminense** [comment]
Followup to 4.6.x after force push https://github.com/liferay-ac/liferay-portal/pull/1119

**Comment by interaminense** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
