### PR TITLE
LRAC-13054 - [P] Add missing properties called title and formPageTitle in the fieldFocused and fieldBlurred events

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://issues.liferay.com/browse/LRAC-13054

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:stop

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @fmarcio :rocket:

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
