### PR TITLE
LRAC-12771 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-12771

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by joshitagaki** [comment]
Semantic Versioning failure @marcosapmf :
`[exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/analytics/analytics-settings-rest-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.analytics.settings.rest.manager        MINOR      1.1.0      1.1.0      1.2.0      VERSION INCREASE REQUIRED
     [exec]     	<   interface  com.liferay.analytics.settings.rest.manager.AnalyticsSettingsManager
     [exec]     		+   method     syncedAccountFieldsChanged(long)
     [exec]     			+   access     abstract
     [exec]     			+   return     boolean
     [exec]     		+   method     syncedAccountSettingsChanged(long)
     [exec]     			+   access     abstract
     [exec]     			+   return     boolean
     [exec]     		+   method     syncedAccountSettingsEnabled(long)
     [exec]     			+   access     abstract
     [exec]     			+   return     boolean
     [exec]     		+   method     syncedCommerceSettingsChanged(long)
     [exec]     			+   access     abstract
     [exec]     			+   return     boolean
     [exec]     		+   method     syncedCommerceSettingsEnabled(long)
     [exec]     			+   access     abstract
     [exec]     			+   return     boolean
     [exec]     		+   method     syncedContactSettingsChanged(long)
     [exec]     			+   access     abstract
     [exec]     			+   return     boolean
     [exec]     		+   method     syncedContactSettingsEnabled(long)
     [exec]     			+   access     abstract
     [exec]     			+   return     boolean
     [exec]     		+   method     syncedOrderFieldsChanged(long)
     [exec]     			+   access     abstract
     [exec]     			+   return     boolean
     [exec]     		+   method     syncedProductFieldsChanged(long)
     [exec]     			+   access     abstract
     [exec]     			+   return     boolean
     [exec]     		+   method     syncedUserFieldsChanged(long)
     [exec]     			+   access     abstract
     [exec]     			+   return     boolean
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 3.8.0`

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by riccardo-ferrari** [comment]
ci:forward

**Review by riccardo-ferrari — APPROVED** [review]

**Pull request closed without merging**
