### PR TITLE
LRCI-4163 Add AC suites to the list of available test suites

### PR DESCRIPTION
**Pull request by CalumR23**
https://liferay.atlassian.net/browse/LRCI-4163

### CODE REVIEW

**Comment by christianstokes** [comment]
Hey team, this is required to run the release tests.

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by CalumR23** [comment]
Hey AC team this commit was cherry-picked from master. It has passed all previous suites to make it into BChans origin

**Comment by interaminense** [comment]
@marcellustavares could you merge it and update UAT?

**Comment by christianstokes** [comment]
The commits are not necessary to be on UAT, it's just a property so that CI can successfully run the automated release tests based on the 4.8.x branch.

**Pull request merged**
