### PR TITLE
LRAC-12185 Commerce Connection - Property Step Stuff

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issues: https://issues.liferay.com/browse/LRAC-11904, https://issues.liferay.com/browse/LRAC-11905, https://issues.liferay.com/browse/LRAC-12184, https://issues.liferay.com/browse/LRAC-12185

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
Resent https://github.com/liferay-ac/liferay-portal/pull/156

**Comment by interaminense** [comment]
ci:close

**Comment by interaminense** [comment]
ci:stop

**Pull request closed without merging**
