### PR TITLE
LRAC-12616 Follow up: improve unit tests and organize folders

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://issues.liferay.com/browse/LRAC-12616

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Review by interaminense — APPROVED** [review]
LGTM! Thanks a lot @fmarcio !!

**Review by ilzamcmed — APPROVED** [review]
LGTM :rocket:

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:forward

**Comment by fmarcio** [comment]
ci:forward

**Review by interaminense — APPROVED** [review]
LGTM!

**Pull request closed without merging**
