### PR TITLE
LRAC-14397 and LRAC-13113

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issues: https://issues.liferay.com/browse/LRAC-14397, https://issues.liferay.com/browse/LRAC-13113

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
