### PR TITLE
[F] Limit button to create a variant to 1

### PR DESCRIPTION
**Pull request by JLucasM**
LRAC-14380: [Jira Issue](https://liferay.atlassian.net/browse/LRAC-14380)

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
Resent to https://github.com/liferay-echo/liferay-portal/pull/13309

**Pull request closed without merging**
