### PR TITLE
LRAC-13916 - [BUG] Settings Definition - Block and hide icons not working

### PR DESCRIPTION
**Pull request by ilzamcmed**
Jira issue: https://issues.liferay.com/browse/LRAC-13916

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @ilzamcmed

**Comment by ilzamcmed** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
