### PR TITLE
LRAC-12808 - Enable feature flag by default

### PR DESCRIPTION
**Pull request by ilzamcmed**
https://issues.liferay.com/browse/LRAC-12808

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Review by interaminense — APPROVED** [review]
LGTM! This PR is on hold until all commerce stories be done.

**Comment by interaminense** [comment]
<div align="center">:warning: This PR is on hold until all commerce stories be done. :warning:</div>

**Comment by marcosapmf** [comment]
Hey @ilzamcmed, can you please resolve the conflicts and force push?
Thanks :wink:

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Hey @ViniLopes20, let's send it directly to Brian as soon as possible.

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
