### PR TITLE
AC Automated Tests - LRAC-13586 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-13586

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks, my amigo :male_detective:

**Review by nkkwon — APPROVED** [review]
LGTM! Thank you for working on this! :+1:

**Comment by ViniLopes20** [comment]
ci:forward:force

**Pull request closed without merging**
