### PR TITLE
LRAC-12758 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**
Jira Issue: https://issues.liferay.com/browse/LRAC-12758

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Review by marcosapmf — CHANGES_REQUESTED** [review]
Hey @leilanyaragao,
we just have the change in `service.xml` file. You need to run `buildService` gradle task to see your changes reflected in the java classes

**Comment by marcosapmf** [comment]
ci:test:relevant

**Review by marcosapmf — APPROVED** [review]

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
