### PR TITLE
LRAC-14472 Unit tests

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://issues.liferay.com/browse/LRAC-14472

### CODE REVIEW

**Comment by interaminense** [comment]
There is a new one commit in this PR https://github.com/liferay-ac/liferay-portal/pull/716/commits/ccfe4dd82c867bb7add17896d078bcfb1899308c. Another ones is merged but it needs a sync from brian to master

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! thanks @interaminense :rocket:

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward:force

**Comment by interaminense** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/140918

**Pull request closed without merging**
