### PR TITLE
AC Automated Test - LRAC-11508 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRAC-11508 (Automation ticket)

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good test, LGTM. Thanks 🎉

**Review by joshitagaki — APPROVED** [review]
Nice job! LGTM!

**Review by manuferreira — APPROVED** [review]
LGTM! Very nice, Calvin :tada:

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
