### PR TITLE
LPD-35511 LPD-35515 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://liferay.atlassian.net/browse/LPD-35511
https://liferay.atlassian.net/browse/LPD-35515

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
Hi @rachaelkoestartyo, it looks good to me! Thanks

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
