### PR TITLE
LPS-199879 Remove dependency

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
Hey @interaminense, the failure of `acceptance` is related to this [bug](https://liferay.atlassian.net/browse/LRAC-15298). The PR looks good to be forwarded after the stable is passing. Thanks!

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
