### PR TITLE
LPD-23149 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LPD-23149

### CODE REVIEW

**Comment by marcosapmf** [comment]
waiting for https://github.com/liferay-ac/liferay-portal/pull/1437 being merged

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
hey @marcosapmf https://github.com/brianchandotcom/liferay-portal/pull/149734 is now merged

**Comment by marcosapmf** [comment]
forwarded to https://github.com/brianchandotcom/liferay-portal/pull/149734

**Pull request closed without merging**
