### PR TITLE
AC Test Fix - LRAC-11839 | master

### PR DESCRIPTION
**Pull request by manuferreira**
[Testray run](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1989632909&testrayRunId=1989632960)
[Jira ticket](https://issues.liferay.com/browse/LRAC-11839)

- I tried using different click macros because I thought the problem was when the test tries to save the segment, but none of them worked, and when I run this test locally I couldn't reproduce the error (mysteries :sparkles:) but when I shorten the name of the segment it works (and I don't know why :thinking:).

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Hmm that is weird, wonder why it works with a shorter segment name haha. LGTM!

**Review by ViniLopes20 — APPROVED** [review]
Very funny this problem hahaha, good discovery Manu. LGTM 🎉 🕵🏽‍♀️

**Review by calvinctvo — APPROVED** [review]
Haha good catch @manuferreira ! LGTM

**Review by christianstokes — APPROVED** [review]
Looks good to me. Approved.

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
