### PR TITLE
LPD-7672 | master

### PR DESCRIPTION
**Pull request by riccardo-ferrari**

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Review by marcellustavares — CHANGES_REQUESTED** [review]
Please skip timezone updates during PATCH if it's set to blank.

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Review by marcellustavares — APPROVED** [review]

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
