### PR TITLE
LRAC-12924 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-12924

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by joshitagaki** [comment]
ci:test:relevant

**Review by riccardo-ferrari — APPROVED** [review]

**Comment by riccardo-ferrari** [comment]
ci:forward

**Pull request closed without merging**
