### PR TITLE
AC Test Fix LRAC-14317 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14317

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good, Josh. Thanks for fixing those cases that were already present in the settings screen like the API tests. LGTM 🎉

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you! :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
