### PR TITLE
Disable AC Automated Tests - LRAC-13675 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-13675

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you! :muscle:

**Review by nkkwon — APPROVED** [review]
LGTM! :+1:

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward:force

**Pull request closed without merging**
