### PR TITLE
AC Test fix - LRAC-11473 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11473

Let me know what you think of using this solution. This shouldn't conflict with any other tests as it is mainly checking to see if the connection is present it will disconnect the connection.

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, Josh. I was thinking about this same solution for this ticket, I think it will be a good idea to always do this check to avoid these cases.

**Review by manuferreira — APPROVED** [review]
Nice fix, Josh :clap: :clap:

**Review by calvinctvo — APPROVED** [review]
Great catch @joshitagaki ! This could help stable some of out connectivity tests! LGTM

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
