### PR TITLE
LRAC-13481 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
Jira ticket: https://issues.liferay.com/browse/LRAC-13481

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
Thanks @ViniLopes20 :tada: :rocket:

**Pull request closed without merging**
