### PR TITLE
LRAC-11874 [F] Implement Workspace connection step / LRAC-11909 - [F] Implement Sidebar after connection is done

### PR DESCRIPTION
**Pull request by fmarcio**
https://issues.liferay.com/browse/LRAC-11899

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
liferay/ci:test:relevant

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Hello reviewers, I'll get this PR to do some changes. Please do not move forward yet!

**Comment by interaminense** [comment]
Resent to https://github.com/liferay-ac/liferay-portal/pull/115

**Pull request closed without merging**
