### PR TITLE
LRAC-13517 Update Clay components versions to fix segment bug

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://issues.liferay.com/LRAC-13517

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! thanks @interaminense :rocket:

**Comment by ViniLopes20** [comment]
Hey @interaminense, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
