### PR TITLE
LRAC-13874 set Node version for faro-web

### PR DESCRIPTION
**Pull request by thiago-buarqque**

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Review by interaminense — CHANGES_REQUESTED** [review]
Node 16.18 will brake our frontend.

**Comment by interaminense** [comment]
node v16.17.0
yarn 1.22.19

**Comment by thiago-buarqque** [comment]
ci:test:stop

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @thiago-buarqque, I looked into it here and apparently the issues are not related to your changes. Thanks

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
Merged in https://github.com/liferay/liferay-portal/commit/73b4e091b4e2a6b3238ba6304e9f3228f6ff3d16

**Pull request closed without merging**
