### PR TITLE
LPD-20256 Fix to Url is not displaying correctly

### PR DESCRIPTION
**Pull request by sillascavalcanti**
[Issue](https://liferay.atlassian.net/browse/LPD-20256)

### CODE REVIEW

**Comment by sillascavalcanti** [comment]
ci:test:sf

**Comment by sillascavalcanti** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @sillascavalcanti. You need to backport it to 4.8.x once the branch is created.

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
