### PR TITLE
AC Test Fix - LRAC-14837 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14837

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Good find! LGTM

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you! :detective:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
