### PR TITLE
LPD-20115 resend | master

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LPD-20115

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:analytics-cloud-acceptance

**Review by interaminense — APPROVED** [review]
LGTM! Could you backport to 4.7.x?

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:forward

**Pull request closed without merging**
