### PR TITLE
AC Remove from quarantine - LRAC-11262 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11262
Passing consistently
[Testray](https://testray.liferay.com/home/-/testray/case_results/2154122530/history?tab=result&hideFilterPin=true)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good, thanks for looking at this case, Josh 🎉

**Review by manuferreira — APPROVED** [review]
Thanks for taking a look at it, Josh :muscle:

**Review by calvinctvo — APPROVED** [review]
Thanks @joshitagaki for enabled these tests again!

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
