### PR TITLE
AC Test fix - LRAC-12446 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-12446

This test is failing in the development team's PR

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by manuferreira** [comment]
LGTM. Thanks.

**Review by manuferreira — APPROVED** [review]

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks Vini! Hopefully this fixes the issue

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
