### PR TITLE
LPS-191826 Quarantining AnalyticsSettingsManagerTest due to implementation silent failure

### PR DESCRIPTION
**Pull request by AkramYoussoufi**
This test is Quarantined due to this reasons mentioned in this [ticket](https://liferay.atlassian.net/browse/LPS-191826)

### CODE REVIEW

**Comment by AkramYoussoufi** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:forward:force

**Pull request closed without merging**
