### PR TITLE
LPD-33375 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-33375

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:stop

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud

**Comment by ViniLopes20** [comment]
resent: https://github.com/liferay-ac/liferay-portal/pull/1743

**Pull request closed without merging**
