### PR TITLE
Removes FF for LRAC-14922

### PR DESCRIPTION
**Pull request by interaminense**
https://liferay.atlassian.net/browse/LPD-15819

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Review by marcosapmf — APPROVED** [review]

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Pull request closed without merging**
