### PR TITLE
LPD-41964 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-41964

### CODE REVIEW

**Comment by marcellustavares** [comment]
hi @marcosapmf @rachaelkoestartyo LGTM, however I think we should prefix those configuration variables together. I added some suggestions. Let me know what you think.

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
Thanks @marcellustavares! Just updated the pull with your suggestions :)

**Comment by marcosapmf** [comment]
ci:test:sf

**Review by rachaelkoestartyo — COMMENTED** [review]
added a commit and resent https://github.com/liferay-ac/liferay-portal/pull/1950

**Pull request closed without merging**
