### PR TITLE
AC Test Fix - LRAC-15262 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-15262

**Description:**

The Try Again button issue was with the workaround being used in the getAssignedPropertyName macro. Tests that did not use this macro could continue to suffer from the problem.

**Solution:**

Move the alternative to avoid the Try Again button to the connectAnalyticsCloud macro, this macro is used by all tests that make the connection between AC and DXP and this problem should not affect other tests. I researched and all uses of the getAssignedPropertyName macro always have the use of the connectAnalyticsCloud macro before.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hey @joshitagaki, I made this change and wanted to know what you think. I put a `wait` to ensure that the Next button is present and the page has loaded

**Review by joshitagaki — APPROVED** [review]
Thanks Vini. Yea I agree with this change. Makes more sense to move it to the connection macro

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
