### PR TITLE
AC Test Fix - LRAC-12696 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-12696
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2148829081&testrayRunId=2148838285)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Good catch, Josh. Thanks for it! LGTM 🎉

**Review by calvinctvo — APPROVED** [review]
Thank you for the fix @joshitagaki ! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM! Thank you, Josh :tada:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
