### PR TITLE
AC Test Fix - LRAC-15198 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-15198

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — COMMENTED** [review]
Hey @joshitagaki, This problem is very strange hahaha. I think this could be a solution, but I was wondering if you ran this locally or in CI with the modifications to see if this will work? I think it would be good to do this since this is not a solution that we can know if it will work just by looking at the code

**Comment by joshitagaki** [comment]
Yea I wanted to run it on CI but since this is going to upstream the test fails to start. I ran it locally just to see that it is possible to go to the correct site page.

**Comment by ViniLopes20** [comment]
> Yea I wanted to run it on CI but since this is going to upstream the test fails to start. I ran it locally just to see that it is possible to go to the correct site page.

Ohhh nice, Josh. I had forgotten about the CI problem when I posted the comment. Thanks man

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
