### PR TITLE
AC Test fix - LRAC-12810 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-12810
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2173642731)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — COMMENTED** [review]
Hey @joshitagaki, I noticed that in the [Testray](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/8344/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.SegmentsCreationWebBehavior_CheckWebBehaviorSegmentShowsWhichDataSourceDataCameFrom/index.html.gz?authuser=0) your test failed in that click and you removed it, but I was thinking that in the image in the Poshi Report, the segment did not have the criteria added, so I wanted to know if when you executed it after this removal if the criterion was really added

`Click(locator1 = "ACSegments#MODAL_CANCEL_BUTTON");`

image

**Review by manuferreira — CHANGES_REQUESTED** [review]
Hey Josh, thanks for working on it. I was taking a look at this test and I think [this step](https://github.com/liferay-ac/liferay-portal/pull/276/files#diff-8726008809ca4a9364255e8752a84c70ff999b29d48f72cfcb21f91da96bcfccR1421-R1427) is not necessary since you can just click on the select button.

**Comment by joshitagaki** [comment]
> Hey @joshitagaki, I noticed that in the [Testray](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/8344/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.SegmentsCreationWebBehavior_CheckWebBehaviorSegmentShowsWhichDataSourceDataCameFrom/index.html.gz?authuser=0) your test failed in that click and you removed it, but I was thinking that in the image in the Poshi Report, the segment did not have the criteria added, so I wanted to know if when you executed it after this removal if the criterion was really added
> 
> `Click(locator1 = "ACSegments#MODAL_CANCEL_BUTTON");`
> 
> image

@ViniLopes20 so for this test adding the segment is not the purpose of this test so I removed the close modal step. I ended the test to the point where it is checking the validation of data source in the selection screen. As @manuferreira said just selecting the select button would also work, but I think that would still be an unnecessary step to the test that is checking the data source is correct for assets in segments.
Let me know what you guys think. Thanks for the responses!

**Comment by manuferreira** [comment]
```
ACSegments.editWebBehaviorCriterion(
				indexField = "1",
				occurenceNumber = "4",
				searchTerm = "Blogs AC Title - Site Name - Liferay DXP");
```

but don't you think this is not necessary? since we can start to create the segment but not necessarily edit the infos and fill them with data, we can skip to the `task ("Check for data source origin")` @joshitagaki

**Comment by joshitagaki** [comment]
> ```
> ACSegments.editWebBehaviorCriterion(
> 				indexField = "1",
> 				occurenceNumber = "4",
> 				searchTerm = "Blogs AC Title - Site Name - Liferay DXP");
> ```
> 
> but don't you think this is not necessary? since we can start to create the segment but not necessarily edit the infos and fill them with data, we can skip to the `task ("Check for data source origin")` @joshitagaki

Oh I see what you mean. Yea that doesn't seem necessary either... I'll need to look into this test closer because I'm not sure why it's doing that step and was able to pass since it wouldn't have been able to move onto the next step.

**Pull request closed without merging**
