### PR TITLE
LPS-199327 Remove 'metal-promise'

### PR DESCRIPTION
**Pull request by p2kmgcl**
The goal of this PR is removing the deprecated metal-promise dependency with no behavior change.

For most cases the standard Promise class works exactly the same way, but I had to add a bit of implementation for a couple of cases that rely on Promise cancellation, which does not exist right now. I relied on AbortController to solve this situation: https://github.com/liferay-ac/liferay-portal/commit/7c25fc7a5827ca86fa0301eab80cb1cd078f568d

I also found some code that had (I think) wrong typing, as the API was not returning any promise: https://github.com/liferay-ac/liferay-portal/commit/868ca36f0865b04f89624e27fa579ff6cc0a7554

Apart from that, everything else is just removing the mentioned dependency.

However I broke lots of unit tests, and I am not sure how I can test the application, so I need a little guidance to see what is happening. I tried running the webpack server with `yarn run start`, but it looks like it just starts a proxy to liferay portal :thinking:

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @p2kmgcl, the failure of `acceptance` is not related to your modifications. The PR looks good to be forwarded after the `relevant` and `stable` are passing. Thanks!

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
