### PR TITLE
LRAC-12673 Fix unit tests for Wizard Group Pages

### PR DESCRIPTION
**Pull request by JLucasM**
LRAC-12673: [Jira Issue](https://issues.liferay.com/browse/LRAC-12673)

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by interaminense** [comment]
It is failing unit tests

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by JLucasM** [comment]
ci:test:stable

**Review by ilzamcmed — APPROVED** [review]
LGTM :rocket:

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
