### PR TITLE
AC Test fix - LPS-177768 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LPS-177768
https://issues.liferay.com/browse/LRAC-13085
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2224084322&testrayRunId=2224085200) - I ran a test from the Tango team which was failing with the click on disconnect issue

**Solution for the AC team:**
I noticed that we used the same path for the connect and disconnect buttons, so I think he would click on the connect button and then wait for the confirmation to disconnect (but this only happens when clicking the disconnect button), so I separated the paths. But I still don't know why Poshi pass in the `IF` condition when it wasn't imagined to enter, so I modified the condition to enter in the `IF` and hope this can solve this problem

**Solutions for the Tango team:**
The Tango team had a test fail because the path they used didn't work with the new wizard, that path was the click on the disconnect button that was performed in the disconnect macro that the Tango team used. I've updated the Tango tests to use the AC disconnect macro. I don't think that in this case, it's good for the Tango team to have macros and paths for the AC product that is separate from ours, that way increasing the chance of their tests failing since we may not be able to maintain and update their macros and paths.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hey @rafaellajordao, could you look at the modifications in the Tango tests?

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM!

**Review by manuferreira — APPROVED** [review]
Thank you for looking into it! :tada: :muscle: Good solution separating the xpaths, I think it`s clearer this way.

**Review by calvinctvo — APPROVED** [review]
Thank you so much for the fix @ViniLopes20 ! LGTM

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
