### PR TITLE
LRAC 13476

### PR DESCRIPTION
**Pull request by ivicac**
- LRAC-13476 - Add AnalyticsCloudBearerTokenProvider
- LRAC-13476 - Pass expiresIn value to AnalyticsCloudBearerTokenProvider
- LRAC-13476 - Add “apps:oauth2-provider:oauth2-provider-rest-spi” dependency

### CODE REVIEW

**Comment by ivicac** [comment]
@interaminense here is the backend port for LRAC-13255 story.

**Comment by interaminense** [comment]
LGTM! Thanks @ivicac

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
