### PR TITLE
LRAC-12180 Fix documentDownloaded AC event 

### PR DESCRIPTION
**Pull request by JLucasM**
LRAC-12180: [Jira Issue](https://issues.liferay.com/browse/LRAC-12180)

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by JLucasM** [comment]
ci:stop

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
