### PR TITLE
LRAC-14050 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-14050

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
Hey @marcosapmf, the `relevant` failure is not related to your modifications. I believe we can forward this PR

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
