### PR TITLE
LRAC-14780 | 7.0.x

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test

**Comment by ViniLopes20** [comment]
ci:stop

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @marcellustavares, the failure of `relevant` and `acceptance` are not related to your modifications. The PR looks good to be forwarded after the `SF` is passing. Thanks!

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
It's a new dawn. It's a new day.

https://github.com/liferay-ac/liferay-portal/pull/784

**Pull request closed without merging**
