### PR TITLE
AC Test Fix - LRAC-14809 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14809

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by nkkwon — APPROVED** [review]
LGTM! :+1:

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks Vini :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
