### PR TITLE
LRAC-14910 Support downloading PDF report for Individuals Overview

### PR DESCRIPTION
**Pull request by JLucasM**
LRAC-14910: [Jira Issue](https://liferay.atlassian.net/browse/LRAC-14910)

### CODE REVIEW

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @JLucasM

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
