### PR TITLE
LPD-20251 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LPD-20251

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
backport to faro-v4.7.x sent to https://github.com/liferay-ac/liferay-portal/pull/1264

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
waiting for https://github.com/liferay/com-liferay-osb-asah-private/pull/5715 gets merged

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
