### PR TITLE
AC Test Fix LRAC-14511 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14511

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks Josh 🎉

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for the fix! :male_detective:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
