### PR TITLE
LRAC-14051 | master

### PR DESCRIPTION
**Pull request by thiago-buarqque**
Faro was based on 7.1.x, after migrating to master we got a unnexpected default value for `oauth2.authorization.server.issue.jwt.access.token` ([See](https://github.com/liferay-ac/liferay-portal/blob/c31442f7c68cb19f519791e87812699f796dc454/modules/apps/oauth2-provider/oauth2-provider-rest/src/main/java/com/liferay/oauth2/provider/rest/internal/configuration/OAuth2AuthorizationServerConfigurationGenerator.java#L54))

Fix: added file to prevent default value for `auth2.authorization.server.issue.jwt.access.token`

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by thiago-buarqque** [comment]
ci:reevaluate:1407401_3346

**Comment by thiago-buarqque** [comment]
Changes are being applied, do not review it

**Pull request closed without merging**
