### PR TITLE
AC New Automated Test - LRAC-14794 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14794

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good, Josh. LGTM 🎉

**Review by nkkwon — APPROVED** [review]
LGTM! :+1:

**Review by manuferreira — APPROVED** [review]
Very good, Josh. Thank you!

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
