### PR TITLE
AC Test Fix - LRAC-14526 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14526
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2421309907&testrayRunId=2421310039)[
Testray echo](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2421476685&testrayRunId=2421476723)

### CODE REVIEW

**Review by ViniLopes20 — APPROVED** [review]
Thanks Josh, LGTM 🎉

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for looking into this! :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
