### PR TITLE
LRAC-14652 - Second-Order SQL Injection vulnerability in UpgradeProcess | master

### PR DESCRIPTION
**Pull request by ivicac**

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:stable

**Review by marcosapmf — APPROVED** [review]

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:stable

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ivicac** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
