### PR TITLE
LPD-26351 | master

### PR DESCRIPTION
**Pull request by fmarcio**
https://liferay.atlassian.net/browse/LPD-26351

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:analytics-cloud-acceptance

**Comment by fmarcio** [comment]
@ViniLopes20 is this acceptance error related to the playwright test we discussed today? thanks

**Comment by fmarcio** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @fmarcio, The acceptance failure is related to a problem in [one of the playwright tests](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2571636162&testrayRunId=2571636173). [I fix this today](https://liferay.atlassian.net/browse/LCD-38204), but it is not related with you modifications. Thanks!

**Comment by fmarcio** [comment]
ci:test:sf

**Review by interaminense — APPROVED** [review]
LGTM! Thanks

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:forward

**Pull request closed without merging**
