### PR TITLE
AC Automated Test - LRAC-11541 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11541 (Automation ticket)
https://issues.liferay.com/browse/LRAC-9589 (Bug)
[Could not run the test on CI because of problem building AC](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1941323791&testrayRunId=1941329053)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:stop

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks @ViniLopes20!

**Review by calvinctvo — APPROVED** [review]
Hey @ViniLopes20 ! Thanks for working on this, LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks a lot Vini :tada:

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
