### PR TITLE
LPD-41935 | URL directing to documentation on Block list events shows 404 error

### PR DESCRIPTION
**Pull request by rafaellajordao**
More details: [LPD-41935](https://liferay.atlassian.net/browse/LPD-41935)

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:relevant

**Comment by rafaellajordao** [comment]
all tests passed locally :heavy_check_mark: 
Test Suites: 1 skipped, 615 passed, 615 of 616 total
Tests:       34 skipped, 2570 passed, 2604 total
Snapshots:   759 passed, 759 total
Time:        242.711 s
Ran all test suites.
Done in 243.53s.

**Review by interaminense — APPROVED** [review]
Thanks @rafaellajordao

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
