### PR TITLE
LPD-24713 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LPD-24713

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:test:analytics-cloud-acceptance

**Review by marcellustavares — APPROVED** [review]

**Comment by marcellustavares** [comment]
ci:foward:force

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
