### PR TITLE
AC Improvement Test - LRAC-15311 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-15311
[LocalFile.ConnectACWithDXP#CheckIsPossibleConnectACWithValidToken](https://testray.liferay.com/home/-/testray/case_results/2476990066?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DCheckIsPossibleConnectACWithValidToken%26testrayBuildId%3D2476989621%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
Thanks Vini! This test should be pretty stable to run on relevant. Hopefully more tests can be added at a later time. Just needs to fix the SF to forward.

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
> Thanks Vini! This test should be pretty stable to run on relevant. Hopefully more tests can be added at a later time. Just needs to fix the SF to forward.

Thanks, Josh. I hope we can put more tests, especially to validate that the portal modifications are not affecting asset events. I will forward 🙏🏽

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
