### PR TITLE
LRAC-14749 Change script ID when portal updates language to remove cache and load it again and then send events

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://liferay.atlassian.net/browse/LRAC-14749

## Motivation

Senna (DXP's SPA) makes a kind of cache for scripts with `data-senna-track="permanent"` and that prevents in some way (still unknown) that the script is not loaded after repeating the steps below:

### Steps

1. Create two users on DXP;
2. The second user should have a different language from the first one;
3. Log in with the first user, navigate SPA, and console should render (OK);
4. Now, log in with the second user and console isn't rendering (BUG);

### Code to reproduce

Add the code below on DXP
```javascript
<script data-senna-track="permanent" id="requiredId" type="text/javascript">
    Liferay.on('endNavigate', () => {
        console.log('it is working!');
    });
</script>
```

### CODE REVIEW

**Comment by interaminense** [comment]
cc: @marcellustavares

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Review by marcosapmf — APPROVED** [review]

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
s

**Pull request closed without merging**
