### PR TITLE
LPD-25251 Fix null pointer exception in FragmentExportImportTest#testImportUpdateFragmentEntryWithPropagationEnabled

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----

Fix null pointer exception in FragmentExportImportTest#testImportUpdateFragmentEntryWithPropagationEnabled

Proposed Solution
----

Adds null check to validate if the ipAddress is null or not and return a blank countryCode to keep the old behavior

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Review by marcosapmf — APPROVED** [review]

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Manual forward see: https://github.com/brianchandotcom/liferay-portal/pull/150243

**Pull request closed without merging**
