### PR TITLE
LRAC-15063 Fix unit tests on master after remove metalJS packages

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://liferay.atlassian.net/browse/LRAC-15063

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket: thanks for the hard work, @interaminense !

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
