### PR TITLE
LRAC-15206 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-15206

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:forward:force

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @marcosapmf, the Faro cannot be started after these modifications. Could you see the [list of container logs here](https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/890749/) to identify any errors that could help you?

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/964

**Pull request closed without merging**
