### PR TITLE
LPD-1210 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://liferay.atlassian.net/browse/LPD-1210

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:reevaluate:1327401_3677

**Comment by ViniLopes20** [comment]
Hey @rachaelkoestartyo, the acceptance failure is related to this [bug](https://liferay.atlassian.net/browse/LPD-17914). But from the result, I can see that the AC can be built correctly without any problems

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
