### PR TITLE
LRAC-14487 | master

### PR DESCRIPTION
**Pull request by lesliewong92**
https://liferay.atlassian.net/browse/LRAC-14487

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:forward

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @lesliewong92, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by lesliewong92** [comment]
ci:forward:force

**Pull request closed without merging**
