### PR TITLE
AC Test Fix - LRAC-11312 | master

### PR DESCRIPTION
**Pull request by manuferreira**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1867562845&testrayRunId=1867562972 (Testray run)
https://issues.liferay.com/browse/LRAC-11312 (ticket)

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM Manu, good catch 🕵🏽‍♀️

**Review by calvinctvo — APPROVED** [review]
Hey @manuferreira Thanks for catching this! LGTM

**Review by christianstokes — APPROVED** [review]
LGTM. Nice!

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
