### PR TITLE
LRAC-14871 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://liferay.atlassian.net/browse/LRAC-14871

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @rachaelkoestartyo, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
