### PR TITLE
LPD-32841 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-32841

cc @JerryAdrianoo

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by JerryAdrianoo** [comment]
Hi @marcosapmf, I have put the test results in this [spreadsheet](https://docs.google.com/spreadsheets/d/1JpoGb_qh7KswX6Pulf57HH2KaNTu9vzJDKCJ6BPRqWs/edit?gid=2121493107#gid=2121493107). It seems to be ok to be forwarded.

**Comment by JerryAdrianoo** [comment]
Hi @marcosapmf I have put the results in this [spreadsheet](https://docs.google.com/spreadsheets/d/1JpoGb_qh7KswX6Pulf57HH2KaNTu9vzJDKCJ6BPRqWs/edit?gid=2121493107#gid=2121493107).
 Hi @shuyangzhou, as I showed you Monday, this temporary fix can be forwarded, right?

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
