### PR TITLE
Disable test from upstream routine - LRAC-11006 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11006
[Testray 1](https://testray.liferay.com/home/-/testray/subtasks/1883138120)
[Testray 2](https://testray.liferay.com/home/-/testray/subtasks/1883138118/view?cur=1&delta=20&testraySubtaskId=1883138118)
[Testray 3](https://testray.liferay.com/home/-/testray/subtasks/1883138134/view?cur=1&delta=20&testraySubtaskId=1883138134)

### CODE REVIEW

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks for finding these tests.

**Review by calvinctvo — APPROVED** [review]
Hey @ViniLopes20 , thanks for disabling these tests, LGTM

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
