### PR TITLE
AC Test fix LRAC-11171 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11171 (Ticket)
[Testray](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1860026432)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Nice LGTM! Yea I think this should be enough so we would know the message it is checking

**Review by calvinctvo — APPROVED** [review]
Thanks @ViniLopes20 for working on this, the code LGTM

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks Vini :policeman:

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
