### PR TITLE
AC Test Fix - LRAC-13319 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-13319

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for noticing that!

**Review by ViniLopes20 — APPROVED** [review]
Good catch, Josh. LGTM! 🎉

**Review by nkkwon — APPROVED** [review]
LGTM 👍

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
