### PR TITLE
LPD-34707 and LPD-34709 | master

### PR DESCRIPTION
**Pull request by fmarcio**

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:test:analytics-cloud-acceptance

**Comment by rafaellajordao** [comment]
> ### ✔️ ci:test:stable - 27 out of 27 jobs passed
> ### ❌ ci:test:relevant - 31 out of 34 jobs passed in 1 hour 25 minutes
> Click here for more details.
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [f4a74b11034dc1849ca55bd3d3927bd2e70fe22d](https://github.com/liferay/liferay-portal/commit/f4a74b11034dc1849ca55bd3d3927bd2e70fe22d)
> 
> **ci:test:stable - 27 out of 27 jobs PASSED**
> **ci:test:relevant - 31 out of 34 jobs PASSED**
> ##### For more details click [here](https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10747/jenkins-report.html).
> #### Failures (upstream comparison is not available):
> 1. [modules-unit-jdk8/0/0](https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1020630//consoleText)1. [com.liferay.osb.faro.web.internal.model.display.main.FaroSubscriptionDisplayTest](https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1020630/testReport/com.liferay.osb.faro.web.internal.model.display.main/FaroSubscriptionDisplayTest) - [Failed 0 of last 19](https://testray.liferay.com/home/-/testray/case_results/71767642/history)1. [testSetUsageCounts2](https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1020630//testReport/com.liferay.osb.faro.web.internal.model.display.main/FaroSubscriptionDisplayTest/testSetUsageCounts2)
> 2. [playwright-js-tomcat90-mysql57-jdk8/1/0](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/991339//consoleText) - [Playwright Report](https://testray.liferay.com/reports/production/logs/2024-08/test-1-40/test-portal-acceptance-pullrequest(master)/10747/playwright-js-tomcat90-mysql57-jdk8/1/0/playwright-report/index.html)1. [osb-faro-web/segment.spec.ts](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/991339/testReport/osb-faro-web_segment.spec/ts)1. [Add segment using an individual property "user group"](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/991339//testReport/osb-faro-web_segment.spec/ts/Add_segment_using_an_individual_property__user_group_)2. [Add segment using an organization property "organization"](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/991339//testReport/osb-faro-web_segment.spec/ts/Add_segment_using_an_organization_property__organization_)
> 
> #### For upstream results, click [here](https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)).

Hi @fmarcio ,
Analyzing the failures of the Relevant suite of this PR I can see that the failures are not related to your changes.

**Comment by fmarcio** [comment]
ci:forward:force

**Comment by fmarcio** [comment]
Resent to https://github.com/liferay-ac/liferay-portal/pull/1801

**Pull request closed without merging**
