### PR TITLE
[BACKPORT] New Crowdin Updates

### PR DESCRIPTION
**Pull request by ilzamcmed**
Backport to master of https://github.com/liferay/com-liferay-osb-faro-private/pull/4719

Jira issue: https://liferay.atlassian.net/browse/LRAC-14107

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by ilzamcmed** [comment]
ci:test:stable

**Comment by ilzamcmed** [comment]
ci:forward

**Comment by ilzamcmed** [comment]
ci:test:stable

**Comment by ilzamcmed** [comment]
ci:forward:force

**Pull request closed without merging**
