### PR TITLE
LPS-195290 | Baseline

### PR DESCRIPTION
**Pull request by JhossephG**
https://liferay.atlassian.net/browse/LRAC-14507

### CODE REVIEW

**Comment by JhossephG** [comment]
ci:test:relevant

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:forward:force

**Comment by ViniLopes20** [comment]
Hey @JhossephG, conflict here. Could you do a rebase and resend it?

**Comment by JhossephG** [comment]
ci:forward:force

**Comment by JhossephG** [comment]
ci:stop

**Comment by JhossephG** [comment]
ci:forward:force

**Comment by JhossephG** [comment]
Hey folks, the modules didn't even get to run on the CI (internal issues, I believe). Just to be safe, I'll trigger another baseline run, update the PR and the branch name to the LRAC, and set it to run once more.

**Comment by JhossephG** [comment]
The module was already updated to the most recently version in master and the versioning test it's passing on CI!

**Pull request closed without merging**
