### PR TITLE
LPD-15983 | master

### PR DESCRIPTION
**Pull request by fmarcio**
https://liferay.atlassian.net/browse/LPD-15983

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:analytics-cloud-acceptance

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @fmarcio

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:forward:force

**Pull request closed without merging**
