### PR TITLE
LRAC-15249 | master

### PR DESCRIPTION
**Pull request by lesliewong92**
https://liferay.atlassian.net/browse/LRAC-15249

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:test:startup

**Comment by lesliewong92** [comment]
ci:test:upgrade

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
