### PR TITLE
AC Test Fix - LCD-38204 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LCD-38204
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2571503912&testrayRunId=2571503916)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
Good work @ViniLopes20 :tada:

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud

**Pull request closed without merging**
