### PR TITLE
AC Test Fix -  LRAC-11474 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11474

### CODE REVIEW

**Review by calvinctvo — APPROVED** [review]
Hey @joshitagaki thank you for the fix! LGTM

**Review by christianstokes — APPROVED** [review]
Looks good. Approved.

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks Josh!

**Comment by manuferreira** [comment]
ci:foward

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
