### PR TITLE
LPD-37551 Add Playwright test | master

### PR DESCRIPTION
**Pull request by lesliewong92**
https://liferay.atlassian.net/browse/LPD-37551

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward

**Comment by lesliewong92** [comment]
ci:test:playwright

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:test:playwright

**Comment by interaminense** [comment]
Hi @lesliewong92, you can run `ci:test:analytics-cloud-acceptance` to avoid running all Playwright tests.

**Comment by lesliewong92** [comment]
Ah, thanks @interaminense!

**Comment by lesliewong92** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
The failure is on upstream, would you like to move it forward?

**Comment by lesliewong92** [comment]
ci:forward

**Pull request closed without merging**
