### PR TITLE
LPD-36870 | Test Fix | Poshi >>> Playwright

### PR DESCRIPTION
**Pull request by rafaellajordao**
### Motivation:
Test failing due to Poshi limitations.

### Proposed Solution:
Transcribe test to playwright in order to facilitate maintenance.

**More details:** [LPD-36870](https://liferay.atlassian.net/browse/LPD-36870)

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:analytics-cloud

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @rafaellajordao

**Comment by rafaellajordao** [comment]
ci:forward

**Pull request closed without merging**
