### PR TITLE
AC Test fix - LRAC-13145 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-13145

### CODE REVIEW

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks Josh 🎉 😄

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for noticing that! :tada:

**Review by calvinctvo — APPROVED** [review]
Thanks for the fix Josh! LGTM

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
