### PR TITLE
LPD-23024 | master

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LPD-23024

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:analytics-cloud-acceptance

**Review by interaminense — APPROVED** [review]
LGTM! @fmarcio @marcosapmf

**Comment by fmarcio** [comment]
ci:forward

**Comment by fmarcio** [comment]
ci:stop

**Comment by fmarcio** [comment]
ci:forward

**Pull request closed without merging**
