### PR TITLE
LRAC-14784 | master

### PR DESCRIPTION
**Pull request by riccardo-ferrari**

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @riccardo-ferrari, the failure of `acceptance` is related to this [bug](https://issues.liferay.com/browse/LRAC-13481). The PR looks good to be forwarded. Thanks!

**Comment by marcellustavares** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/781

**Pull request closed without merging**
