### PR TITLE
AC Test Fix - LRAC-14861 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14861

**Context:**
Some segment tests are failing because individuals take a long time to appear to be added to the static segment.

**Solution:**
I analyzed some of these cases and observed that some tests have objectives like validating the deletion, pagination, and ordering of the list of segments, so it is not important for the test objective if the segment is dynamic or static and also if it has added members or not.

I will modify these tests so that they do not check if the segment has already processed the data or use a dynamic segment instead of the static segment to avoid the individual problem.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Great idea changing it to use dynamic segment instead. LGTM!

**Review by nkkwon — APPROVED** [review]
LGTM! Thanks for the fix! :+1:

**Review by manuferreira — APPROVED** [review]
Hey Vini, thank you. I think we need to do more of what you did here, adapting some failing tests when necessary. :muscle: :detective:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
