### PR TITLE
AC Test Fix - LRAC-14508 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14508

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by nkkwon — APPROVED** [review]
LGTM! :+1:

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks Josh 🎉

**Review by manuferreira — APPROVED** [review]
LGTM! Thank you very much :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
