### PR TITLE
LPD-20144 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LPD-20144

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by rachaelkoestartyo** [comment]
merged with https://github.com/liferay-ac/liferay-portal/pull/1259

**Pull request closed without merging**
