### PR TITLE
LRAC-13976 - Follow up

### PR DESCRIPTION
**Pull request by ilzamcmed**
Update snapshots related to this jira issue: https://issues.liferay.com/browse/LRAC-13976

### CODE REVIEW

**Comment by ilzamcmed** [comment]
## :fire: GitRay Report 
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
 ## Jira Tasks 

 <html></html> 

---

Hey, don't forget to update all related tickets with correct status, such as **In Review** :wink: 
### Git Stats 

6 files changed, 46 insertions(+), 30 deletions(-)

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:stop

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by JLucasM — APPROVED** [review]
LGTM!

**Comment by ViniLopes20** [comment]
ci:test:stable

**Pull request closed without merging**
