### PR TITLE
LRAC-14455 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-14455

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:forward:force

**Comment by rachaelkoestartyo** [comment]
ci:forward:force

**Comment by rachaelkoestartyo** [comment]
ci:forward:force

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
