### PR TITLE
LPD-21786 | Master

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://issues.liferay.com/browse/LPD-21786

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Pull request closed without merging**
