### PR TITLE
AC Test Improvement - LRAC-11698 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11698

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
Nice, thank you Vini :male_detective:

**Review by joshitagaki — APPROVED** [review]
Thanks for making these changes! LGTM

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1377401_4273

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1277401_4518

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1297401_4120

**Review by calvinctvo — APPROVED** [review]
Thank you @ViniLopes20 for updating our upstream

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1297401_4122

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1297401_4140

**Comment by christianstokes** [comment]
Seems we are having some issues with this PR? Let us know if we can help @michaelhashimoto, thanks!

**Comment by michaelhashimoto** [comment]
ci:test:relevant

@christianstokes - Thanks, I think this is related to all the PR Tester instability that we are trying to fix as mentioned here:
https://liferay.slack.com/archives/C19PWQ74J/p1660264553139289?thread_ts=1660264373.646359&cid=C19PWQ74J

I talked with @ViniLopes20, and we are going to add `test.properties` as a bypass for pull request tester.

Here's the pull for this update:
https://github.com/michaelhashimoto/liferay-portal/pull/2396

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Pull request closed without merging**
