### PR TITLE
Enable Test LRAC-13575 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
Bug: https://liferay.atlassian.net/browse/LRAC-13575

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
