### PR TITLE
LRAC-0 Fixes

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
