### PR TITLE
LPS-199879 Remove dependency

### PR DESCRIPTION
**Pull request by sandrodw3**
Hi guys! I'm sending this one removing `metal-uri` usages from `osb-faro-web`. I'll be sending more PRs this week removing the rest of metal plugins remaining in the module 😄

Here is the Jira ticket: https://liferay.atlassian.net/browse/LPS-199326.

Please let me know what you think, thanks!

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @sandrodw3, The acceptance tests are failing because after their modifications it was not possible to create the Faro image locally. Could you fix this?

cc: @interaminense

**[Erro:](https://testray.liferay.com/reports/production/logs/2023-12/test-1-39/test-portal-acceptance-pullrequest(master)/8793/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)**
`[exec] > Task :dxp:apps:osb:osb-faro:osb-faro-web:packageRunWebpack
     [exec] yarn run v1.22.19
     [exec] $ webpack --config webpack.prod.js
     [exec] Hash: 47f6ee22336c216166bf
     [exec] Version: webpack 4.43.0
     [exec] Time: 95236ms
     [exec] Built at: 12/20/2023 4:28:28 AM
     [exec]  136 assets
     [exec] Entrypoint main = main.css main.js
     [exec]   [2] ./src/main/js/shared/util/constants.ts 17.2 KiB {126} [built]
     [exec]   [8] ./src/main/js/shared/util/router.ts 22.3 KiB {126} [built]
     [exec]  [31] ./src/main/js/shared/actions/modals.ts 714 bytes {126} [built]
     [exec]  [35] ../node_modules/react-redux/es/index.js + 28 modules 49 KiB {126} [built]
     [exec]       |    29 modules
     [exec]  [38] ../node_modules/react-router-dom/esm/react-router-dom.js + 3 modules 11 KiB {126} [built]
     [exec]       |    4 modules
     [exec]  [78] ./src/main/js/shared/util/react.ts 824 bytes {126} [built]
     [exec]  [80] ./src/main/js/shared/context/channel.tsx 1.76 KiB {126} [built]
     [exec]  [99] ./src/main/js/shared/pages/ErrorPage.tsx 1.02 KiB {126} [built]
     [exec] [117] ./src/main/js/route-middleware/BundleRouter.jsx 2.24 KiB {126} [built]
     [exec] [134] ./src/main/js/shared/context/unassignedSegments.tsx 2.39 KiB {126} [built]
     [exec] [148] ./src/main/js/shared/apollo/client.js + 10 modules 33 KiB {126} [built]
     [exec]       | ./src/main/js/shared/apollo/client.js 1.76 KiB [built]
     [exec]       | ./src/main/js/shared/apollo/cache.js 91 bytes [built]
     [exec]       | ./src/main/js/shared/apollo/resolvers/resolvers.ts 1.24 KiB [built]
     [exec]       | ./src/main/js/shared/apollo/resolvers/CommerceAverageOrderValueResolver.js 885 bytes [built]
     [exec]       | ./src/main/js/shared/apollo/resolvers/CommerceAverageRevenuePerAccountResolver.js 885 bytes [built]
     [exec]       | ./src/main/js/shared/apollo/resolvers/CommerceIncompleteOrdersResolver.js 903 bytes [built]
     [exec]       | ./src/main/js/shared/apollo/resolvers/CommerceTotalOrderValueResolver.js 873 bytes [built]
     [exec]       | ./src/main/js/shared/apollo/resolvers/CustomAssetsListResolver.js 399 bytes [built]
     [exec]       | ./src/main/js/shared/apollo/resolvers/EventAnalysisListResolver.js 886 bytes [built]
     [exec]       | ./src/main/js/shared/apollo/resolvers/ExperimentResolver.js 23.4 KiB [built]
     [exec]       | ./src/main/js/shared/apollo/resolvers/PagePathResolver.js 1.81 KiB [built]
     [exec] [522] multi core-js/fn/array/fill core-js/fn/string/code-point-at core-js/fn/typed custom-event-polyfill unorm whatwg-fetch ./src/main/js/main.jsx 100 bytes {126} [built]
     [exec] [561] ./src/main/css/main.scss 39 bytes {126} [built]
     [exec] [563] ./src/main/js/external-scripts.js 4.98 KiB {126} [built]
     [exec] [850] ./src/main/js/main.jsx + 5 modules 22.9 KiB {126} [built]
     [exec]       | ./src/main/js/main.jsx 227 bytes [built]
     [exec]       | ./src/main/js/App.jsx 14.4 KiB [built]
     [exec]       | ./src/main/js/shared/store/index.ts 295 bytes [built]
     [exec]       | ./src/main/js/shared/context/oAuthUpgradeWarning.tsx 94 bytes [built]
     [exec]       |     + 2 hidden modules
     [exec]     + 3098 hidden modules
     [exec] 
     [exec] ERROR in src/main/js/shared/util/router.ts:9:3
     [exec] prettier/prettier: Replace `���������` with `��`
     [exec]      7 | 	try {
     [exec]      8 | 		return new URL(href);
     [exec]   >  9 | 	}
     [exec]        | 	 ^
     [exec]   > 10 |
     [exec]        | ^
     [exec]   > 11 | 	catch {
     [exec]        | ^^
     [exec]     12 | 		return new URL(href, document.baseURI)
     [exec]     13 | 	}
     [exec]     14 | }
     [exec] 
     [exec] ERROR in src/main/js/shared/util/router.ts:12:41
     [exec] prettier/prettier: Insert `;`
     [exec]     10 |
     [exec]     11 | 	catch {
     [exec]   > 12 | 		return new URL(href, document.baseURI)
     [exec]        | 		                                      ^
     [exec]     13 | 	}
     [exec]     14 | }
     [exec]     15 |
     [exec] 
     [exec] ERROR in src/main/js/shared/util/router.ts:486:28
     [exec] prettier/prettier: Insert `;`
     [exec]     484 | 	const uri = createURL(href);
     [exec]     485 |
     [exec]   > 486 | 	addParam(uri, name, value)
     [exec]         | 	                          ^
     [exec]     487 |
     [exec]     488 | 	return `${uri.pathname}${uri.search}`;
     [exec]     489 | }
     [exec] 
     [exec] ERROR in src/main/js/shared/util/router.ts:517:29
     [exec] prettier/prettier: Insert `;`
     [exec]     515 |
     [exec]     516 | export function removePageParam(newPath, href = window.location.href) {
     [exec]   > 517 | 	const uri = createURL(href)
     [exec]         | 	                           ^
     [exec]     518 |
     [exec]     519 | 	if (newPath) {
     [exec]     520 | 		uri.pathname = newPath;
     [exec] 
     [exec] ERROR in src/main/js/shared/util/router.ts:528:39
     [exec] prettier/prettier: Replace `������newPath,������href��=��window.location.href���` with `newPath,��href��=��window.location.href`
     [exec]     526 | }
     [exec]     527 |
     [exec]   > 528 | export function resetPaginationParams(
     [exec]         |                                       ^
     [exec]   > 529 | 	newPath,
     [exec]         | ^^^^^^^^^
     [exec]   > 530 | 	href = window.location.href
     [exec]         | ^^^^^^^^^
     [exec]   > 531 | ) {
     [exec]         | ^
     [exec]     532 | 	const uri = createURL(href);
     [exec]     533 |
     [exec]     534 | 	if (newPath) {
     [exec] Child mini-css-extract-plugin ../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/postcss-loader/lib/index.js??postcss!../node_modules/sass-loader/lib/loader.js??ref--6-3!src/main/css/main.scss:
     [exec]     Entrypoint mini-css-extract-plugin = *
     [exec]     [0] ../node_modules/css-loader/dist/cjs.js??ref--6-1!../node_modules/postcss-loader/lib??postcss!../node_modules/sass-loader/lib/loader.js??ref--6-3!./src/main/css/main.scss 1010 KiB {0} [built]
     [exec]         + 1 hidden module
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] error Command failed with exit code 2.
     [exec] 
     [exec] > Task :dxp:apps:osb:osb-faro:osb-faro-web:packageRunWebpack FAILED
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':dxp:apps:osb:osb-faro:osb-faro-web:packageRunWebpack'.
     [exec] > Process 'command '/opt/dev/projects/github/liferay-portal/modules/dxp/apps/osb/osb-faro/osb-faro-web/build/node/bin/node'' finished with non-zero exit value 2`

**Comment by interaminense** [comment]
It is an SF error, I'm running the source format locally to fix that.

**Comment by interaminense** [comment]
Resent https://github.com/liferay-ac/liferay-portal/pull/961

**Pull request closed without merging**
