### PR TITLE
AC Improvements Test - LRAC-11597 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11597
https://issues.liferay.com/browse/LRAC-11497 (Bug)
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1935068924&testrayRunId=1935068987)

Update the test to add the URL attribute in the breakdown. If the formatting breaks again this test will indicate this bug since the assert it makes in the test is an `AssertElementPresent`, if the formatting is broken it will not be able to validate the value on the screen.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM, thanks Vini :detective:

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks @ViniLopes20

**Review by christianstokes — APPROVED** [review]
Nice, good, simple idea for an improvement. I like it.

**Comment by christianstokes** [comment]
ci:forward

**Comment by christianstokes** [comment]
Oh yeah looks like CI is having issues. We will have to forward it later :(

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
