### PR TITLE
AC Automated Test - All tests from the LRAC-11306 group | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10999 (Story)
[Test Plan](https://docs.google.com/document/d/12d5UkNdzZZkZZYseZYPEisXGAuWWwpTEUA-qzQ7_2Ko/edit#heading=h.4cvkk079wqez)
https://issues.liferay.com/browse/LRAC-11307 (Automation ticket)
https://issues.liferay.com/browse/LRAC-11308 (Automation ticket)
https://issues.liferay.com/browse/LRAC-11309 (Automation ticket)
https://issues.liferay.com/browse/LRAC-11310 (Automation ticket)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by christianstokes — APPROVED** [review]
These tests look very good, thank you @ViniLopes20.

It's really nice to see tests for this story, amazing work.

**Review by joshitagaki — APPROVED** [review]
Great work Vini! I'll be able to use your macro to clear local storage in: https://issues.liferay.com/browse/LRAC-11316. Hopefully it'll fix some more tests

**Review by calvinctvo — APPROVED** [review]
Great work @ViniLopes20 🎉 Thank you for working on these tests

**Review by manuferreira — APPROVED** [review]
LGTM, very nice Vini :policeman: :tada:

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
