### PR TITLE
LPS-164566

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
Hey guys, the analytics-client-js unit tests are failing. I'll investigate that.

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
