### PR TITLE
LRAC-12600 - [F] Fix spacing between checkbox and table columns

### PR DESCRIPTION
**Pull request by ilzamcmed**
https://issues.liferay.com/browse/LRAC-12600

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Pull request closed without merging**
