### PR TITLE
AC Test Improvement - LRAC-12832 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-12832

ℹ️ **Reason for Change:**
All customer workspaces are still using ES on AC. Only Liferay's workspace is using BQ. We are currently validating the regression using a workspace with BQ and we don't know how things are working for the customers as they are still using ES. So we must make our tests run with ES so that we can have a general result of the operation of ES by automation.

- When the variable has the value `true`, the AC will use Postgres:
`OSB_ASAH_POSTGRESQL_ENABLED=true`

- When the variable has the value `false`, the AC will use Elasticsearch:
`OSB_ASAH_POSTGRESQL_ENABLED=false`

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you!! :muscle:

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! Yea I agree it makes more sense to run our tests using ES.

**Review by calvinctvo — APPROVED** [review]
I agree! Thanks for enable ES Vini!

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
