### PR TITLE
LRAC-12613 - [BUG] Not selectable item on channel tab are not displayed disabled

### PR DESCRIPTION
**Pull request by ilzamcmed**
https://issues.liferay.com/browse/LRAC-12613

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @ilzamcmed !

**Review by JLucasM — APPROVED** [review]
LGTM!

**Comment by ilzamcmed** [comment]
ci:forward

**Pull request closed without merging**
