### PR TITLE
LRAC-12806 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:stable

**Comment by joshitagaki** [comment]
Stable error: 
```
[junit] Portal log assert failure, see above log for more information: 
    [junit] Declarative Service Unsatisfied Component System Checker check result: 
    [junit] Bundle {id: 1474, name: com.liferay.analytics.settings.web, version: 5.0.66}
    [junit] 	Declarative Service {id: 11647, name: com.liferay.analytics.settings.web.internal.portal.settings.configuration.admin.display.AnalyticsSyncedSitesConfigurationScreen, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11652, name: com.liferay.analytics.settings.web.internal.portlet.action.EditChannelMVCRenderCommand, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11654, name: com.liferay.analytics.settings.web.internal.portlet.action.EditSyncedContactsGroupsMVCRenderCommand, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11646, name: com.liferay.analytics.settings.web.internal.portal.settings.configuration.admin.display.AnalyticsSyncedContactsDataConfigurationScreen, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11657, name: com.liferay.analytics.settings.web.internal.portlet.action.EditSyncedContactsOrganizationsMVCRenderCommand, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11653, name: com.liferay.analytics.settings.web.internal.portlet.action.EditSyncedContactsFieldsMVCRenderCommand, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11645, name: com.liferay.analytics.settings.web.internal.portal.settings.configuration.admin.display.AnalyticsCloudConnectionConfigurationScreen, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11656, name: com.liferay.analytics.settings.web.internal.portlet.action.EditSyncedContactsMVCRenderCommand, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11650, name: com.liferay.analytics.settings.web.internal.portlet.action.AddChannelMVCRenderCommand, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11648, name: com.liferay.analytics.settings.web.internal.portal.settings.configuration.admin.display.AnalyticsWorkspaceConnectionConfigurationScreen, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] junit.framework.AssertionFailedError: 
    [junit] Declarative Service Unsatisfied Component System Checker check result: 
    [junit] Bundle {id: 1474, name: com.liferay.analytics.settings.web, version: 5.0.66}
    [junit] 	Declarative Service {id: 11647, name: com.liferay.analytics.settings.web.internal.portal.settings.configuration.admin.display.AnalyticsSyncedSitesConfigurationScreen, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11652, name: com.liferay.analytics.settings.web.internal.portlet.action.EditChannelMVCRenderCommand, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11654, name: com.liferay.analytics.settings.web.internal.portlet.action.EditSyncedContactsGroupsMVCRenderCommand, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11646, name: com.liferay.analytics.settings.web.internal.portal.settings.configuration.admin.display.AnalyticsSyncedContactsDataConfigurationScreen, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11657, name: com.liferay.analytics.settings.web.internal.portlet.action.EditSyncedContactsOrganizationsMVCRenderCommand, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11653, name: com.liferay.analytics.settings.web.internal.portlet.action.EditSyncedContactsFieldsMVCRenderCommand, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11645, name: com.liferay.analytics.settings.web.internal.portal.settings.configuration.admin.display.AnalyticsCloudConnectionConfigurationScreen, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11656, name: com.liferay.analytics.settings.web.internal.portlet.action.EditSyncedContactsMVCRenderCommand, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11650, name: com.liferay.analytics.settings.web.internal.portlet.action.AddChannelMVCRenderCommand, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	Declarative Service {id: 11648, name: com.liferay.analytics.settings.web.internal.portal.settings.configuration.admin.display.AnalyticsWorkspaceConnectionConfigurationScreen, unsatisfied references: 
    [junit] 		{name: analyticsUsersManager, target: null}
    [junit] 	}
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.scanXMLLogFile(PortalLogAssertorTest.java:162)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:89)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest$1.visitFile(PortalLogAssertorTest.java:79)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2670)
    [junit] 	at java.nio.file.Files.walkFileTree(Files.java:2742)
    [junit] 	at com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog(PortalLogAssertorTest.java:77)
```

**Comment by rachaelkoestartyo** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
ci:forward

**Comment by rachaelkoestartyo** [comment]
ci:reevaluate:1257401_4131

**Comment by rachaelkoestartyo** [comment]
ci:forward

**Comment by rachaelkoestartyo** [comment]
ci:forward:force

**Pull request closed without merging**
