### PR TITLE
AC Test Fix - LRAC-14516 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14516

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for the fix!! :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
