### PR TITLE
AC Test fix LRAC-14510 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14510

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks Josh 🎉

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
