### PR TITLE
LPD-29379 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-29379

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM 🎉

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
