### PR TITLE
AC Test fix - LRAC-13908 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-13908
Missed a createDate in last PR.

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks Josh 🎉

**Review by manuferreira — APPROVED** [review]
LGTM! Thank you :tada:

**Review by nkkwon — APPROVED** [review]
LGTM! :+1:

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
