### PR TITLE
LRAC-12806

### PR DESCRIPTION
**Pull request by ivicac**
- LRAC-12806 move validateConnection
- LRAC-12806 update
- LRAC-12806 remove analytics-message-sender-api and impl
- LRAC-12806 remove AnalyticsMessage table, model, services
- LRAC-12806 remove EntityModelListenerRegistry
- LRAC-12806 clean up
- LRAC-12806 drop AnalyticsMessage table
- LRAC-12806 remove feature flag in portal.properties
- LRAC-12806 remove feature flag
- LRAC-12806 fix
- LRAC-12806 baseline

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @ivicac, I put an `on hold` tag in the PR, we will validate the changes before forwarding this PR. After we verify and everything is working in 7.4 then we can forward the PR to bchan. Thanks

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
@ViniLopes20, could you please check this PR? It is constantly failing test:relevant

**Comment by ViniLopes20** [comment]
Hey @ivicac, I finished the [analysis](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2371784571) of the `relevant` results and the errors are not related to your PR. They are occurring for other PRs as well. So after the QA team validates that the batch sync is working, we can forward this PR. You can follow it [here](https://liferay.atlassian.net/browse/LRAC-13019)

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
i'll rebase and resend with more fixes

**Pull request closed without merging**
