### PR TITLE
LRAC-14049 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**
Jira ticket: https://issues.liferay.com/browse/LRAC-14049

### CODE REVIEW

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
resent https://github.com/liferay-ac/liferay-portal/pull/522

**Comment by marcosapmf** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
