### PR TITLE
LRAC-12475 [BUG] Unable to sort channel tab by Related Site if you have more than one channel in the list

### PR DESCRIPTION
**Pull request by JLucasM**
LRAC-12475: [Jira Issue](https://issues.liferay.com/browse/LRAC-12475)

### CODE REVIEW

**Review by ilzamcmed — APPROVED** [review]
LGTM! :rocket:

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by JLucasM** [comment]
> 

Thanks @interaminense, I did it now.

**Comment by interaminense** [comment]
ci:forward

**Review by interaminense — APPROVED** [review]
LGTM!

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Pull request closed without merging**
