### PR TITLE
LRAC-13976 - A little dot appears when the card of individual activities is loading

### PR DESCRIPTION
**Pull request by ilzamcmed**
Jira issue: https://issues.liferay.com/browse/LRAC-13976

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @ilzamcmed

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by ViniLopes20** [comment]
Hey @ilzamcmed, Could you update your `master` branch and rebase again with the branch you are using here and then do a force push? The CI found some conflicts on this PR


`Unable to rebase master-temp-1686671153027 to master
Rebasing (1/2)
error: could not apply 551852d30da4... LRAC-13976 - Add class to fix loading position
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 551852d30da4... LRAC-13976 - Add class to fix loading position`

**Comment by ilzamcmed** [comment]
Thanks @ViniLopes20
I am working to fix on conflicts, it was related to https://github.com/liferay-ac/liferay-portal/pull/496

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:forward

**Pull request closed without merging**
