### PR TITLE
AC Test Fix - LRAC-14615 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14615

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Thanks Josh, enjoy your vacations. LGTM 🎉

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for working on it! :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
