### PR TITLE
LRAC-15322 Uncaught ReferenceError: Analytics is not defined when rendering DPT

### PR DESCRIPTION
**Pull request by Mikellorza**
Fix two bugs:

1. https://liferay.atlassian.net/browse/LRAC-15322
2. https://liferay.atlassian.net/browse/LRAC-15321

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:analytics-cloud-acceptance

**Comment by joshitagaki** [comment]
ci:test:relevant

**Review by rachaelkoestartyo — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:forward:force

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
