### PR TITLE
AC Delete Automated Tests - LRAC-12887 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-12887

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks Vini!

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks :tada:

**Review by calvinctvo — APPROVED** [review]
Thanks @ViniLopes20 for deleting the tests! LGTM

**Comment by calvinctvo** [comment]
ci:forward

**Comment by calvinctvo** [comment]
ci:forward:force

**Comment by calvinctvo** [comment]
ci:forward:force

**Pull request closed without merging**
