### PR TITLE
LRAC-13926 | master

### PR DESCRIPTION
**Pull request by ilzamcmed**
Jira issue: https://issues.liferay.com/browse/LRAC-13926
Jira issue: https://issues.liferay.com/browse/LRAC-13927

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
