### PR TITLE
LRAC-14169 follow up

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LRAC-14169

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @fmarcio

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by fmarcio** [comment]
ci:forward

**Pull request closed without merging**
