### PR TITLE
LRAC-15023 and LRAC-15024

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issues: https://issues.liferay.com/browse/LRAC-15023, https://issues.liferay.com/browse/LRAC-15023

### CODE REVIEW

**Comment by interaminense** [comment]
ci:forward

**Comment by marcellustavares** [comment]
ci:stop

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
