### PR TITLE
AC Test fix - LRAC-11543 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11543
Test fails on CI run due to it running on upstream as well. This should fix the issue as well as only run on release branch.
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1917704388&testrayRunId=1917705163)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM. Thanks for it, Josh 🎉

**Review by manuferreira — APPROVED** [review]
LGTM, thanks Josh :tada:

**Review by christianstokes — APPROVED** [review]
LGTM thanks Josh!

**Review by calvinctvo — APPROVED** [review]
Thanks @joshitagaki ! LGTM

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
