### PR TITLE
AC Test fix - LRAC-11605 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11605
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1937236975)

Explanation for the changes:
Removed `JSONUser.tearDownNonAdminUsers();` because the `PortalInstances.tearDownCP();` would already run that macro. 
Moving the `ACUtils.tearDownAC();` helped with any issues during teardown of DXP. Ex: There are times when it fails to find the companyid during the teardown step.
Fixed delete properties teardown macro to only teardown all properties if the select all checkbox is present. Certain tests did not have any properties causing it to fail.

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by christianstokes — APPROVED** [review]
Thank you for working on this @joshitagaki. Approved.

**Review by ViniLopes20 — APPROVED** [review]
Great job, thank you so much for investigating this issue for us, Josh 🎉

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
