### PR TITLE
AC Test Fix - LRAC-14726 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14726

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks for updating it 🎉

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you! :detective:

**Review by nkkwon — APPROVED** [review]
LGTM!

**Comment by nkkwon** [comment]
ci:forward

**Pull request closed without merging**
