### PR TITLE
LRAC-15206 | master

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:stable

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @marcellustavares, acceptance tests are failing for your PR. I looked in the log and I think there is a problem starting Faro. You can look at [Faro's log here](https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/8935/functional-tomcat90-mysql57-jdk8/0/2/docker-logs/faro.1.log). Could you check the errors that are appearing?

**Comment by marcellustavares** [comment]
why test:sf is failing @ViniLopes20? I can't get passed it

**Comment by ViniLopes20** [comment]
> why test:sf is failing @ViniLopes20? I can't get passed it

Hey @marcellustavares, related to the SF issue. The error that appears in the `ci:test:sf` log is not related to your changes. Could you try to follow these steps and force the push again for this PR?

**Steps:**
1. Go to liferay-portal
2. Update the `master` branch
3. Go to your branch and rebase with the `master`
4. Run `ant setup-sdk`
5. Go to `portal-impl` > Run `ant format-source-current-branch`

**Comment by marcellustavares** [comment]
https://github.com/liferay-ac/liferay-portal/pull/919

**Pull request closed without merging**
