### PR TITLE
[F] LRAC-13326 follow up

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://issues.liferay.com/browse/LRAC-13326

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
The SF test logs https://github.com/liferay-ac/liferay-portal/pull/390#issuecomment-1531582310 says the SF task was not executed because there were no modified files, which makes sense because this PR only deletes some files.
If SF only runs if there's modifications, what should we do? Just forward?

**Comment by interaminense** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:forward

**Pull request closed without merging**
