### PR TITLE
AC Test Fix - LRAC-11583 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRAC-11583 (Test fix ticket)
Cannot run on Testray due to: [LRAC-11653](https://issues.liferay.com/browse/LRAC-11653)

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Thank you very much for this correction, Calvin. Hope the test can pass after this 🎉

**Review by manuferreira — APPROVED** [review]
LGTM, thanks Calvin :tada: :sparkle:

**Review by joshitagaki — APPROVED** [review]
Hope to see this test pass! LGTM!

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
