### PR TITLE
LRAC-12196 People Step

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issues:

[LRAC-11981](https://issues.liferay.com/browse/LRAC-11981),
[LRAC-11904](https://issues.liferay.com/browse/LRAC-11904),
[LRAC-12185](https://issues.liferay.com/browse/LRAC-12185),
[LRAC-12196](https://issues.liferay.com/browse/LRAC-12196),
[LRAC-12197](https://issues.liferay.com/browse/LRAC-12197),
[LRAC-12198](https://issues.liferay.com/browse/LRAC-12198),
[LRAC-12202](https://issues.liferay.com/browse/LRAC-12202),
[LRAC-12196](https://issues.liferay.com/browse/LRAC-12196)

### CODE REVIEW

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
After several tentatives to move forward, I send a PR directly to Brian's repo https://github.com/brianchandotcom/liferay-portal/pull/126119

**Comment by interaminense** [comment]
Resent https://github.com/liferay-ac/liferay-portal/pull/164

**Pull request closed without merging**
