### PR TITLE
[F] LRAC-15364 Fix Download Report modal year range issue on DataPicker component

### PR DESCRIPTION
**Pull request by fmarcio**
https://liferay.atlassian.net/browse/LRAC-15364

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:reopen

**Comment by fmarcio** [comment]
ci:reopen

**Comment by interaminense** [comment]
It's already fixed on 4.6.x branch, so I'll close it.

**Pull request closed without merging**
