### PR TITLE
LRAC-12687 - [F] Create unit tests for utils/request.ts

### PR DESCRIPTION
**Pull request by ilzamcmed**
https://issues.liferay.com/browse/LRAC-12687

### CODE REVIEW

**Comment by ilzamcmed** [comment]
Hey @interaminense @fmarcio and @JLucasM 
The tests passed but I was getting this console error:
Screenshot_20230112_094922

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by JLucasM — APPROVED** [review]
LGTM!

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
