### PR TITLE
AC Test Fix - LRAC-12039 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRAC-12039 (Test Fix)
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2013285024)

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Nice fix, Calvin. Thanks for it, LGTM 🎉

**Review by joshitagaki — APPROVED** [review]
Thanks Calvin! LGTM!

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks Calvin :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
