### PR TITLE
AC Automated Test - LRAC-11475 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11475 (Automation Ticket)
https://issues.liferay.com/browse/LRAC-11423 (Bug)
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1903269288&testrayRunId=1903276863)

### CODE REVIEW

**Review by joshitagaki — APPROVED** [review]
Thanks @ViniLopes20! LGTM!

**Review by calvinctvo — APPROVED** [review]
Hey @ViniLopes20 ! Thanks for working on this, LGTM

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
