### PR TITLE
[BACKPORT] [F] LRAC-14054

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LRAC-14054

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
This SF issue is happening in others PRs too. It started after JIRA migration

**Comment by ViniLopes20** [comment]
Hey @fmarcio, one test is failing your `relevant` but checking the history and they always fail for other PRs too. It should not be related to your modifications. I would say you could follow the PR after the `stable` is passing

Test:
- [PortalLogAssertorTest-functional-smoke-tomcat90-db2115-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2354801435?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2354801299%26testrayRunId%3D2354801428%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by fmarcio** [comment]
So, should I wait the SF fix and then forward it? cc @interaminense @ViniLopes20

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:forward

**Pull request closed without merging**
