### PR TITLE
LRAC-12470 set min length when creating a new property

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://issues.liferay.com/browse/LRAC-12470

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:sf

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:stable

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:stable

**Comment by fmarcio** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Review by ilzamcmed — APPROVED** [review]
LGTM :rocket:

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Review by JLucasM — APPROVED** [review]
LGTM!

**Comment by fmarcio** [comment]
ci:test:stable

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:forward

**Pull request closed without merging**
