### PR TITLE
LRAC-15333 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://liferay.atlassian.net/browse/LRAC-15333
https://liferay.atlassian.net/browse/LRAC-15334

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
Fixing rebase issues and resent to https://github.com/liferay-ac/liferay-portal/pull/1029

**Pull request closed without merging**
