### PR TITLE
LPD-29843 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-29843

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
LGTM! thanks @marcosapmf :rocket:

**Comment by marcosapmf** [comment]
ci:forward

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
blocked by https://github.com/liferay-frontend/liferay-portal/pull/4340

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
The source format issues are not related to this PR. Forwarding manually to https://github.com/brianchandotcom/liferay-portal/pull/152699

**Pull request closed without merging**
