### PR TITLE
AC Convert Test - LPD-32222, LPD-32223 and LPD-32220 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LPD-32222
https://liferay.atlassian.net/browse/LPD-32223
https://liferay.atlassian.net/browse/LPD-32220
[Testray](https://testray.liferay.com/#/project/34880/routines/730294/build/45667438)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by marcosapmf — APPROVED** [review]

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
