### PR TITLE
AC Test Improvements - LRAC-14289 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14289

On hold waiting for tickets:
https://liferay.atlassian.net/browse/LRAC-14273
https://liferay.atlassian.net/browse/LRAC-14286

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM! Thank you :detective:

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
