### PR TITLE
AC Test Fix - LRAC-12302 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-12302

I ran this a couple times on CI and this seems to have fixed the issue of the error. It was due to some timing issues when trying to click on connect that was causing some tests to sometimes fail.

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good @joshitagaki, I hope this problem doesn't come back to disturb us hahaha. LGTM 🎉 

**PS:** Could you make this modification in this [PR](https://github.com/liferay-ac/liferay-portal/pull/262) too? I modified the name of this path to _CONNECT_BUTTON_DISABLED_ in the PR

**Review by manuferreira — APPROVED** [review]
Thank you Josh, nice solution :muscle:

**Review by calvinctvo — APPROVED** [review]
Thanks Josh for the fix!

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
