### PR TITLE
LRAC-14385 Create unit test

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://liferay.atlassian.net/browse/LRAC-14385

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:stop

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward:force

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
