### PR TITLE
AC Test Fix - LRAC-14548 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14548

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Good job, Josh. LGTM 🎉

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for the investigation! :detective:

**Review by nkkwon — APPROVED** [review]
Thanks for the fix!

**Comment by nkkwon** [comment]
ci:forward

**Pull request closed without merging**
