### PR TITLE
LPD-33302 | Master

### PR DESCRIPTION
**Pull request by interaminense**
Changes on this PR:

1. Create a new CSS to import Source Sans Pro fonts locally instead of Google Fonts
2. Based on this URL to import fonts https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700|Source+Serif+Pro

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
