### PR TITLE
LPD-25251 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-25251

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:core-functional

**Comment by vicnate5** [comment]
ci:report:2566637593

**Comment by marcosapmf** [comment]
Hi @vicnate5,
It looks like the failures in `ci:test:core-functional` are not related to the changes in this pull.
So if you agree, I can forward it

Thanks

**Comment by vicnate5** [comment]
@marcosapmf The failures are not related. You can forward.

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
