### PR TITLE
LRAC-15206 | master

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
@marcosapmf could you please help me out here? I’ve tried many different things but I can’t get passed SF check.

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/921

**Pull request closed without merging**
