### PR TITLE
LRAC-13968 sort NULLS last

### PR DESCRIPTION
**Pull request by sillascavalcanti**

### CODE REVIEW

**Comment by sillascavalcanti** [comment]
ci:test:sf

**Comment by sillascavalcanti** [comment]
ci:test:sf

**Comment by sillascavalcanti** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @sillascavalcanti, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by interaminense** [comment]
@marcellustavares could you review it?

**Comment by marcellustavares** [comment]
LGTM

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by marcellustavares** [comment]
Thanks @sillascavalcanti!

**Pull request closed without merging**
