### PR TITLE
AC Refactor - LRAC-11814 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11814

Wanted to start with some smaller changes that we can handle at this point. AC launch and token connection are the places I thought would be easiest to replace. Looking into other places but it would require more work.

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks for the refactor Josh 🎉

Hey @joshitagaki, I think we can remove these macros related to the connection if the Tango team agrees as they won't be used anymore.

**Comment by joshitagaki** [comment]
> LGTM, thanks for the refactor Josh tada
> 
> Hey @joshitagaki, I think we can remove these macros related to the connection if the Tango team agrees as they won't be used anymore.

Ahh yea good point. I'll look into some of the macros that can be removed

**Review by calvinctvo — APPROVED** [review]
Hey @joshitagaki ! Thanks for refactoring Tango's macro. LGTM

**Review by christianstokes — APPROVED** [review]
Looks good! Approved.

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
