### PR TITLE
[Backport] LRAC-13781

### PR DESCRIPTION
**Pull request by JLucasM**
Jira issue: https://issues.liferay.com/browse/LRAC-13781

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:stable

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by ilzamcmed** [comment]
ci:forward

**Pull request closed without merging**
