### PR TITLE
LPD-16508 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LPD-16508

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud

**Comment by CalumR23** [comment]
ci:test:analytics-cloud

**Comment by CalumR23** [comment]
ci:stop

**Comment by marcosapmf** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/1164

**Pull request closed without merging**
