### PR TITLE
LPD-26796 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-26796

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:stable

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @marcosapmf, acceptance failure is not related to your PR. The problem is being caused by [LPD-26134](https://liferay.atlassian.net/browse/LPD-26134). But I am investigating a possible regression bug

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
ci:forward

**Pull request closed without merging**
