### PR TITLE
AC Test Fix LRAC-14305 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14305

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good, Josh. Thanks for updating these xpaths. LGTM 🎉

**Review by manuferreira — COMMENTED** [review]
LGTM. Thanks Josh! :muscle:

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
