### PR TITLE
AC Test Fix - LRAC-14509 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14509

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by nkkwon — APPROVED** [review]
LGTM :+1:

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks for working on it :muscle:

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM!

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
