### PR TITLE
LPD-33314 | Master [Playwright]

### PR DESCRIPTION
**Pull request by interaminense**

### CODE REVIEW

**Comment by interaminense** [comment]
It depends on https://github.com/liferay-ac/liferay-portal/pull/1868

**Comment by interaminense** [comment]
ci:test:analytics-cloud

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:analytics-cloud

**Comment by interaminense** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
Merged https://github.com/brianchandotcom/liferay-portal/pull/154692

**Pull request closed without merging**
