### PR TITLE
LPD-43610 | master

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:test:relevant

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
resent with SF fix https://github.com/liferay-ac/liferay-portal/pull/1970

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
