### PR TITLE
AC Ignore Test LRAC-11942 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11942
Hey guys, I don't see the value of keeping this test considering both salesforce and csv are currently hidden. According to LRAC-11651 and LRAC-11571 it is temporary so I think keeping it ignored for the moment until it is possibly reintroduced if necessary. Let me know what you think

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Very good @joshitagaki, thanks for working on it!

**Review by calvinctvo — APPROVED** [review]
Hey @joshitagaki ! Thanks for disable this test!

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
