### PR TITLE
[F] Send follow up PR for unit tests

### PR DESCRIPTION
**Pull request by JLucasM**
LRAC-14360: [Jira Issue](https://liferay.atlassian.net/browse/LRAC-14360)

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by fmarcio** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by ViniLopes20** [comment]
Hey @JLucasM, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by fmarcio** [comment]
ci:forward:force

**Pull request closed without merging**
