### PR TITLE
LRAC-14551 Follow up

### PR DESCRIPTION
**Pull request by JLucasM**
Jira issue https://liferay.atlassian.net/browse/LRAC-14551

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Review by fmarcio — APPROVED** [review]
LGTM! thanks @JLucasM

**Comment by fmarcio** [comment]
@manuferreira @ViniLopes20 could you guys please check if the failure on "ci:test:relevant" is related or not to this PR? thanks :-)

**Comment by ViniLopes20** [comment]
Hey @JLucasM and @fmarcio, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded after the `acceptance` is passing. Thanks!

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by JLucasM** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward:force

**Pull request closed without merging**
