### PR TITLE
AC New Automated Test - LRAC-11726 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11726 (automation ticket)
https://issues.liferay.com/browse/LRAC-11659 (Bug ticket)
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1990534192&testrayRunId=1990534196)

Hey guys, I thought it was better not to check the event during this automation, the purpose of this automation is to verify that even a default event being sent using `Analytics.track` will be counted in the AC as a default event and not a custom event, so check the event is not important in this case and we could still have problems with a possible `browserMob` crash that could prejudice our test.

So I'm generating the event through `Analytics.track` and through the normal view of a WC with the custom asset and I'm verifying that the two interactions are being counted for the default event in the event analysis.

### CODE REVIEW

**Review by calvinctvo — APPROVED** [review]
Hey @ViniLopes20 ! Thank you so much for clarify the purpose of this test. I see that we don't have to check for event in browser

**Review by manuferreira — APPROVED** [review]
Thanks @calvinctvo and @ViniLopes20 :tada: :detective:

**Review by joshitagaki — APPROVED** [review]
Great job @calvinctvo and @ViniLopes20! LGTM

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
