### PR TITLE
LPD-30561 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-30561
[Testray Result](https://ff9a476d2989f7e75c15cfae40d1f7787b82e515033c6255e5acc79-apidata.googleusercontent.com/download/storage/v1/b/testray-results/o/2024-07%2Ftest-1-27%2Ftest-portal-acceptance-pullrequest(master)%2F12282%2Fplaywright-js-tomcat90-mysql57-jdk8%2F9%2F0%2Fplaywright-report%2Findex.html?jk=AYBlUPDUmQYYa9VyDO5rN_8sV5m_PAc4sLLmyTkNHpsjpuyTQ6XRZ-0OL2BwfkinZSL83iIKqPO0e2y-VEqSdPpiXA6O4zFDcJcZqSpRZqAaqS1TyDqqmjkhMW9DD_Ck-zvlPLRaGRIEwitvT2ZdAJby3MZVtNaiCUrOHxLxN0Y0lEfx5Dl4okLF08mtFdGN2wr8KrbRKVSDdqwdlKuzFUyGeEK4eB6dDGg0s86H47SAnp7vtL3Oa-_WUZ8Rk2mgaJPHngjYToTM11mXa_NUODHp2eE5xIWunl8a-kEyu4_dQvGA5r17UOpekCLsPN9kF9IN9lrgfxdxuQpmmhJXKcs_rq1yt64hEXYNTnGaLg1oJAisswhrZe1T0lorW9tTnL134Eeg9-dj8desXeVLyexohTJyxku4-nWSi2xA-AM5j7ki2Cw5UpSzag_tr5BVYuB2hAy0SjoRKM1d2hRhVJncVRiOPu4U8_QkAmI1mkvd_ekuUKzdwtZUZLRnyaJUbcR9ej_LGXevMYMvWEmrlcxvtPc7DvxqrLMX7d3xw7TunJmluGvfCYPuJdpKkXj8RkhpHorYyPqf3gixnx0kEG-hHJEd4Xyq93txfIUF-QXPcgOeqvX4onkJ6QxsDFPjGSdDvq-riPOz4b2GCrL5XtzkzfMGYnaQ3rfN2s0janTOcS0ZkfSyGGan45qiFPjRxF11V8VwGNB_Wk0NYc0EziNQ1ouxpDdX41skgd2UJtTjYtgscOLDwjOi7jGh8B-HJjpxhzWo7bDRWq-GyyVVFf6gO-2LDBdWMx6cY1BK2OFRbOMWyDkQlPcSVa-2RPlpIv9L46zbgPkmgUg1CxDkXBTEMSGjiju6a-bpFWTNHngl79zcuk4AthavpOnieBClrVcWOrikXc48ZcpEvMoOCk1HB42XOmB1fkUcVqvpU38mfChatmQQlr_t62RZsIMoHWMAc97sPcQJQiNACjEOfefhKkqem12huAO9JoZ80fV1J2qiVE9cpog0N3gHWHEGqrj9VQCeYo32IYjU-2yGPi0hH7QpkblySVlwXiV97BqOIzj75kq98jUTrnuNDRGrwXb-O3wbtaphakf6h_aVpqJ1kbB65sGftlhtulCNYMSYktkh95X5J9iNs0-2jF3C0_SDR_9xVa1hGEgEb2i_xLlYj2Y8f3xjwY0AfF5g95D6QlyNumaztfwJCm-PKT7iHtHnjcoPdQABCaRUJz2j0Z_-tUsTfER6gsDXNlLtHVhPtd7eukD4pPk7O7Yrfp6U4C5wXojBlBZ-LaeY8BA64UnbdTR5zyizMKTMiXE40yi68Ss&isca=1)

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:playwright

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:playwright

**Review by ViniLopes20 — APPROVED** [review]
Very good, @marcosapmf. Thanks for working on it 🎉

[Testray Result](https://ff9a476d2989f7e75c15cfae40d1f7787b82e515033c6255e5acc79-apidata.googleusercontent.com/download/storage/v1/b/testray-results/o/2024-07%2Ftest-1-27%2Ftest-portal-acceptance-pullrequest(master)%2F12282%2Fplaywright-js-tomcat90-mysql57-jdk8%2F9%2F0%2Fplaywright-report%2Findex.html?jk=AYBlUPDUmQYYa9VyDO5rN_8sV5m_PAc4sLLmyTkNHpsjpuyTQ6XRZ-0OL2BwfkinZSL83iIKqPO0e2y-VEqSdPpiXA6O4zFDcJcZqSpRZqAaqS1TyDqqmjkhMW9DD_Ck-zvlPLRaGRIEwitvT2ZdAJby3MZVtNaiCUrOHxLxN0Y0lEfx5Dl4okLF08mtFdGN2wr8KrbRKVSDdqwdlKuzFUyGeEK4eB6dDGg0s86H47SAnp7vtL3Oa-_WUZ8Rk2mgaJPHngjYToTM11mXa_NUODHp2eE5xIWunl8a-kEyu4_dQvGA5r17UOpekCLsPN9kF9IN9lrgfxdxuQpmmhJXKcs_rq1yt64hEXYNTnGaLg1oJAisswhrZe1T0lorW9tTnL134Eeg9-dj8desXeVLyexohTJyxku4-nWSi2xA-AM5j7ki2Cw5UpSzag_tr5BVYuB2hAy0SjoRKM1d2hRhVJncVRiOPu4U8_QkAmI1mkvd_ekuUKzdwtZUZLRnyaJUbcR9ej_LGXevMYMvWEmrlcxvtPc7DvxqrLMX7d3xw7TunJmluGvfCYPuJdpKkXj8RkhpHorYyPqf3gixnx0kEG-hHJEd4Xyq93txfIUF-QXPcgOeqvX4onkJ6QxsDFPjGSdDvq-riPOz4b2GCrL5XtzkzfMGYnaQ3rfN2s0janTOcS0ZkfSyGGan45qiFPjRxF11V8VwGNB_Wk0NYc0EziNQ1ouxpDdX41skgd2UJtTjYtgscOLDwjOi7jGh8B-HJjpxhzWo7bDRWq-GyyVVFf6gO-2LDBdWMx6cY1BK2OFRbOMWyDkQlPcSVa-2RPlpIv9L46zbgPkmgUg1CxDkXBTEMSGjiju6a-bpFWTNHngl79zcuk4AthavpOnieBClrVcWOrikXc48ZcpEvMoOCk1HB42XOmB1fkUcVqvpU38mfChatmQQlr_t62RZsIMoHWMAc97sPcQJQiNACjEOfefhKkqem12huAO9JoZ80fV1J2qiVE9cpog0N3gHWHEGqrj9VQCeYo32IYjU-2yGPi0hH7QpkblySVlwXiV97BqOIzj75kq98jUTrnuNDRGrwXb-O3wbtaphakf6h_aVpqJ1kbB65sGftlhtulCNYMSYktkh95X5J9iNs0-2jF3C0_SDR_9xVa1hGEgEb2i_xLlYj2Y8f3xjwY0AfF5g95D6QlyNumaztfwJCm-PKT7iHtHnjcoPdQABCaRUJz2j0Z_-tUsTfER6gsDXNlLtHVhPtd7eukD4pPk7O7Yrfp6U4C5wXojBlBZ-LaeY8BA64UnbdTR5zyizMKTMiXE40yi68Ss&isca=1)

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
Format issues are not related to this pull. Manually forwarding to https://github.com/brianchandotcom/liferay-portal/pull/152697

**Pull request closed without merging**
