### PR TITLE
LRAC-11979 - [F] Make request to get properties from backend

### PR DESCRIPTION
**Pull request by ilzamcmed**
[https://issues.liferay.com/browse/LRAC-11979](https://issues.liferay.com/browse/LRAC-11979)

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:sf

**Review by fmarcio — APPROVED** [review]
As long as the tests passes, LGTM! :rocket:

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
resent to https://github.com/liferay-ac/liferay-portal/pull/122

**Pull request closed without merging**
