### PR TITLE
LRAC-12050 Final adjustments

### PR DESCRIPTION
**Pull request by interaminense**
- LRAC-12050 Final adjustments
- LRAC-12050 Generated types

### CODE REVIEW

**Comment by interaminense** [comment]
ci:forward

**Review by fmarcio — APPROVED** [review]
LGTM!

**Comment by interaminense** [comment]
ci:reevaluate:1267401_5345

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
Resent to https://github.com/brianchandotcom/liferay-portal/pull/124254

**Pull request closed without merging**
