### PR TITLE
LRAC-14009 Backport translations

### PR DESCRIPTION
**Pull request by interaminense**
Jira Issue: https://issues.liferay.com/browse/LRAC-14009

### CODE REVIEW

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward:force

**Comment by ilzamcmed** [comment]
ci:forward:force

**Pull request closed without merging**
