### PR TITLE
AC Test fix - LRAC-13401 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-13401 (Disable Tests and Macros)
https://issues.liferay.com/browse/LRAC-13440 (Enable Tests and Macros)
https://issues.liferay.com/browse/LRAC-13389 (Ticket that hide the functionality to delete property data source)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks for working on this Vini! LGTM!

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
Hey Vini, thanks for working on it! It would be good if we had a way to ignore a macro in poshi, instead of commenting all these lines lol

**Review by nkkwon — APPROVED** [review]
Thank you for working on this! Looks good to me! :+1:

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
