### PR TITLE
LRAC-14307 [F] When resizing the screen in AC you can see in the menu what seems like a route definition

### PR DESCRIPTION
**Pull request by fmarcio**
https://liferay.atlassian.net/browse/LRAC-14307

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @fmarcio

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:stable

**Comment by fmarcio** [comment]
ci:test:stable

**Comment by fmarcio** [comment]
@ViniLopes20 could you please check if the failure on 'relevant' is related to this PR? thanks!

**Comment by ViniLopes20** [comment]
Hey @fmarcio, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded. Thanks!

**Comment by fmarcio** [comment]
ci:forward:force

**Pull request closed without merging**
