### PR TITLE
LRAC-14858 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://liferay.atlassian.net/browse/LRAC-14858

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by marcellustavares** [comment]
@rachaelkoestartyo, please send a follow-up with a way we can enable/disable this API based on ENV_VAR (maybe  based on `graphql.api.enabled`. I would like to enable this API for UAT only.

Thanks

**Pull request closed without merging**
