### PR TITLE
LRAC-13956 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**
Jira ticket: https://issues.liferay.com/browse/LRAC-13956

### CODE REVIEW

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Review by ilzamcmed — APPROVED** [review]
LGTM :rocket:

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @leilanyaragao

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
