### PR TITLE
AC Convert Test and Test Improvement - LPD-30749 and LPD-29909 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LPD-30749
https://liferay.atlassian.net/browse/LPD-29909
https://github.com/liferay/com-liferay-osb-asah-private/pull/5872
[Testray](https://testray.liferay.com/#/project/34880/routines/730294/build/44451660)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
