### PR TITLE
LRAC-14149 [F] CSV data source is still mentioned in add data source page

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LRAC-14149

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hey @fmarcio, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded after the `stable` is passing. Thanks!

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
