### PR TITLE
AC Test Fix - LRAC-12432 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-12432

### CODE REVIEW

**Review by ViniLopes20 — APPROVED** [review]
LGTM. Thanks for working on it, Josh 🎉

**Review by calvinctvo — APPROVED** [review]
Hey @joshitagaki ! Thanks for the fix! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks Josh :tada:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
