### PR TITLE
AC Test Fix - LRAC-14564 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14564

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM!

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for looking into it! :muscle:

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Comment by nkkwon** [comment]
ci:forward

**Pull request closed without merging**
