### PR TITLE
AC Test fix - LRAC-11341 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11341 (Automation ticket)
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1884488956&testrayRunId=1884490039)
[Commit that caused the problem](https://github.com/ViniLopes20/liferay-portal/commit/b4962479e7b728f7179e86bef7173e7bfa72bd38)

**Solution:**
This commit caused the problem, after this change the test started to fail on the CI. The problem is because when the macro opens the BBC site in a new browser tab, it first opens a new tab (Crtl + t) after the macro quickly returns to the AC page causing the _tabFocused_ event to be sent. So when the test comes to the end, two _tabFocused_ events are present, not just one.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
That's interesting good catch! LGTM!

**Review by calvinctvo — APPROVED** [review]
Nice catch @ViniLopes20 LGTM

**Review by manuferreira — APPROVED** [review]
LGTM Vini, thank you. :tada:

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
