### PR TITLE
AC Test Fix - LRAC-11952 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11952
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2014339155&testrayRunId=2014339230)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you, Josh :muscle:

**Review by calvinctvo — APPROVED** [review]
Thanks @joshitagaki for the fix! LGTM

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
