### PR TITLE
AC Test Fix - LRAC-14554 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://liferay.atlassian.net/browse/LRAC-14554

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Review by ViniLopes20 — APPROVED** [review]
Very good, Josh. Strange that we had so many tests using liferay dxp that is not the data source that appears in CI. Thanks for fixing this, LGTM 🎉

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for updating all of these tests! :detective:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
