### PR TITLE
AC Test Fix - LRAC-12454 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
Test Fix ticket - https://issues.liferay.com/browse/LRAC-12454
[Test Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2086947146&testrayRunId=2086995494)

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks for fixing this!

**Review by ViniLopes20 — APPROVED** [review]
Thanks for working on it, Calvin. LGTM 🎉

**Review by manuferreira — APPROVED** [review]
LGTM! Thank you Calvin :tada:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
