### PR TITLE
AC Test Fix - LRAC-11557 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11557
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1919959809&testrayRunId=1920087552)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Hey @joshitagaki ! Thanks for the fix! LGTM

**Review by christianstokes — APPROVED** [review]
Nice and simple 😄 
LGTM.

**Review by ViniLopes20 — APPROVED** [review]
Good catch, Josh. LGTM 🎉

**Comment by calvinctvo** [comment]
Hey guys, thanks for the review! I'm forwarding this PR

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
