### PR TITLE
 Enable Test LRAC-11639 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRAC-11639 (Bug Ticket)
Enable AssetsDocumentsAndMedia#VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM to acceptance
Remove AssetsDocumentsAndMedia#ViewAllDocumentsAndMediaShownInAssetList from acceptance

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Hey @calvinctvo, thanks for working on this and enabling our test for acceptance again.

I think we can keep this PR with the "**On Hold**" tag to carry out this modification only when we are only using BQ for the release branch and for the `latest` tags that are used in the portal. If we make this modification now, then the PR sent to the release branches or to the portal teams that use our acceptance will observe that this test will fail because it will still be using ES, so after release 4.0.0 we should be able to make this modification and forward this PR

Thank you for opening this PR so we don't forget to do this in the future 🎉 😄

**Review by joshitagaki — APPROVED** [review]
Thanks Calvin! LGTM!

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks Calvin :tada:

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
