### PR TITLE
LPS-200577

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
Creates new Collection provider for User's Personalized Content Recommendations, it supports category filtering and class name prefiltering (filter by item type). Also mark this collection provider as Beta and hide it behind **LRAC-14771** feature flag.

Proposed Solution
-----
Creates new InfoCollectionClass for User's Personalized Content Recommendations, implementing:
* **BetaInfoCollectionProvider**<AssetEntry> -> Mark it as beta
* **ConfigurableInfoCollectionProvider**<AssetEntry> -> Allow users pre filter the collection by item type
* **FilteredInfoCollectionProvider**<AssetEntry> -> Allow users add a filter to filter the collection by categories

To make it possible I made some changes in **UserContentRecommendationManager**:
* Pagination was added to getUserContentRecommendations
* New method to get count 
* Supports to filter by classNameIds

Commits to review:
* 1aeeecd1617d47ba48f1350288a35ebb79c93308
* 90361120407ac151fae1ea048a2b6d705b478f74
* 254ed9ed5e094a9ca002f70de3ca57e65d96089c

Please let me know if you have any question.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @ealonso, the failure of `acceptance` is not related to your modifications. Thanks!

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by marcellustavares** [comment]
thanks @ealonso!

**Comment by marcellustavares** [comment]
manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/143260

**Pull request closed without merging**
