### PR TITLE
LRAC-12928 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-12928

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:stop

**Pull request closed without merging**
