### PR TITLE
LRAC-12602 fix sorting on sites and channels tab

### PR DESCRIPTION
**Pull request by thiago-buarqque**
[PR already sent to Brian](https://github.com/brianchandotcom/liferay-portal/pull/127884), just making some SF

### CODE REVIEW

**Comment by thiago-buarqque** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Comment by thiago-buarqque** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Sent directly to Brian https://github.com/brianchandotcom/liferay-portal/pull/127956

**Pull request closed without merging**
