### PR TITLE
LRAC-12756 Fix case-sensitive sort

### PR DESCRIPTION
**Pull request by riccardo-ferrari**

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Review by thiago-buarqque — APPROVED** [review]
LGTM

**Comment by thiago-buarqque** [comment]
ci:forward

**Comment by thiago-buarqque** [comment]
ci:forward

**Pull request closed without merging**
