### PR TITLE
LRAC-12619  Global checkbox should select all items from current page

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://issues.liferay.com/browse/LRAC-12619

### CODE REVIEW

**Comment by interaminense** [comment]
This PR needs a rebase from https://github.com/liferay-ac/liferay-portal/pull/212

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Review by ilzamcmed — APPROVED** [review]
Thanks @interaminense!
LGTM :rocket:

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:stop

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Pull request closed without merging**
