### PR TITLE
AC Automated Test - LRAC-12355 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11903 (Bug)
https://issues.liferay.com/browse/LRAC-12355 (Automation ticket)
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2079160211&testrayRunId=2079160217)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Thanks Vini

**Review by calvinctvo — APPROVED** [review]
Hey @ViniLopes20 ! Great test! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for the automation and the macro :tada: :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
