### PR TITLE
LRAC-14300 Use portal to render dropdown outside the Modal

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://issues.liferay.com/browse/LRAC-14300

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:forward:force

**Pull request closed without merging**
