### PR TITLE
LRAC-12757 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**
Jira Issue: https://issues.liferay.com/browse/LRAC-12757

### CODE REVIEW

**Comment by leilanyaragao** [comment]
ci:test:sf

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
LGTM!

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
