### PR TITLE
[ON HOLD] LPD-15137 Upgrade FARO frontend to use node ^18

### PR DESCRIPTION
**Pull request by interaminense**
https://liferay.atlassian.net/browse/LPD-15137

### CODE REVIEW

**Comment by interaminense** [comment]
I opened a thread about the error that is happening on this PR https://liferay.slack.com/archives/CLBE14570/p1704306710915699

On hold until this task is implemented https://liferay.atlassian.net/browse/LRCI-3921

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @interaminense, the acceptance failure is related to this [bug](https://liferay.atlassian.net/browse/LPD-17914). But from the result, I can see that the AC can be built correctly without any problems

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
Resent to https://github.com/liferay-ac/liferay-portal/pull/1124

**Pull request closed without merging**
