### PR TITLE
LRAC-14418 | master

### PR DESCRIPTION
**Pull request by lesliewong92**
https://liferay.atlassian.net/browse/LRAC-14418

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
Hey @lesliewong92, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded after the `stable` is passing. Thanks!

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:forward:force

**Pull request closed without merging**
