### PR TITLE
LRAC-14827 New Path Analysis

### PR DESCRIPTION
**Pull request by interaminense**
Jira issue: https://issues.liferay.com/browse/LRAC-14827

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward:force

**Comment by marcellustavares** [comment]
ci:stop

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
