### PR TITLE
AC Test Fix - LRAC-12002 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-12002 (Automation ticket)
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2006054186&testrayRunId=2006081260)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Nice fix! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks Vini :tada: :police_officer:

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
