### PR TITLE
AC Test Fix - LRAC-11340 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11340 (ticket)
[Testray Result](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1872588750&testrayRunId=1872588760)

**Solutions:**
This test started to fail after the [story](https://issues.liferay.com/browse/LRAC-10999) changes, before the identity event was triggered every time you log in, the userId was changed, but now when you log out the userId remains the same, so you need to clear the local storage so when you log in again it needs to pull the userId again, that way the identity event will be resent.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Can probably remove the first commit now that LRAC-11306 is in upstream.

**Comment by ViniLopes20** [comment]
ci:test:sff

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Hey @ViniLopes20 thanks for working on this! LGTM

**Review by manuferreira — APPROVED** [review]
Nice Vini, LGTM :tada:

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
