### PR TITLE
Revert "LRAC-13968 sort NULLS last"

### PR DESCRIPTION
**Pull request by sillascavalcanti**
This reverts commit cba60a044b5a80cce376ff1a27c78f2b7787d367.

### CODE REVIEW

**Comment by interaminense** [comment]
ci:forward

**Comment by pyoo47** [comment]
@sillascavalcanti I had to abort the `relevant` test because it froze in CI

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:test:stable

**Pull request closed without merging**
