### PR TITLE
LRAC-12806 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @rachaelkoestartyo, could you resolve the conflict and resend that PR? [Josh approved the changes in 7.4](https://liferay.atlassian.net/browse/LRAC-13664?focusedCommentId=2423592), so we can forward this PR after resolving the conflicts. Thanks

**Comment by rachaelkoestartyo** [comment]
resent https://github.com/liferay-ac/liferay-portal/pull/637

**Pull request closed without merging**
