### PR TITLE
AC Automation Test - LRAC-14041 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-14041
https://issues.liferay.com/browse/LRAC-14042
https://issues.liferay.com/browse/LRAC-14043
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2352804535&testrayRunId=2352804912)
[Story](https://issues.liferay.com/browse/LRAC-13424)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM! Hopefully the user will appear in time when adding static segments once we run it through our normal test routines.

**Review by nkkwon — APPROVED** [review]
LGTM! 👍 Thanks for working on this

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks for the work! :detective: :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
