### PR TITLE
LRAC-11981 - [F] Create modal to assign channels and sites to the property

### PR DESCRIPTION
**Pull request by ilzamcmed**

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:foward

**Comment by ilzamcmed** [comment]
Merged

**Pull request closed without merging**
