### PR TITLE
LPD-26134 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-26134

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
acceptance failures fixed in https://github.com/liferay-ac/liferay-portal/pull/1643

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
