### PR TITLE
LPD-24609 | master

### PR DESCRIPTION
**Pull request by ivicac**

### CODE REVIEW

**Comment by interaminense** [comment]
LGTM! Thanks @ivicac

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:test:analytics-cloud-acceptance

**Comment by interaminense** [comment]
ci:forward

**Comment by lesliewong92** [comment]
Created 4.7.x backport https://github.com/liferay-ac/liferay-portal/pull/1527

**Pull request closed without merging**
