### PR TITLE
AC Disable Test - LRAC-11185 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11185 (Bug)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Hey @ViniLopes20 ! Thanks for disable the test

**Review by christianstokes — APPROVED** [review]
Approved

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
