### PR TITLE
LPD-31392 Update base DXP image to U124 | 4.8.x

### PR DESCRIPTION
**Pull request by lesliewong92**
https://liferay.atlassian.net/browse/LPD-31392

### CODE REVIEW

**Comment by lesliewong92** [comment]
See [comment](https://liferay.atlassian.net/browse/LPD-31392?focusedCommentId=2698816) on ticket  for alternative solution if we do not want to update the base image.

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcosapmf** [comment]
ci:re

**Pull request merged**
