### PR TITLE
 LRAC-15260 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://liferay.atlassian.net/browse/LRAC-15260

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:startup

**Comment by rachaelkoestartyo** [comment]
ci:test:upgrade

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
Hey @rachaelkoestartyo, the failure of `acceptance` is related to this [bug](https://liferay.atlassian.net/browse/LRAC-15298). The PR looks good to be forwarded after the stable is passing. Thanks!

**Comment by rachaelkoestartyo** [comment]
ci:test:upgrade

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
