### PR TITLE
LPD-23156 | master

### PR DESCRIPTION
**Pull request by lesliewong92**
https://liferay.atlassian.net/browse/LPD-23156

### CODE REVIEW

**Comment by marcellustavares** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
ci:test:sf

**Comment by marcellustavares** [comment]
ci:test:stable

**Comment by marcellustavares** [comment]
ci:test:relevant

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:sf

**Comment by lesliewong92** [comment]
ci:test:analytics-cloud-acceptance

**Comment by lesliewong92** [comment]
ci:test:stable

**Comment by lesliewong92** [comment]
ci:test:relevant

**Comment by marcellustavares** [comment]
ci:forward

**Pull request closed without merging**
