### PR TITLE
LRAC-12562 Fix empty state on Properties

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue: https://issues.liferay.com/browse/LRAC-12562

### CODE REVIEW

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Comment by interaminense** [comment]
ci:forward

**Review by fmarcio — APPROVED** [review]
LGTM! :rocket:

**Comment by interaminense** [comment]
Sent directly to Brian's repo https://github.com/brianchandotcom/liferay-portal/pull/127659

**Pull request closed without merging**
