### PR TITLE
AC Test Fix - LRAC-13355 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-13355
[Testray](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2308107044)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Thanks for fixing this, Josh. LGTM 🎉

**Review by nkkwon — APPROVED** [review]
Thank you for working on this! LGTM! :+1:

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you, Josh. :tada:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
