### PR TITLE
LRAC-14134 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-14134
Jira ticket: https://issues.liferay.com/browse/LRAC-12110 [Backport]

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @marcosapmf, the failure of `relevant` is not related to your modifications. The PR looks good to be forwarded after the `stable` is passing. Thanks!

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
