### PR TITLE
LPD-21483 | master

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Review by rachaelkoestartyo — APPROVED** [review]

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Review by marcosapmf — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:forward

**Pull request closed without merging**
