### PR TITLE
LPS-199328 Don't use metal utility

### PR DESCRIPTION
**Pull request by sandrodw3**
Hi guys! 😄 in this PR I'm removing the last usages of `metal` that we had in `osb-faro-web`. Here's [the link to the ticket](https://liferay.atlassian.net/browse/LPS-199328), please let me know when you have time to take a look!

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Review by interaminense — APPROVED** [review]
LGTM! Thanks @sandrodw3

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by JLucasM** [comment]
Follow up: https://github.com/liferay-ac/liferay-portal/pull/783

**Pull request closed without merging**
