### PR TITLE
LRAC-15298 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-15298

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud-acceptance

**Comment by ViniLopes20** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:forward:force

**Comment by ViniLopes20** [comment]
ci:forward:force

**Pull request closed without merging**
