### PR TITLE
LRAC-13061 [C] Add missing property called title in the fieldFocused and fieldBlurred events

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://issues.liferay.com/browse/LRAC-13061

### CODE REVIEW

**Review by interaminense — APPROVED** [review]
LGTM!

**Comment by interaminense** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:forward

**Pull request closed without merging**
