### PR TITLE
AC Test Fix - LRAC-14517 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14517

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM! Thank you, Vini :male_detective:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
