### PR TITLE
AC Remove Test - LRAC-13333 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-13333
See comments in: https://issues.liferay.com/browse/LRAC-12930
Removing these test cases as they are no longer available.

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks Josh 🎉

**Review by nkkwon — APPROVED** [review]
LGTM! 👍

**Review by manuferreira — APPROVED** [review]
LGTM. Thank you, Josh! :tada: :muscle:

**Comment by manuferreira** [comment]
ci:forward

**Pull request closed without merging**
