### PR TITLE
LPD-40124 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-40124

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Review by marcellustavares — APPROVED** [review]

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
Failure is not related. Same test failed in https://github.com/liferay-ac/liferay-portal/pull/1919 without these changes.

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
