### PR TITLE
LRAC-15258 LRAC-15259 | master

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://liferay.atlassian.net/browse/LRAC-15258
https://liferay.atlassian.net/browse/LRAC-15259

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:upgrade

**Comment by rachaelkoestartyo** [comment]
ci:test:startup

**Comment by ViniLopes20** [comment]
ci:test:analytics-cloud-acceptance

**Comment by marcellustavares** [comment]
ci:forward:force

**Pull request closed without merging**
