### PR TITLE
LPD-30450 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://liferay.atlassian.net/browse/LPD-30450

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud

**Comment by marcosapmf** [comment]
ci:test:analytics-cloud

**Review by ViniLopes20 — APPROVED** [review]
Very nice, @marcosapmf. Remove the CI test commit and forward this PR. Thanks for working on it 🎉

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
