### PR TITLE
AC Automation Improvements - LRAC-14238 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://liferay.atlassian.net/browse/LRAC-14238

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
The SF problem is related to this [thread](https://liferay.slack.com/archives/CD7939WBE/p1688108216527859)

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM!

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
