### PR TITLE
AC Test fix - LRAC-11273 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11273

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
Thread: https://liferay.slack.com/archives/GP37V21A6/p1653667339741209
Might need to update test depending on answer

**Comment by joshitagaki** [comment]
Demo data was [not appearing](https://issues.liferay.com/browse/LRAC-11163) causing the second state to be what was showing. Now that demo data is back we're seeing the first state

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks Josh :mag:

**Review by calvinctvo — APPROVED** [review]
Thanks @joshitagaki LGTM

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Pull request closed without merging**
