### PR TITLE
LRAC-11500 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-11500

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by marcosapmf** [comment]
ci:test:stable

**Comment by interaminense** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:forward:force

**Comment by marcosapmf** [comment]
ci:forward:force

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:forward:force

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:forward:force

**Pull request closed without merging**
