### PR TITLE
LRAC-13451| master

### PR DESCRIPTION
**Pull request by leilanyaragao**
Jira Issue: https://issues.liferay.com/browse/LRAC-13451

### CODE REVIEW

**Comment by leilanyaragao** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
Hey @leilanyaragao, I looked into it here and apparently the issues are flaky and not related to your changes

**Comment by leilanyaragao** [comment]
ci:forward

**Pull request closed without merging**
