### PR TITLE
LRAC-11874 - [F] Implement Workspace connection step / LRAC-11909 - [F] Implement Sidebar after connection is done

### PR DESCRIPTION
**Pull request by ilzamcmed**
[https://issues.liferay.com/browse/LRAC-11899](https://issues.liferay.com/browse/LRAC-11899)

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:master:analytics-cloud-acceptance

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
Resent to https://github.com/liferay-ac/liferay-portal/pull/113

**Pull request closed without merging**
