### PR TITLE
LRAC-14129 The detail tabs of interest in a segment are colored blue instead of gray and it is not indicating which tab the user is accessing

### PR DESCRIPTION
**Pull request by fmarcio**
Jira issue https://liferay.atlassian.net/browse/LRAC-14129

### CODE REVIEW

**Comment by fmarcio** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by ViniLopes20** [comment]
ci:test:relevant

**Comment by interaminense** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward:force

**Comment by ViniLopes20** [comment]
ci:forward:force

**Pull request closed without merging**
